### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#1]
i'm not going to paste all log, is very large and i need to filter username

```
.......................
[ 33%] Completed 'SDLMixerX_Local'
[ 36%] Built target SDLMixerX_Local
[ 37%] Building CXX object CMakeFiles/thextech.dir/src/game_main.cpp.o
[ 38%] Building CXX object CMakeFiles/thextech.dir/src/sound.cpp.o
[ 39%] Building CXX object CMakeFiles/thextech.dir/src/main/world_loop.cpp.o
[ 40%] Building CXX object CMakeFiles/thextech.dir/src/main/world_file.cpp.o
/Users/username/lab/test/H/TheXTech/src/game_main.cpp:1251:27: error: 
      call to 'abs' is ambiguous
            if((int(XnH + std::abs((int(XnH * 100) % 800) / 100)) * 100) ...
                          ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:664:1: note: 
      candidate function
abs(float __lcpp_x) _NOEXCEPT {return fabsf(__lcpp_x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:668:1: note: 
      candidate function
abs(double __lcpp_x) _NOEXCEPT {return fabs(__lcpp_x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:672:1: note: 
      candidate function
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}
^
/Users/username/lab/test/H/TheXTech/src/game_main.cpp:1252:26: error: 
      call to 'abs' is ambiguous
                XnHfix = std::abs((int(XnH * 100) % 800) / 100);
                         ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:664:1: note: 
      candidate function
abs(float __lcpp_x) _NOEXCEPT {return fabsf(__lcpp_x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:668:1: note: 
      candidate function
abs(double __lcpp_x) _NOEXCEPT {return fabs(__lcpp_x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:672:1: note: 
      candidate function
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}
^
/Users/username/lab/test/H/TheXTech/src/game_main.cpp:1254:26: error: 
      call to 'abs' is ambiguous
                XnHfix = std::abs(8 - ((int(XnH * 100) % 800) / 100));
                         ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:664:1: note: 
      candidate function
abs(float __lcpp_x) _NOEXCEPT {return fabsf(__lcpp_x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:668:1: note: 
      candidate function
abs(double __lcpp_x) _NOEXCEPT {return fabs(__lcpp_x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:672:1: note: 
      candidate function
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}
^
3 errors generated.
make[2]: *** [CMakeFiles/thextech.dir/src/game_main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 41%] Building CXX object CMakeFiles/thextech.dir/src/main/game_loop.cpp.o
make[1]: *** [CMakeFiles/thextech.dir/all] Error 2
make: *** [all] Error 2
```

i have Xcode 8.2.1 in macosx 10.11.6, i tried "make -j 2" "make -j 4" "Ninja" and Xcodeproject

what is the problem?

**Comment by Wohlstand** [comment]
Odd :thinking: 
Gonna to verify why this happens...

**Comment by Wohlstand** [comment]
Yeah, I see a reason:
https://stackoverflow.com/questions/56978365/how-to-fix-error-call-to-abs-is-ambiguous

gonna to make a workaround for that :thinking:

**Comment by Wohlstand** [comment]
Just now I sent a fix, can you try to build it?

**Comment by M0REKZ** [comment]
fixed? i will try to install and make it with "make -j 2" (if not, with "make -j 4")

**Comment by Wohlstand** [comment]
A tip if you not know: use `git pull` to quickly download a change from a clonned repo.

**Comment by Wohlstand** [comment]
>  "make -j 2" (if not, with "make -j 4")

The -j X means a count of threads, I.e. you can specify a count of CPU cores that you have to get the build faster.

**Comment by M0REKZ** [comment]
lol

**Comment by M0REKZ** [comment]
make -j 2 is finished with "[100%] Linking CXX executable output/bin/TheXTech.app/Contents/MacOS/TheXTech
[100%] Built target thextech"

:+1:

**Comment by M0REKZ** [comment]
i will install files for test

**Comment by Wohlstand** [comment]
Nice :fox_face: 
So, enjoy a game :wink:

**Comment by M0REKZ** [comment]
thanks

**Comment by M0REKZ** [comment]
Then, again the problem, since the game crashed when starting it #45 , I decided to try to compile it myself, but I get an error



`-- Installing: /Users/USERNAME/lab/thexthex/again/TheXTech/build/output/lib/pkgconfig/SDL2_mixer_ext.pc
[ 38%] Completed 'SDLMixerX_Local'
[ 38%] Built target SDLMixerX_Local
Scanning dependencies of target thextech
[ 39%] Building CXX object CMakeFiles/thextech.dir/src/compat.cpp.o
[ 39%] Building CXX object CMakeFiles/thextech.dir/src/game_main.cpp.o
[ 40%] Building CXX object CMakeFiles/thextech.dir/src/globals.cpp.o
[ 41%] Building CXX object CMakeFiles/thextech.dir/src/npc.cpp.o
[ 42%] Building CXX object CMakeFiles/thextech.dir/src/sound.cpp.o
[ 42%] Building CXX object CMakeFiles/thextech.dir/src/frame_timer.cpp.o
[ 43%] Building CXX object CMakeFiles/thextech.dir/src/main/world_loop.cpp.o
/Users/USERNAME/lab/thexthex/again/TheXTech/src/frame_timer.cpp:129:19: error: 
      use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
    clock_gettime(CLOCK_MONOTONIC_RAW, &ts);
                  ^
1 error generated.
make[2]: *** [CMakeFiles/thextech.dir/src/frame_timer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/thextech.dir/all] Error 2
make: *** [all] Error 2
`

i only tried build the debug version

please reopen this issue

**Comment by Wohlstand** [comment]
> frame_timer.cpp:129:19: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW' clock_gettime(CLOCK_MONOTONIC_RAW, &ts);

:thinking: :thinking: :thinking: :thinking: :thinking: 
Weird that this thing is absent here... 

Try to pull now and re-run the build, I made the little tweak that should help you...

**Comment by M0REKZ** [comment]
i still get the same error:

`/Users/USERNAME/lab/thexthex/again/TheXTech/src/frame_timer.cpp:129:19: error: 
      use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
    clock_gettime(CLOCK_MONOTONIC_RAW, &ts);
                  ^
1 error generated.
make[2]: *** [CMakeFiles/thextech.dir/src/frame_timer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/thextech.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by Wohlstand** [comment]
btw, @M0REKZ, please make a new issue for the new fault. Don't continue the discussion related to the old build fault.

**Comment by Wohlstand** [comment]
BTW. I made another fix, try to build it then. Also, tell me does the game speed works normally or faster/slower than it should be? That means if it will fail, I will need to tweak the frame rate controller to fix it. Right now on Windows XP, it works incorrectly.

**Comment by M0REKZ** [comment]
>btw, @M0REKZ, please make a new issue for the new fault. Don't continue the discussion related to the old build fault.

sorry, ill do it next time

**Comment by M0REKZ** [comment]
uh:

`/Users/Username/lab/thexthex/again/TheXTech/src/frame_timer.cpp:137:19: error: 
      use of undeclared identifier 'CLOCK_MONOTONIC'
    clock_gettime(XTECH_CLOCK_TYPE, &ts);
                  ^
/Users/username/lab/thexthex/again/TheXTech/src/frame_timer.cpp:41:33: note: 
      expanded from macro 'XTECH_CLOCK_TYPE'`
`#       define XTECH_CLOCK_TYPE CLOCK_MONOTONIC`
                                `^
1 error generated.
make[2]: *** [CMakeFiles/thextech.dir/src/frame_timer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/thextech.dir/all] Error 2
make: *** [all] Error 2`

**Comment by Wohlstand** [comment]
Damn, probably I'll try std::chrono here instead of this.......

**Comment by Wohlstand** [comment]
@M0REKZ, please pull again and try to build the game.

**Comment by M0REKZ** [comment]
:(

![Captura de pantalla 2021-03-21 a las 8 10 33 p m](https://user-images.githubusercontent.com/60852359/111924122-97f8a080-8a81-11eb-9a59-32604b478215.png)

**Comment by Wohlstand** [comment]
You should clean-up your build directory and restart the build from the scratch

**Comment by M0REKZ** [comment]
i deleted the old source and tried to build the new

**Comment by Wohlstand** [comment]
What is a full log is? Can you save it into a TXT file and drop it here? (you can upload some file types directly into GitHub)

**Comment by M0REKZ** [comment]
here is the Make log:

[somelog.txt](https://github.com/Wohlstand/TheXTech/files/6178593/somelog.txt)

**Comment by Wohlstand** [comment]
Ah, understood, you did the build of debug version, and it tried to build the FLAC library as the `libFLACd.a`, but the game had to look for the `libFLAC.a`, that an odd... It should find debug versions properly :thinking: 

Anyway, right now you need to build the project as a MinSizeRel:

```
-DCMAKE_BUILD_TYPE=MinSizeRel
```
to just compile the release build as-is.

**Comment by M0REKZ** [comment]
I managed to compile it and it seems to work fine, thanks for the help

ill close the crash issue
