### ISSUE TITLE
"--" Option Cannot Be Used Before File Path For "-l"

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#11]
```
$ smbx -l -- level1.lvl
PARSE ERROR: Argument: level1.lvl
             Couldn't find match for argument

Brief USAGE:
   smbx  [-i] [-k] [-x] [-m] [-a] [-g] [-b] [-p] [-s] [-f] [-2
               <c1;s2;m0;t0 : c - character, s - state, m - mount, t -
               mount type>] [-1 <c1;s2;m0;t0 : c - character, s - state, m
               - mount, t - mount type>] [-n <number 1 or 2>] [-l <file
               path>] [-r <render type>] [--] [--version] [-h]

For complete USAGE and HELP type:
   smbx --help
```
The general purpose of `--` as an argument is so that files who's name begins with a `-` can be interpreted as a file.

When scripting (Such as writing a custom launcher via bash/zenity) or making a `.desktop` file to associate levels with it'd be wise to use this argument for the sake of reliability.

However, in this case, it cannot be used before a file name as in:
 `smbx -l -- level.lvl` because TheXTech does not appear to account for this.

And *this*:
 `smbx -- -l level.lvl` could never work because `-l` would no longer be interpreted as an argument. 

This ultimately kind of renders this argument (`--`) unusable.

**Comment by Wohlstand** [comment]
The blame to API I did to pass level file path as the "-lLevelFile.lvlx" rather just a nameless argument. Thanks for a notice, I'll change that.

**Comment by ChristianSilvermoon** [comment]
No problem ^^

Are feature suggestions as issues welcome as well?
My apologies if this is the wrong place to ask, I don't have a lot of experience when it comes to Issues on others' repos :P

Huge fan of your work, Wohlstand, I really appreciate ya ^^

**Comment by Wohlstand** [comment]
> Are feature suggestions as issues welcome as well?

Feel free to suggest anything you want, I'll implement if possible and if I'll have a time for that :wink:

**Comment by Wohlstand** [comment]
Done just now, level test path argument no longer  requires the -l argument: just pass the file path or after `--` sign.
So, you do NOT need to use `-l "file path"` argument, just `./thextech path/to/file.lvlx`

**Comment by ChristianSilvermoon** [comment]
Very nice! Even better, actually. Awesome!

**Comment by Wohlstand** [comment]
Great!
So, closing this as complete.
