### ISSUE TITLE
(Bug) Tank treads move through blocks

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#113]
The SMB3 tank treads, when they walk into a wall, continue moving, instead of halting or reversing their course.
[tanktreadswallbug.zip](https://github.com/Wohlstand/TheXTech/files/6534604/tanktreadswallbug.zip)

**Comment by 0lhi** [comment]
Hey there. Please make use of the Issue Template when reporting a bug. Also, you should upload your footage to a site like [Imgur](https://imgur.com/), or GitHub itself, so that people without Discord can see it.

**Comment by P-Star7** [comment]
> Hey there. Please make use of the Issue Template when reporting a bug. Also, you should upload your footage to a site like [Imgur](https://imgur.com/), or GitHub itself, so that people without Discord can see it.

How do I upload a level to GitHub?

**Comment by Wohlstand** [comment]
> How do I upload a level to GitHub?

Simply pack it into the `.zip` archive, and drop the archive into here, easy!

**Comment by 0lhi** [comment]
You may also click where the red arrow points, and then navigate to the file(s) to upload:

![Upload](https://i.imgur.com/ByNjcsN.png)

**Comment by P-Star7** [comment]
Thank you, the level file is now in the first post.
