### ISSUE TITLE
(Bug) Mario and Luigi asymmetrical swimming up animations

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#116]
Mario and Luigi's animations are asymmetrical when they are swimming up. This applies to all 7 forms for both players. I think it should be changed to how it appears in the right direction, without moving back and forth.

[marioanimationexamples.zip](https://github.com/Wohlstand/TheXTech/files/6549328/marioanimationexamples.zip)

**Comment by Wohlstand** [comment]
The "Preview" in the animation editor doesn't apply aligns yet, and therefore result is so messy. Try to play these animations in the main animator which plays these animations with all alignments applied.

**Comment by ds-sloth** [comment]
This issue doesn't exist in-game and never did. It also doesn't exist in the vanilla game. It's possible there was some issue with the Moondust animator at the time the issue was filed.

**Comment by Wohlstand** [comment]
This issue should be posted here: https://github.com/WohlSoft/Moondust-Project, as it's a problem of Moondust Calibrator, not TheXTech.

**Comment by Wohlstand** [comment]
> This issue doesn't exist in-game and never did. It also doesn't exist in the vanilla game. (Edit: I tested and confirmed both of these.) It's possible there was some issue with the Moondust animator at the time the issue was filed.

I already explained that in the Moondust Calibrator, the preview at the animation editor doesn't apply any aligns and just simply draw frames as-is, when normal animator does, and all runtime games do.
