### ISSUE TITLE
"--verbose" Option For Logging?

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#12]
When running, TheXTech keeps a log file.

I noticed when testing some things out with `music.ini` and `sounds.ini` it resports some quite useful information.

Being able to (optionally) see these from the terminal instead of having to `tail -f` the log after figuring out which one it is would be pretty great.

**Comment by Wohlstand** [comment]
Currently, a debug build (built with `CMAKE_BUILD_TYPE=Debug` option) only prints logs into stdout together with a file. Good idea for release builds I see... That should be quick!

**Comment by Wohlstand** [comment]
Made!

**Comment by ChristianSilvermoon** [comment]
This is gonna sound silly, but... how do I build non-debug build? XD
Do I just switch `CMAKE_BUILD_TYPE=` to something else? If so what to?

**Comment by Wohlstand** [comment]
For production, I usually building `CMAKE_BUILD_TYPE=MinSizeRel` to make a compact build.

**Comment by Wohlstand** [comment]
the only `CMAKE_BUILD_TYPE=Debug` will enable persistent logging and the debug assembly itself.

**Comment by ChristianSilvermoon** [comment]
I was able to compile ccd091446d44747f795a2de83243926217016fbe and I can confirm that the `--verbose` option well as `-e` works (though `-v` is actually a little more traditional shorthand for verbose :P).

However it still creates a log file on the disk when the option is used.
When using a verbose output, the log is probably being viewed as it happens and one could manually redirect output to a file :P

**Comment by Wohlstand** [comment]
```
-v
```
it's busy by "version"

**Comment by Wohlstand** [comment]
Closing as you had to confirm it works:fox_face:

**Comment by Wohlstand** [comment]
> However it still creates a log file on the disk when the option is used.

The log on the disk is always creating, yeah. Anyway, I bet there are some sets of daemon examples which printing both disk and the own log file...

**Comment by ChristianSilvermoon** [comment]
> ```
> -v
> ```
> 
> it's busy by "version"

Ah! Makes sense, actually but the shorthand isn't noted in `--help` for it.

Thanks, Wohlstand ^^
