### ISSUE TITLE
Bug: `--verbose` is non-functional when compiled with `-DENABLE_LOGGING=0`

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#124]
**Describe the bug**
When the `--verbose` option is used, the game does not output anything to stdout or stderr when `-DENABLE_LOGGING=0` is used at compile time. This renders `--verbose` useless. 

I often use `-DENABLE_LOGGING=0` to prevent writes to storage that I don't want/need during normal play, but this shouldn't prevent `--verbose` from being used, as the verbose output can be an invaluable resource for troubleshooting problems.

Stumbled across this by accident :P

**Example Case**
*N/a*

**Recording**
*N/a*

**Vanilla Recording**
*N/a*

**Additional context**
*N/a*

**Comment by Wohlstand** [comment]
Usually the "Disable logging" is mainly targeted to disable the logging into files at all, but yeah, I should allow the print logging when the `--verbose` has been requested.

**Comment by Wohlstand** [comment]
Oh, forgot to note that I fixed this bug some weeks ago, could you test it?

**Comment by Wohlstand** [comment]
I had to rework the logger where I allowed verbose log even the log into files got removed by the CMake flag

**Comment by ChristianSilvermoon** [comment]
Test off Master @ commit 9a16671

Seems to work ^^

**Comment by Wohlstand** [comment]
So, closing this now :fox_face:
