### ISSUE TITLE
Game timer stops when beating "level27.lvlx" using speedrun mode 2 (The Invasion 2)

### ISSUE THREAD

**Issue by simox-23** [Wohlstand/TheXTech#130]
I was trying to speedrun The Invasion 2 using Speedrun mode 2, and I noticed that when I get the orb after killing Larry to exit "The Invasion" (level27.lvlx), the IGT full game timer stops.
The run was made on a completely empty save file, no restarts or quits were made.

I'm running TheXTech v1.3.5.1.Win64 on Windows 10 64-bit

https://user-images.githubusercontent.com/80751487/120898381-f36f0f00-c62a-11eb-8e65-c7e3ddc1ce39.mp4

**Comment by Wohlstand** [comment]
Huh? The only reason to not count the full game timer (bottom timer) is that the game has the "Game beaten" flag is set (usually after defeating the final boss and getting the credits page). The level play timer (at top) should stop when you touching any item that leads to the level exit. I'll check some, was that "game has beaten" flag got set by mistake anywhere...

**Comment by simox-23** [comment]
Thanks for the reply! I'll wait for future updates then :)

**Comment by Wohlstand** [comment]
As at the `master` branch the works got started, I'll release the hotfix on top of the `stable-1.3.5.x` branch

**Comment by Wohlstand** [comment]
Okay, the reason for the bug is the most LOL OF UNIVERSE!

This is the code that handles the "Boss Dead" event to trigger the episode timer to stop:
![Снимок экрана от 2021-06-05 20-45-41](https://user-images.githubusercontent.com/6751442/120900720-14415f80-c63f-11eb-82f7-83a61291d502.png)

And this is the "Boss Dead" event at the level you have been mentioned:
![Снимок экрана от 2021-06-05 20-45-56](https://user-images.githubusercontent.com/6751442/120900752-3804a580-c63f-11eb-8365-ed71416148e1.png)

I don't remind who originally suggested to me add this event hook, however, this hook makes the direct trouble to play "The Invasion 2" that has the not final level with such a hook. :grin:

**Comment by Wohlstand** [comment]
Until the true solution will be developed, try to edit the level and rename the "Boss Dead" event into anything. Don't worry, Moondust Editor (former PGE Editor) can do that safely (it automatically renames all references to renamed events): double-click the event in a list, and type the new name for it.

**Comment by Wohlstand** [comment]
Also, check all other levels in the episode for the case they may have this false positive too. I do see the `dungeon2.lvlx` also have mention of this. All other levels are fine.

**Comment by simox-23** [comment]
Thank you so much for the explanation, that was very helpful! :)

**Comment by Wohlstand** [comment]
Okay, just now I made the update that should resolve your problem.

I did next:
- I disabled the "Boss Dead" hook by default
- I added the next settings into `compat.ini` to allow episode makers to specify which event should be used to hook the speed-run timer stop:
```ini
[speedrun]
stop-timer-by-event = true    ; true to enable the hook, false to disable
stop-timer-event-name = "Heck yeah, episode done!"   ; The name of the event that should hook the end of the episode. The "Boss Dead" will be default name for this hook
```

A tip: to avoid the collision against other levels, you may put these settings of `compat.ini` at the level's data directory, then, this hook will work for only that level. I.e. another level with "Boss Dead" hook will be safe, the level with the final boss and "Boss Dead" hook will work.

**Comment by Wohlstand** [comment]
@simox-23, please download this binary:
https://builds.wohlsoft.ru/win32/thextech-bin-win64-.7z
and unpack it over your existing copy of the game and try the game run again. Tell me if it works or not.

**Comment by 0lhi** [comment]
Instead of "stop-timer-by-event", you may consider to this:

```ini
[speedrun]
stop-timer-by = event / leave / enter    ; leave is quitting a specific level, enter is starting one
stop-timer-at = "Boss Dead" / finalboss.lvl / credits.lvl
```

This would give some flexibility, and more conditions could be added in the future.

**Comment by simox-23** [comment]
Hi, i finished both **level27.lvlx** and **dungeon2.lvlx** with the game timer running, both were completely fine. I also tried to fast-restart before playing them to check if everything was ok. **Dungeon1.lvlx** and **Dungeon3.lvlx** were already fine and **Dungeon4.lvlx** worked too. Thanks a lot for this fix.

**Comment by Wohlstand** [comment]
So, thanks for the confirmation this works now :fox_face:
A bit later I'll apply suggested changes into the config that will become final in the 1.3.5.2 release.

**Comment by Wohlstand** [comment]
Just now I made an update, so, the next will be at compat.ini:
```ini
[speedrun]
stop-timer-by = none / event / leave / enter
stop-timer-at = "Event Name" / "File Name Without Extension in UTF8"
```
feel free to test the result of the `stable-1.3.5.x` branch and confirm the work

**Comment by 0lhi** [comment]
Enter works:

![Scr_2021-06-12_19-16-29](https://user-images.githubusercontent.com/74732674/121784326-b5866380-cbb3-11eb-8c3f-a3ac91c1a4be.gif)

Leave does not:

![Scr_2021-06-12_19-18-41](https://user-images.githubusercontent.com/74732674/121784327-b6b79080-cbb3-11eb-9c3e-baf634462125.gif)
![Scr_2021-06-12_19-22-52](https://user-images.githubusercontent.com/74732674/121784329-b8815400-cbb3-11eb-917d-5d45d76d3386.gif)

This brings my attention to something: 

Leave should work for leaving the level through any means, and only stop the timer once the next level is reached.

Exit should be another option that stops the timer at any exit that also stops the level timer.

**Comment by Wohlstand** [comment]
I made some fixes, now that should work fine, @0lhi , gonna push all fixes...

**Comment by 0lhi** [comment]
Did some tests, here are the results: https://imgur.com/a/xgXuj4Z

**Comment by Wohlstand** [comment]
Kurwa... But ok, I know where to put the trigger now, thanks 🦊

**Comment by Wohlstand** [comment]
Fixed!

**Comment by 0lhi** [comment]
`leave` now gets triggered by taking any exit that ends the level timer, including fake exits that cause death, but no pipe or door exits. That's what `exit` should do, so I suggest to rename it.

Then make a `leave` trigger that gets enabled on the following condition:

_The player leaves the level through any means that do not involve death. Timer stops at the first frame of the next level/map._

_This includes pipe exits, door exits, or any normal exits, but no fake exits that cause death like in "A Short Level"._

**Comment by Wohlstand** [comment]
Then I'll revert that code, but I'll leave the "dead" place being without the trigger. So, the timer will be triggered to stop in the ONLY condition when the level got really left for non-death reasons. If you need to stop the timer by existing item taking, then just use an event way.

**Comment by 0lhi** [comment]
`leave` now does what it's supposed to!

> If you need to stop the timer by existing item taking, then just use an event way.

What would the event name be for taking an exit?

**Comment by Wohlstand** [comment]
> What would the event name be for taking an exit?

Manually defined as `event` type with the exact name in the `-at` field.

> EDIT: Also, is there an event for deaths?

Do you mean the way to finish the horror episodes where the main hero must die at the final?

**Comment by Wohlstand** [comment]
Anyway, the main topic of this issue has been solved, any future improvement for the speedrun configure at the `compat.ini` like custom ways of the timer trigger, etc. The discussion could be made.
