### ISSUE TITLE
Feature Request: Ability to Bind Multiple Keys To One Action

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#135]
There are some buttons my controller with no functionality that would be neat to give functionality to :P

**Comment by 0lhi** [comment]
Hah, issue #38 was closed just a few days ago :D

I'd like to see it as well, but figured there wouldn't be much demand for it after the controller update, so I suggested to give it the "won't fix" label with the option to change that if people wish for it. It happened faster than I thought ^-^>

Anyway, before said Update, I wanted to be able to play TheXTech using both, D-Pad and Analog Stick, and set up two workarounds that may be useful for trying multiple keybinds: [Xboxdrv](https://wohlsoft.ru/pgewiki/Xboxdrv) & [Antimicro](https://wohlsoft.ru/pgewiki/Antimicro).

Antimicro is the safer approach, but about 1 in 10 frames or there is input delay.

**Comment by ChristianSilvermoon** [comment]
I love Antimicro myself, but a native option would be great for the lonely buttons on my controller XD

I think it'd be better to bind actions to a list of buttons rather than buttons to a list of actions, personally

**Comment by ds-sloth** [comment]
This feature is included in the big `wip-abstract-controls` update that creates a shared internal programming interface for all controller types (and should make it much easier to add/remove support for controller types, eg homebrew console controls, in a modular way). If you want to consult the update, please check out that branch. Note that it does not currently include joystick or controller support, but it has keyboard and touchscreen, and I have been working on the joystick support for some weeks (haven't had that much daily time for the project).

Will update the issue when that update is ready for testing.

**Comment by 0lhi** [comment]
Done with #245
