### ISSUE TITLE
Feature Request: Optional Background Input

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#136]
The ability to enable the game to respond to Input (preferably gamepad only) when it is not in focus.

This is *especially* useful for multi-monitor configurations and multitasking

For example, the player could have a chat client focused to reply to messages quickly while playing.

**Comment by Wohlstand** [comment]
First off I need to check does SDL2 allows enabling that, that should be a small update. :thinking:

**Comment by Wohlstand** [comment]
Oh, I found just now:
> https://wiki.libsdl.org/SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS

**Comment by Wohlstand** [comment]
Gonna try that... I'll add the command-line flag for that

**Comment by ChristianSilvermoon** [comment]
> Gonna try that... I'll add the command-line flag for that

Could it also be a setting possible to set in Options?

**Comment by Wohlstand** [comment]
> Could it also be a setting possible to set in Options?

Yes, at [video] section, ~~BUT, it requires the restart of the engine~~ no, I'm blind:

> This hint may be set at any time.

So, this could be togglable in options easily, I'll try some.

**Comment by 0lhi** [comment]
> So, this could be togglable in options easily, I'll try some.

Would it also be possible for the --never-pause flag, and the Purple Yoshi Ground Pound?

**Comment by Wohlstand** [comment]
Yes, I do plan that in the whole options menu upgrade.

**Comment by P-Star7** [comment]
Please defaultly off.

**Comment by Wohlstand** [comment]
Don't worry, that is already 🦊👍

BTW, forgot to tell that this thing is done, and you can try test it in action, if it works, confirm, I'll close. The toggle for the menu I'll do in another task.

**Comment by 0lhi** [comment]
Works 👍

https://user-images.githubusercontent.com/74732674/121759147-a6a4a000-cb24-11eb-9b04-000ed90c8559.mp4
