### ISSUE TITLE
Idea: Episode Title & Copy/Erase Options For Saves on Save Select Screen

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#14]
I always found it a little frustrating to have to manually copy/delete saves with an external program (File Manager, etc.) x3

This would be a *very* nice quality of life addition in my opinion

Example
```
EPISODE NAME

SLOT 1... 30  ★x1
SLOT 2... EMPTY
SLOT 3... EMPTY
COPY
ERASE
```

**Comment by Wohlstand** [comment]
I have a plan to make that, thanks for making a note on that :fox_face:

**Comment by ChristianSilvermoon** [comment]
Awesome ^^

**Comment by Wohlstand** [comment]
The first step: showing the episode title at the menu
![Scr_2021-04-24_11-42-10](https://user-images.githubusercontent.com/6751442/115953097-30a39580-a4f2-11eb-8d00-7b93f3f8dd6d.gif)

**Comment by Wohlstand** [comment]
Made just now!
![Scr_2021-04-26_00-12-20](https://user-images.githubusercontent.com/6751442/116009793-27b2e100-a624-11eb-9d7d-55a377680c5a.gif)

**Comment by Wohlstand** [comment]
Sent the commit just now

**Comment by ChristianSilvermoon** [comment]
Built: cf77a9f

Can confirm, works entirely as expected on
• x86_64 Linux Mint
• armv71l RetroPie
• aarch64 Mobian

Built with:
```bash
# Linux Mint (x86_64)
cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizRel -DENABLE_LOGGING=0 ..

# Raspbian/RetroPie (armv7l - Raspberry Pi 4 Model B Rev 1.4 - Piboy DMG)
cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizRel -DENABLE_LOGGING=0 -DUSE_SYSTEM_LIBS=1 ..

# Mobian (aarch64 - Pine64 PinePhone 1.2 )
cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizRel -DENABLE_LOGGING=0 -DUSE_SYSTEM_LIBS=1 ..
```

Though I've noticed it allows you to "Copy" an empty file. The target file remains unchanged in this instance.

**Comment by Wohlstand** [comment]
> Though I've noticed it allows you to "Copy" an empty file. The target file remains unchanged in this instance.

Good notice, I should reject an ability to select an empty file... You right!

**Comment by Wohlstand** [comment]
btw, about ARM32 (armv71l) the note that Bowser III'th is broken, however, I got fixed that recently by tuning the floating-point comparison calls that being used to verify the AI state of Bowser III'rd,

**Comment by Wohlstand** [comment]
Sent a fix to reject an attempt to copy the empty file

**Comment by ChristianSilvermoon** [comment]
Tested out f3f58f8 and it works pretty well (only tested on desktop, this time tho)

**Comment by Wohlstand** [comment]
Also, this feature is a life-important for Emscripten, because you literally has no direct access to the gamesaves store at all, because on how WebAssembly side cache storage works

**Comment by ChristianSilvermoon** [comment]
> Also, this feature is a life-important for Emscripten, because you literally has no direct access to the gamesaves store at all, because on how WebAssembly side cache storage works

Oh wow, that's a good point, I never even though about that, but yeah. Gosh, web assembly's an interesting tech to have.

**Comment by Wohlstand** [comment]
> Gosh, web assembly's an interesting tech to have.

You may see some here: 
* https://wohlsoft.ru/TheXTech/smbx-on-web/
* https://wohlsoft.ru/TheXTech/aod-on-web/

btw, gotta update these builds here...

**Comment by Wohlstand** [comment]
They got fixed, but now they don't show the "click to start" title... that odd

**Comment by Wohlstand** [comment]
Anyway, the issue itself is solved 🦊
