### ISSUE TITLE
[Bug] TheXTech loads custom level graphics into the map

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#141]
**Describe the issue**

After quitting a level with custom character sprites, the Character display on the Map does not return to the default sprite.

**Example Case**

First noticed in CrimsonTRB's Stream at the [STTB2 Credits](https://clips.twitch.tv/ResoluteSweetHamOhMyDog-2KTEuEp_DgNiK4Uo) (Mario Sprites are invisible). Easy to reproduce by pasting any custom sprites to The Invasion 2's level1.

**Recording**

![Scr_2021-06-17_18-12-00](https://user-images.githubusercontent.com/74732674/122435645-76338a80-cf98-11eb-8f50-80c4d8fa6f85.gif)

**Vanilla Recording**

Does not occur in Vanilla.

https://user-images.githubusercontent.com/74732674/122437224-cced9400-cf99-11eb-9645-40f3f36ddfce.mp4

**Additional context**

\-

**Comment by Wohlstand** [comment]
I guess, that might happen because level custom resources wasn't unloaded after the level quit, a little miss up

**Comment by 0lhi** [comment]
The unload is fixed, buuuut...

![Scr_2021-06-22_12-09-13](https://user-images.githubusercontent.com/74732674/122906968-f9672e80-d352-11eb-9051-59b5e633339f.gif)

**Comment by Wohlstand** [comment]
Please try 1.3.5.x branch, the master branch has some WIP parts, let's report them to @ds-sloth

**Comment by 0lhi** [comment]
Stable branch is fine. 
![Scr_2021-06-22_12-43-48](https://user-images.githubusercontent.com/74732674/122911419-90ce8080-d357-11eb-9ccd-2190f9a30c5d.gif)

**Comment by Wohlstand** [comment]
So, I do close this, the but with a menu offset is a different thing, so, it's another issue
