### ISSUE TITLE
(Feature Request) Option to put the episode's credits in gameinfo.ini

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#142]
Since other episode settings are stored in gameinfo.ini, I think this should be done too so that other GUIs can be used to edit the credits text. SMBX should check if there are credits in gameinfo.ini, and if not, falls back on the map credits.

**Comment by ds-sloth** [comment]
The role of `gameinfo.ini` has changed, and this is clearly not appropriate *for episodes*. We may want to consider adding *asset pack* credits to `gameinfo.ini`, but that's a different issue.

**Comment by Wohlstand** [comment]
Also, WLDX is able to handle more than 5 lines of credits. So, episode credits CAN be longer.
