### ISSUE TITLE
Menu offset issue

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#146]
The unload is fixed, buuuut...

![Scr_2021-06-22_12-09-13](https://user-images.githubusercontent.com/74732674/122906968-f9672e80-d352-11eb-9051-59b5e633339f.gif)

_Originally posted by @0lhi in https://github.com/Wohlstand/TheXTech/issues/141#issuecomment-865853357_

**Comment by ds-sloth** [comment]
Thanks for the report @0lhi!

I'm familiar with this code and happy to hunt this down.

Was this in the primary branch ("master") or in my wip branch ("wip-multires")?

**Comment by Wohlstand** [comment]
> Was this in the primary branch ("master") or in my wip branch ("wip-multires")?

I guess, `master` 0lhi always tested on the `master` branch. :thinking:

**Comment by 0lhi** [comment]
Yup, master branch. The [auto-builds](https://github.com/Wohlstand/TheXTech/wiki/Fresh-devel-builds), to be precise.

**Comment by 0lhi** [comment]
While testing a separate thing that I'm about to open an issue for, I found this:

![PauseMenuVanilla](https://user-images.githubusercontent.com/74732674/123090060-fee27880-d427-11eb-9399-457b263cdc47.png)
![SpeakBoxVanilla](https://user-images.githubusercontent.com/74732674/123090075-01dd6900-d428-11eb-9fa4-2611b7f8e93b.png)

This happened after using the Multiplayer once, a restart makes them appear normally.

**Comment by ds-sloth** [comment]
Thanks for letting me know!

Don't open a new issue, I know this code well and the menu and messagebox use the same underlying offsets for multiplayer.

I actually am very confident that this case will work fine in the `wip-multires` branch already -- you can try it out -- but we can try to get the main branch fixed as well. I'll take a look later today.

**Comment by 0lhi** [comment]
I can also confirm that it also happens in the stable 1.3.5.x Build, but I don't know yet what chain of events causes this to happen.

![PauseMenuStable](https://user-images.githubusercontent.com/74732674/123093742-51259880-d42c-11eb-99cf-ce88db9f463d.png)

The 1player 2player Cheats may be related.

**Comment by ds-sloth** [comment]
It doesn't surprise me that the 1P/2P cheat is involved.

All of this seems to mean that for some reason `DScreenType` is not getting properly reset when it should be.

The trivial way to fix this would probably be to add an `else { DScreenType = 0; }` clause after the `if(ScreenType == 5)` clause ending on line 191 of `graphics/gfx_update.cpp`. We could also figure out why `DScreenType` is not getting reset.

A third option would be to add an `&& numScreens == 2` check to all of the places where the menu / messagebox offset is set. But that would be hackish.

Finally, I can confirm that this issue does not occur in the `wip-multires` branch because that branch draws global interface elements outside of the `vScreen` scope.

**Comment by 0lhi** [comment]
> Don't open a new issue, I know this code well and the menu and messagebox use the same underlying offsets for multiplayer.

I see, Then, I guess I'll post here the other thing I noticed:

![Scr_2021-06-23_13-24-10](https://user-images.githubusercontent.com/74732674/123094410-2556e280-d42d-11eb-9159-acf576ffa9d4.png)

![Scr_2021-06-23_14-16-48](https://user-images.githubusercontent.com/74732674/123094910-b75eeb00-d42d-11eb-996c-0ad1b813497e.png)


The text isn't displayed properly in multiplayer splitscreen. I could reproduce in master and 1.3.5.x, but not in Vanilla.

**Comment by ds-sloth** [comment]
Ahh... in that case we really should just backport my change to take this draw code outside of the `vScreen` scope.

**Comment by 0lhi** [comment]
Noticed this in the most recent Master Build:

![Scr_2021-07-06_11-11-08](https://user-images.githubusercontent.com/74732674/124574809-1f102f80-de4b-11eb-8087-36ee9f05bf0a.png)

Found while testing #152

**Comment by ds-sloth** [comment]
Yes, I believe it is fixed now that I have merged the `wip-multires` branch! Please let me know if it is not and we can re-open the issue.

**Comment by 0lhi** [comment]
The Pause Items, at least inside levels, still lean to the left.

![Scr_2021-07-06_23-24-33](https://user-images.githubusercontent.com/74732674/124668569-5b767680-deb1-11eb-8fbc-d5bd50473958.png)

On the Map and Hubworlds it's fine:

![Scr_2021-07-06_23-26-10](https://user-images.githubusercontent.com/74732674/124668746-94aee680-deb1-11eb-9e9e-cf0289e4bf20.png)
![Scr_2021-07-06_23-26-16](https://user-images.githubusercontent.com/74732674/124668747-95e01380-deb1-11eb-8a56-3b5fedcac69a.png)

**Comment by ds-sloth** [comment]
I didn't realize that was a bug! Fixed now :) b73b1dc17b4fa30d3cc3165a8610856ef140b9d9

**Comment by 0lhi** [comment]
Tested on The Invasion 2 with GBA resolution, with SMBX resolution, with HD resolution, and on Mode 2. Works 👍

![Scr_2021-07-08_18-21-56](https://user-images.githubusercontent.com/74732674/124957603-8b408e00-e019-11eb-850b-c4b6c21f44f9.png)

**Comment by ds-sloth** [comment]
Thanks for the test @0lhi! Closing issue now.
