### ISSUE TITLE
Add an option of short vibration when pressing touch buttons

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#147]
That was discussed with the SadDemon at YouTube comments. There is an idea to make an option to enable the short vibration when pressing buttons on a touch screen, making these buttons being more sensitive.

Note: to get the vibration use the SDL_Haptic API can be used, the vibration device should been found.

**Comment by ds-sloth** [comment]
Completed by Wohlstand a long time ago.
