### ISSUE TITLE
Speedrun Timer stops when meeting Birdo in Mushroom Pass

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#148]
**Describe the issue**

When the screen moves towards the Boss, the timer stops. First discovered by @simox-23:

>I had to use SMBX2 due to the timer behavior being different in TheXTech.
>Specifically during the transition before Birdo, in SMBX2 the timer doesn't pause, while it pauses in TheXTech for some reason.
>
>https://www.youtube.com/watch?v=RDvRoQ4frlM

**Example Case**

mushroom_pass.lvl from *The Princess Cliche*.

**Recording**

![Scr_2021-06-27_23-12-52](https://user-images.githubusercontent.com/74732674/123559771-67ba4f80-d79e-11eb-9b88-4bbd68ecef89.gif)

**SMBX2 Recording**

![2021-06-27_23_16_36](https://user-images.githubusercontent.com/74732674/123559779-7acd1f80-d79e-11eb-81be-ac8b01dc32fa.gif)

**Additional context**

\-

**Comment by Wohlstand** [comment]
That because the transition goes in a separated loop, therefore, to not stop it, I need to call the timer tick at that loop

**Comment by Wohlstand** [comment]
Just now I made a quick fix, please test this

**Comment by 0lhi** [comment]
Fixed 👍

![Scr_2021-06-28_11-36-32](https://user-images.githubusercontent.com/74732674/123615836-f6ae8280-d805-11eb-9b9e-89ec19bf437f.gif)
![Scr_2021-06-28_11-41-30](https://user-images.githubusercontent.com/74732674/123615925-0c23ac80-d806-11eb-88a5-253ba11a2680.gif)

**Comment by Wohlstand** [comment]
:fox_face: :+1:
