### ISSUE TITLE
Feature Request: Add show-input & speedrun-mode options to thextech.ini

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#149]
```ini
[video]
show-input = 1

[gameplay]
speedrun-mode = 0 / 1 / 2 / 3
speedrun-semitransparent = true / false
```

The speedrun-mode setting in particular would be useful to make it easier to access for users who are unfamiliar with the Command Line.

Show-input would display the meta-controller(s) outside of speedruns.

EDIT: Option for translucent timer.

**Comment by Wohlstand** [comment]
The gamepad displaying was been added a while ago, the speed-run mode wasn't yet.

**Comment by Wohlstand** [comment]
Just now I added the:
```ini
[speedrun]
mode = 0 / 1 / 2 / 3
semi-transparent-timer = false / true
```
into settings/thextech.ini, so, feel free to test the thing

**Comment by 0lhi** [comment]
Console overrides settings, Speedrun setting overrides Controller setting.

Works as intended, on both, Master and Devel =)
