### ISSUE TITLE
Checkpoint doesn't work in Super RMN World's "Guernica"

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#152]
**Describe the issue**

Player spawns at the beginning of the level when reentering.

This happens on the Master Branch and the Stable-1.3.5.x Branch, even with enable-multipoints set to false.

On Vanilla it works as intended.

**Example Case**

*Guernica.lvl* from [Super RMN World](https://rpgmaker.net/games/4676/)

**Recording**

https://www.twitch.tv/sl4cer/clip/YawningNurturingAlpacaKappaClaus-FsbQwHqBoBlWEDPF

**Vanilla Recording**

https://user-images.githubusercontent.com/74732674/124522107-51417300-ddf2-11eb-8a2c-32e212e5d51b.mp4

**Additional context**

Bug also does occur on *Koopa Rave.lvl*.

It does not occur on TheXTech 1.3.4.

It does not occur on the Master Branch when testing the Level on Master through the PGE Editor.

**Comment by Wohlstand** [comment]
Fixed just now! :fox_face: :+1: 

I accidentally made this bug when I fixed another bug when custom player sprites got loaded at the world map from the last played level.

This bug appears at 1.3.5.2 only, but it doesn't happen at the 1.3.5.1 release and older. Good that this bug is a dev bug only.

**Comment by 0lhi** [comment]
Works! Tested on both, Master and Stable 👍

![Scr_2021-07-06_11-06-41](https://user-images.githubusercontent.com/74732674/124575210-7d3d1280-de4b-11eb-953c-b8023cf3342f.gif)

**Comment by Wohlstand** [comment]
So, the bug has been fixed :fox_face:
