### ISSUE TITLE
 Multires breaks display-controllers option.

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#153]
**Describe the issue**

Since the merge with the wip-multires branch, the meta-controller doesn't show up in levels anymore:

![2Screen](https://user-images.githubusercontent.com/74732674/124645834-34f61280-de94-11eb-8fb1-babbf079d1ca.png)
![SuperEasyRoad](https://user-images.githubusercontent.com/74732674/124645854-3aebf380-de94-11eb-932f-a0fce36d2cdd.png)

It doesn't appear in the Speedrun-Mode either:

![SpeedRun](https://user-images.githubusercontent.com/74732674/124646168-9a4a0380-de94-11eb-9f6d-fd0c8d7b0a31.png)

But it's still visible on the Map:

![Scr_2021-07-06_19-56-46](https://user-images.githubusercontent.com/74732674/124645991-6242c080-de94-11eb-8fe3-6a8e20d58ae1.gif)

EDIT: In 2 Player Mode, the Controllers appear:

![Scr_2021-07-06_20-05-08](https://user-images.githubusercontent.com/74732674/124646963-9c609200-de95-11eb-86e8-4ffbbda73e57.gif)

EDIT 2: Not in splitscreen though.

![Scr_2021-07-06_20-13-01](https://user-images.githubusercontent.com/74732674/124647755-aa62e280-de96-11eb-84c8-70587ef145cb.gif)

**Comment by ds-sloth** [comment]
Thanks for the heads up @0lhi. I will take a look when I am free tonight.

**Comment by ds-sloth** [comment]
Should be fixed! Please confirm. :)

![Scr_2021-07-06_16-44-25](https://user-images.githubusercontent.com/72112344/124664697-d3c14580-de79-11eb-9acf-6ba638373ba9.gif)
![Scr_2021-07-06_16-44-34](https://user-images.githubusercontent.com/72112344/124664713-d6239f80-de79-11eb-846c-fb6fc16b0572.gif)
![Scr_2021-07-06_16-44-53](https://user-images.githubusercontent.com/72112344/124664714-d754cc80-de79-11eb-94f5-bc9d1287fdbf.gif)

**Comment by 0lhi** [comment]
Confirming 🙂👍

[2 Player](https://user-images.githubusercontent.com/74732674/124667331-8cee4280-deaf-11eb-9a49-a63e7fac0d8c.gif) | [Mode 1](https://user-images.githubusercontent.com/74732674/124667352-937cba00-deaf-11eb-82ce-ac2f34f48df8.png) | [Mode 2](https://user-images.githubusercontent.com/74732674/124667407-a7c0b700-deaf-11eb-8959-a438da8374a0.png)

Also tested Fungi Village, and can confirm that on small screens, the controller moves towards the center. This is a bit off-putting. Can it me made so that it stays at it's closest border?

![Scr_2021-07-06_23-20-59](https://user-images.githubusercontent.com/74732674/124668227-d5f2c680-deb0-11eb-98f0-74f3a0b01968.png)

**Comment by ds-sloth** [comment]
That would be non-trivial. What I did was to make the control graphics belong to the corresponding player's vScreens (which is logical), but then when the vScreen shrinks, the controls would stay within the vScreen. Would it be better if the controller graphic was always restricted to the center 800 pixels of its vScreen so that it would stay consistent?

We can definitely make the control graphics behave as you described (where the control graphics would *follow* the vScreens but be drawn outside of them at times), but this would require a little more hacking and be harder to maintain. If that is strongly preferred, I'm happy to code it up.

**Comment by ds-sloth** [comment]
So I see three options: (1) keep it as shown in @0lhi's last comment, (2) allow controls graphics to render offscreen at level of vScreen, and (3) make controls graphics consistently render at center-left of vScreen.

These are mockups of (2) and (3):

<img src="https://user-images.githubusercontent.com/72112344/124678740-2b1ee000-de91-11eb-82d5-28a8d46e3fb1.png" width="400" height="240" />
<img src="https://user-images.githubusercontent.com/72112344/124678781-3d008300-de91-11eb-9f20-30cd26b8d007.png" width="400" height="240" />

I'd like to hear everyone's thoughts on this if possible.

**Comment by 0lhi** [comment]
Difficult. Maintainability is important. And the current situation overall isn't bad.

Would it be possible that, in 1P Mode, the controller gets always drawn at the bottom left Part of the Window (like the FPS Counter is at the Top Left), but have it be locked inside the vScreen during 2P Mode?

There are Talks at #46 about Splitscreens having fixed positions, and even be able to be separated by windows. I think those features will be used once implemented, and they may allow for less hackish positioning options.

**Comment by ds-sloth** [comment]
That sounds very doable. How about in 1P, it's drawn at the bottom left of the window, and in 2P, it is drawn like (3) in my last message?

**Comment by 0lhi** [comment]
Yeah, I think that's a workable solution.

**Comment by ds-sloth** [comment]
So, like this in 2P?

![Scr_2021-07-07_18-12-46](https://user-images.githubusercontent.com/72112344/124835344-2c164700-df4f-11eb-9a2a-1f56258af0b1.gif)

**Comment by 0lhi** [comment]
> Alternatively: we could make the second player's controls gravitate right in 2P even when the second player has their own screen.

I think this should be done when the "always split vertically" option is available. For dynamic splits, it's probably better to have it always stay within the 800x600 space.

**Comment by ds-sloth** [comment]
> For dynamic splits, it's probably better to have it always stay within the 800x600 space.

I was thinking it would stay in the central 800 pixel area, but be on the right side of that area during the vertical split instead of moving to the left as it does above.

**Comment by 0lhi** [comment]
Ah, I see. I don't think that should be done. In the horizontal split Player 1's controller is on the right, so, the change wouldn't create consistency. Most of the time you move to the right, so it's better to have the controller "behind" you instead "ahead" of you.

**Comment by ds-sloth** [comment]
In that case, I think we can consider this issue closed for now. If you disagree please let me know and I can reopen it.
