### ISSUE TITLE
Feature Request: Display a Level's Star Count on the World Map

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#156]
Doors and Warps to other Levels can display their Star Count. It would be nice to bring this feature to Worldmaps as well. (Particularly for Episodes that have no [Star Tracking Levels](https://i.postimg.cc/zGhZfBxL/2020-03-19-01-06-51.png)).

![StarCount1](https://user-images.githubusercontent.com/74732674/125937532-56f9aeec-6386-44ad-b41f-1070bd93dbe1.png)

Dragon Coins, too, once #122 is done.

![StarCount2](https://user-images.githubusercontent.com/74732674/125937591-44c91b4a-974a-4f99-8383-7f3f5d3dc403.png)

**Comment by Wohlstand** [comment]
Stars count on the world map seems a good thing, that's really easy to do, and so:
- Levels that has no stars, will show nothing
- Add WLDX-side flags:
-- map-wide: enable/disable/unset stars showing
-- level-point local: enable/disable/unset stars for this point only
- `compat.ini` will define the default value for unset values

**Comment by Wohlstand** [comment]
I guess, this thing should majorly simplify the episodes playthrough that has hidden stars on certain levels and it's hard to figure them, but these stars were required to complete the episode

**Comment by Wohlstand** [comment]
Okay, this task has been completed. Any other additional things will go as separate tasks.
