### ISSUE TITLE
Modified NPC-247 (Pokey) falls apart on TheXTech

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#160]
**Describe the issue**

A Pokey that is customized to resemble a stack of Goombas is falling apart on TheXTech regardless of compat settings, but remains stable on Vanilla and SMBX2.

```
npc-247.txt

playerblocktop=0
npcblocktop=1
grabtop=0
nofireball=0
noiceball=0
```

**Example Case**

Post a link to the level where the issue occurs:
*2-1 Deserted Walk.lvl* from [New Super Mario Bros DS. Remastered](https://www.supermariobrosx.org/forums/viewtopic.php?f=36&t=24123)

Download that runs on all branches:
[DesertedWalk.zip](https://github.com/Wohlstand/TheXTech/files/6840522/DesertedWalk.zip)

**TheXTech Result**

![Scr_2021-07-19_13-11-19](https://user-images.githubusercontent.com/74732674/126155354-e546bd20-de54-46a2-988a-510175a7167b.gif)

**Vanilla/SMBX2 Result**

![2021-07-19_13_10_46](https://user-images.githubusercontent.com/74732674/126155251-b5cf4768-57b6-4fe1-9eea-409047d46acb.gif)

**Comment by Wohlstand** [comment]
This is the case you should enable the pokey fix at compat.ini, playing at Mode 2 disables it.

**Comment by Wohlstand** [comment]
So, this will be an episode that requires you to play as Mode 1. All episodes targeted to TheXTech should be played with mode 1. Use Mode 2 to play vanilla SMBX with the SMBX2 compatibility or Mode 3 with the full set of SMBX 1.3's bugs.

**Comment by Wohlstand** [comment]
But wait, seems here is the weird confusion against the ground detection... :thinking:

**Comment by 0lhi** [comment]
> A Pokey that is customized to resemble a stack of Goombas is falling apart on TheXTech **regardless of compat settings**

This occurs, no matter if fix-pokey-collapse is set to true or false. Also tested on Mode 1 and 3.

**Comment by Wohlstand** [comment]
Okay, the quick fix is changing pokey's directino from LEFT into RIGHT :thinking:

**Comment by Wohlstand** [comment]
So, there is a question WHY this happens
https://user-images.githubusercontent.com/6751442/126157300-3f581f59-7e47-445f-b303-1d35c899d606.mp4

I'll try to research some after my workday

**Comment by Wohlstand** [comment]
So, the problem is that Pokey' segments do start in a different direction than needed, causing them to go on the land by corner

**Comment by Wohlstand** [comment]
![Снимок экрана от 2021-07-19 15-15-58](https://user-images.githubusercontent.com/6751442/126158368-c7af8808-0b84-4b31-9a65-6a4744ceded6.png)
![Снимок экрана от 2021-07-19 15-15-28](https://user-images.githubusercontent.com/6751442/126158372-1464b670-a499-453a-a3af-30378d420c78.png)
![Снимок экрана от 2021-07-19 15-15-03](https://user-images.githubusercontent.com/6751442/126158373-4df94c22-08d7-40a4-878d-527582746887.png)

**Comment by Wohlstand** [comment]
So, this is the question of the initial direction handling

![Снимок экрана от 2021-07-19 15-17-26](https://user-images.githubusercontent.com/6751442/126158543-e5a50f94-9634-4945-8813-c5e4f4c15382.png)
![Снимок экрана от 2021-07-19 15-17-12](https://user-images.githubusercontent.com/6751442/126158545-a4b1cde4-7cad-4823-bd74-a80e591894ed.png)

the same Pokey falls when no segments below, but goes on the cliff when something under appears

**Comment by ds-sloth** [comment]
Could this be another one of those pass-by-reference issues?

**Comment by Wohlstand** [comment]
> Could this be another one of those pass-by-reference issues?

Maybe, maybe... :thinking:  :thinking:  :thinking:  :thinking:

**Comment by Wohlstand** [comment]
The test case for this bug [Pokey startup.lvl.zip](https://github.com/Wohlstand/TheXTech/files/7274585/Pokey.startup.lvl.zip)

**Comment by Wohlstand** [comment]
@0lhi, we together with @ds-sloth found the true reason - I called graphics update before the first NPC update cycle, and that caused the big pain here. I had to implement the alternative call to preload some of lazy graphics without triggering any in-game logic at all.

**Comment by Wohlstand** [comment]
![Scr_2021-10-04_05-58-33](https://user-images.githubusercontent.com/6751442/135786788-da3224d7-48e1-480f-a544-75fc4dbdd3d5.gif)

**Comment by Wohlstand** [comment]
Also, @0lhi, please verify the speed-run timer for just in a case, didn't I broke it or not, else I'll add the initial tick triggering

**Comment by Wohlstand** [comment]
Okay, I had checked out the stuff, and this shoudn't hurt the speedrun timer at all

**Comment by 0lhi** [comment]
Looks good!

Vanilla:

https://user-images.githubusercontent.com/74732674/135868949-8c60dc49-4302-4970-8b64-613319505003.mp4

TheXTech:

https://imgur.com/a/GDOgtAD

**Comment by Wohlstand** [comment]
So, problem has been fixed and tested, Thanks for the test! @0lhi :fox_face: :+1:
