### ISSUE TITLE
Feature Request: Multiple Custom BGMs Per Section

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#161]
A long standing limitation as far as I know (which has prompted numerous sets of customs SMBX assets for episodes) is that only one custom track can exist per section, making it impossible to go from one custom track to another without replacing stock assets.

It would be really nice if said limitation were removed

**Comment by Wohlstand** [comment]
If you need to play multiple parallel tracks, that is impossible right now and needs me to complete this task at MixerX:
https://github.com/WohlSoft/SDL-Mixer-X/issues/2

**Comment by ChristianSilvermoon** [comment]
I mean specifically with the Custom Track setting for a section, events can change the track to any of the stock tracks or one selected custom track, but you can't select more than one custom track per section

**Comment by Wohlstand** [comment]
If you want to change the custom music by event, there is already solution as 38A unused fields at PGE-FL level structure, I should handle them and add into Moondust Editor to use them

**Comment by Alucard648** [comment]
One question: does SMBX2 have ability to to change the custom music by event?

**Comment by Wohlstand** [comment]
No, it doesn't, all music change manipulations were done by lua code.

**Comment by ds-sloth** [comment]
Has this already been done? I thought it had been.

**Comment by ds-sloth** [comment]
Please reopen this issue if it is not complete.

**Comment by ChristianSilvermoon** [comment]
@ds-sloth  
> Has this already been done? I thought it had been.

Uhh, well, I suppose individual levels can override stock music now can't they?

I guess that pretty much solves the need for selecting multiple tracks from an editor, unless there's some change I'm unfamiliar with; it's been a long time since I've played with editing levels

**Comment by ds-sloth** [comment]
It's supported in the Moondust Editor for events to set section music by a path, not only by a music index. And yes, it's also possible for a level to create a level-specific `music.ini`.
