### ISSUE TITLE
Change license into GPLv3

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#162]
As we (Me, @ds-sloth, and @KevinW1998) have been discussed together with Nomagno#8284 at the Discord server, I need to apply the GPLv3 license to all main project files (keep the MIT license at libraries and various generic shared modules).

> Nomagno#8284
After successfully verifying all current contributions made over the last year are (Surprisingly, hopefully I can change that once I make something worth including) only yours, and that indeed all code has been completely rewritten from the Redigit code thus eliminating all theoretical VERY MINOR restrictions, I'd like to politeky request a license switch to GPL or otherwise copyleft be considered, to avoid what I see as a curse that hunts all BSD licensed-based Mario fangame engines that makes them end up monetized by a third party closed source fork
TheXTech is probably now in a position where it'll be shined a relatively big spotlight, and without copyleft licensing being in place I'm worried any new features make it just ever that more susceptible to the collective malice seen previously in the game-cloning third parties that roam the internet

That means TheXTech is being used as the engine for the "Super Mario Bors. X" Mario fan game, should not be allowed to be used with closed-source proprietary projects. The MIT license is fine for the Moondust Engine runtime as it's directly targeted to develop brand-new games from the scratch, even its WIP.

- [x] Replace the main license file with GPLv3
- [x] Patch all main project headers to identify them as GPLv3-licensed
- ~~Apply ReadMe changes~~ Not so needed, it doesn't mention the license
- [x] Apply the license change at the Wiki

**Comment by Wohlstand** [comment]
Mainstream branches have been updated, the license file has been changed with GPLv3, and all main Moondust Wiki pages (except Chinese, German, and Spanish translations) have been updated to mention the license change since 1.3.5.2.

**Comment by LoveBodhi** [comment]
Chinese also updated

**Comment by M0REKZ** [comment]
A, I'm going to see that in spanish
