### ISSUE TITLE
Add an ability for stars being placed more times at the same section

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#164]
Since SMBX introduced the stars system, it keeps the painful limitation that restricts every single star being assigned to the section where it was been placed. So, if you put two stars in the same section, they both counted as one star. There is a way to break this limitation, and there is a little plan. However, the compatibility should be kept in a condition that some old levels do keep multiple stars at the same section and intended they all disappear once the star will be taken.

- [x] Utilize the Special Value that will set the mode of the star's algorithm between:
  - Count star by current section (legacy way, keep existing level files to set it always default)
  - Count star by the internal counter (use the same way as checkpoints works) (modern way, make it default at TheXTech SDK config pack when placing new stars at the Moondust Editor)
- [x] Allow SAVX and internal in-game stars database to track stars by section and by counter depending on the star tracking type that was set by a specific star (also, add the "mode" field at SAVX' taken star entry to identify which star was taken: by section or by counter)

Any ideas/suggestions/notices/criticism acceptable

**Comment by Wohlstand** [comment]
Little another idea on how to make the thing:
- Add to every star object the special value
- This value have the 0 by default. Meaning, work as usually: per section
- When you will set any non-zero value, this will become a sort of the "star ID"
- At the SAVX file, give the separated star-id value tha section number, OR, just give the negative value that will directly mean: negative is a star-id, positive is a section number.

So, if anyone wish to use many stars at the same section, that's will be possible via Moondust Editor at the special value (at TheXTech SDK config pack), otherwise, stars will keep with their old work and no compatibility will be harmed.

**Comment by Wohlstand** [comment]
Done by 1fd5f1dd2a917628f8d37fa6b11640e2eb796171, 9dd4b1520c83112a85befc17bfad44082bb1bd9d and d11edf8a720e13eba24585abc47e5275d25c976a.

Example level: [Multistars.lvlx.zip](https://github.com/Wohlstand/TheXTech/files/11580743/Multistars.lvlx.zip)

At this demo level, do next:
- Take any star
- Call pause menu and restart: you'll see how many stars remained on both sections.

**Stars in bubbles** has UID=0, they counted per section as vanilla SMBX. Other stars has their unique ID, and you can take them independently, they won't disappear together on restart, and every taken star will be counted.

**Comment by Wohlstand** [comment]
![Снимок экрана от 2023-05-27 05-00-52](https://github.com/Wohlstand/TheXTech/assets/6751442/7c106be6-994b-4fdd-9157-0c5af656a246)

**Comment by LoveBodhi** [comment]
Now takes a long time to load engine asset than past version, why?

**Comment by SkullGamer205** [comment]
Sheeeeeesh

**Comment by Wohlstand** [comment]
> Now takes a long time to load engine asset than past version, why?

Seems unrelated report for this topic... The change I done does not affects the performance at all.

**Comment by ds-sloth** [comment]
Just added full support at the in-game editor. Also fully tested the feature, and it works in nearly all cases, including various edge cases with buried item, item in egg, and item in bubble.

It doesn't seem to support level-end stars stored by the Item Thrower NPC. When thrown, those become legacy stars. Is that intentional? Since we are using the Variant field, it would be trivially easy to pass the Item Thrower's Variant on to its item.

**Comment by Wohlstand** [comment]
> It doesn't seem to support level-end stars stored by the Item Thrower NPC. When thrown, those become legacy stars. Is that intentional? Since we are using the Variant field, it would be trivially easy to pass the Item Thrower's Variant on to its item.

I just didn't care about them. But, sounds like it's possible to allow Item Throwers to put the proper star ID to spawned star objects.

**Comment by ds-sloth** [comment]
Just did this now. On my side, everything tests according to my expectations now.

**Comment by Wohlstand** [comment]
Fully completed!
