### ISSUE TITLE
Request: Don't Fullscreen On Maximize

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#18]
I've always found this behavior frustrating. I'd like to be able to maximize the window *without* entering Full Screen Mode.

Presently I have to resize the window manually.

The game should just maximize normally and only enter full screen if set in the menu or a key combo is pressed. IE: Ctrl+F, F11, or ALT+Enter

**Comment by Wohlstand** [comment]
I did this to replicate original SMBX' behaviour, however, thanks for a tip, maybe I'll make the setting in the config file to tune this?

**Comment by Wohlstand** [comment]
Done!
Please test the result!

**Comment by Wohlstand** [comment]
I had to add Ctrl+F as alias to Alt+Enter. Also I had to polish the logic to don't affect keyboard when pressing alt+enter that may confuse the work.

**Comment by Wohlstand** [comment]
F11 is busy by a gif recorder. On macOS it can't be used as it's reserved for a "show  desktop" built-in feature.

**Comment by ChristianSilvermoon** [comment]
Aaand it  works absolutely ***perfectly***!
Thank you so *very* much, Wholstand.

I know the goal was to replicate the original game and you've kind of already done that...
I'm really honored and grateful that you're doing any of this extra stuff really ^^

I've been trying to keep most of my feature suggestions to being more quality of life improvements than things like items, etc. for that reason.

I would've replied sooner, but I honestly didn't know you'd gotten back to me until just now, sorry x3

**Comment by Wohlstand** [comment]
Great that you had came back and replied me against result! :fox_face: 
Closing this as a complete thing!

**Comment by Wohlstand** [comment]
Yeah, while XTech Master doesn't intends to add new elements except of minor functionality, any general improvement suggestions are welcome! :fox_face:
