### ISSUE TITLE
The Stopwatch Prevents Objects From Spawning (Devel Branch)

### ISSUE THREAD

**Issue by DerpyBubblez** [Wohlstand/TheXTech#180]
**Describe the issue**
The stopwatch item, used to freeze time, causes objects to stop spawning while moving further into the level.

**Example Case**
Spring Ahead, Fall Back (Super Talking Time Bros 2)
[SA-FB.zip](https://github.com/Wohlstand/TheXTech/files/7117321/SA-FB.zip)

**Devel Recording**
https://cdn.discordapp.com/attachments/693144185754353694/882020695113089074/Scr_2021-08-30_16-54-39.gif

**Stable Recording**
https://cdn.discordapp.com/attachments/693144185754353694/882021183644643408/Scr_2021-08-30_16-56-43.gif

**Comment by ds-sloth** [comment]
I know this code best; I will go ahead and take a look at it today.

**Comment by ds-sloth** [comment]
Hi @DerpyBubblez, if you can verify that this issue has been resolved on your end that would be great!

PS: I believe there is a vanilla bug here. Try switching sections to an already-visited section while time is stopped in the vanilla game. I'm going to go ahead and patch that as well.

**Comment by ds-sloth** [comment]
I would consider the vanilla behavior a bug here. Could someone verify that the original SMBX acts like the primary branch here? I haven't set up VirtualBox or wine up yet on this machine.

Primary branch (and, to my knowledge, vanilla behavior)
![Scr_2021-09-06_23-47-58](https://user-images.githubusercontent.com/72112344/132281591-a84ca299-ad7a-4823-a1e5-0d956e280628.gif)

Devel branch (compat mode off, new behavior)
![Scr_2021-09-06_23-48-50](https://user-images.githubusercontent.com/72112344/132281592-7fee86b2-4fb0-4c78-ae31-c30c7d8d64e6.gif)

I did introduce a new compat flag here, of course :)

**Comment by DerpyBubblez** [comment]
I can confirm that this is now fixed, but I'm unable to check vanilla.

**Comment by Wohlstand** [comment]
Easy: one of forest levels at The Invasion 2, start the stopwatch, then walk on bridge, then go back, and you'll find cells absent

**Comment by ds-sloth** [comment]
It sounds like the bug has been confirmed to be fixed, and that we also fixed a vanilla bug while we were at it. I'm going to go ahead and close this issue now. Thanks for the report, Derpy!
