### ISSUE TITLE
Too many NPCs get blocks in block-quadtree builds

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#182]
**Describe the issue**

Thanks to @DerpyBubblez for the bug report.

**Example Case**

Minimal test case: [crush.zip](https://github.com/Wohlstand/TheXTech/files/7122873/crush.zip)

**Recording**

Devel (uses block-quadtree):
<img src="https://user-images.githubusercontent.com/72112344/132376069-9b9ffdd2-0e5a-4583-82cd-c2f427dbd1c0.gif" width=400 height=300>

Main:
<img src="https://user-images.githubusercontent.com/72112344/132376098-dac0d5cd-1ad0-49dd-bf69-f97e427cfea4.gif" width=400 height=300>

**Comment by ds-sloth** [comment]
Thanks again to Derpy for the report. Fixed as far as I am aware.

Issue was some code where some NPCs' (saws as well as some platforms) `tempBlock` was unconditionally updated and added to the block quadtree, but that `tempBlock` could have had index 0, in which case the tempBlock should not have existed (**and doesn't get cleaned up**). I wrapped it in a conditional to check that the `tempBlock` is not 0.

Derpy, if you're able to give it a confirmation in your problem case, that'd be great.

**Comment by DerpyBubblez** [comment]
![Scr_2021-09-08_17-00-46](https://user-images.githubusercontent.com/19195170/132591561-7e5ae838-42d6-4fbb-ac17-1413ed83af89.gif)
I can confirm this works as well. In the case of this level, climbing the fence to the left of the sawblade, would also have resulted in being squished.

**Comment by ds-sloth** [comment]
I believe this resolves the issue. Thank you!

As far as I'm aware, there are no longer any reproducible issues unique to the devel branch (except #183 which is awaiting comment), though there is still the disappearing blocks issue in the trains level (probably has to do with moving layers) which I am looking forward to tracking down as soon as I see a reproducible report.
