### ISSUE TITLE
Glitch for "Restart level after death" for old levels

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#188]
**Describe the issue**

Player starts from 1st warp point instead of level start point or a proper warp entrance.

**Example Case**

1-6.lvl from Toad Goes to Outer Space

**Recording**

![Scr_2021-09-16_09-51-52](https://user-images.githubusercontent.com/37089530/133536418-55c917bc-8e6d-459f-8bac-435171de8f05.gif)

**Comment by Wohlstand** [comment]
Now it starts properly, I fixed this case as it causes many problems, so, every time player fails the level, will start from the same entrance as player entered level (or since the checkpoint if player got it)

**Comment by Wohlstand** [comment]
The biggest pain of "restart level after death" was layer states was been confused and autostart events won't start, that was a big problem until now.

**Comment by Wohlstand** [comment]
Okay, I did the little check, the behavior is totally not intended: the entrance door tells to this level tells do start level from the start point, and when player starts at the warp, is not intended. BUT, it's possible condition caused by ... intro level! It used the non-zero warp to enter sub-hubs, and the thing left being not clean because of this lasanha... damn!

**Comment by Wohlstand** [comment]
Reproduced that bug by a simple test:
![Scr_2021-09-27_21-46-30](https://user-images.githubusercontent.com/6751442/134967252-b3ffacb9-883f-47a7-a115-6305b0ff6119.gif)

**Comment by Wohlstand** [comment]
Just now I fixed this bug, please test the thing at the latest dev build (once it gets built)

**Comment by 0lhi** [comment]
My Test Result:

![OldBuildNewBuild](https://user-images.githubusercontent.com/74732674/135280421-74c02cc1-4a26-4d65-9c6f-21a7df078d58.png)

**Comment by Wohlstand** [comment]
Means, the fix work, thanks for the test! :fox_face: :+1:
