### ISSUE TITLE
This gray block (IDK whats his name xd) can be broken with ice block

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#19]
i only tested on NSMBX V1.0p1 (no tested on TheXTech or Vanilla)

see:

![Sin-titulo](https://user-images.githubusercontent.com/60852359/84582525-220d2d80-adbb-11ea-9322-49b0b3550198.gif)

**Comment by Wohlstand** [comment]
The vanilla XTech don't reproduce this bug on a scratch level: 
![Scr_2020-10-17_18-55-14](https://user-images.githubusercontent.com/6751442/96347424-63378600-10aa-11eb-8002-f7dda4102be9.gif)

**Comment by Wohlstand** [comment]
Here too:
![Scr_2020-10-17_18-58-16](https://user-images.githubusercontent.com/6751442/96347601-6a12c880-10ab-11eb-8867-46ebb45a26c4.gif)

**Comment by Wohlstand** [comment]
Okay, @Core-LOVE says that this bug has been fixed a while. Closing this.
