### ISSUE TITLE
Feature Request: Optional Backgrounds for Multires

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#190]
When having a large resolution, 800x600 sections are rather unpleasant to look at:

![Scr_2021-09-21_15-46-35](https://user-images.githubusercontent.com/74732674/134186181-5820baed-ca5a-4e7d-9731-8611cfa51fea.png)

A solution for this would be to allow adding a custom background, for example as */graphics/ui/backgrounds/1280x720.png*.

Here's how it could look like using [this](https://pixabay.com/illustrations/background-circuit-grey-digital-2426328/):

![Scr_2021-09-21_15-46-35-Tech](https://user-images.githubusercontent.com/74732674/134187676-ae91e4f1-7307-4c53-b4c4-97a47c58efb9.png)

**Comment by 0lhi** [comment]
> but the game is drawing at 1440x720px (as it does on some Android phones).

Is there a dedicated 1440x720 setting on Android, or is that a result of the Dynamic setting?

I think, the dedicated settings should have two options: Using a Background that exactly fits the resolution (e.g. 1280x720.png), and using the one for the Dynamic setting as a fallback. Dynamic.png should be assumed to be a seamless repetition such as [this one](https://pixabay.com/illustrations/seamless-repeat-repetitive-2033661/).

The Game output should be outlined by the engine.

Making a beautifully framed image isn't really the point of this, but if some want to do so, they can just use Mode 2 or 3 to force an 800x600 output. Maybe that could be triggered by a Compat.ini setting, if there is demand for that.

The engine shouldn't do anything to the background aside from displaying it. Repeatedly in the case of Dynamic.png.

At least, that's what I think. Fancy stuff could be nice, but would be hard to implement, and I don't think that's worth it.

**Comment by ChristianSilvermoon** [comment]
Suggestion: Base it on the same thing the World Map is doing currently, but maybe make it a different color? Maybe a dark color with the decorative shapes a slightly lighter shade?

**Comment by 0lhi** [comment]
The current World Map solution isn't reliable.

**_Dynamic SMBX:_**

![WorldMap](https://user-images.githubusercontent.com/74732674/134529589-a32a5df9-973d-4b59-86fd-b616fb88d4c7.png)

**_1280x720 Demo:_**

![WorldMap2](https://user-images.githubusercontent.com/74732674/134529595-6d19c58e-26a1-4530-aa55-5450b5f3ce79.png)

The Seamless approach would benefit it, too.

**Comment by 0lhi** [comment]
Btw, it may be worthwhile to limit the default Map Output to 668x404, and allow bigger sizes with a .wldx setting.

It would look slightly weird on old episodes, but less so than black areas and borders of a different world.

**Comment by ajleite** [comment]
Regarding your most recent comment: it's not hard to work out the furthest point visible from anywhere on the contiguous path in the vanilla game. We could then (1) make the Map Output never be larger than the largest rectangle that is included in the visible map component, and (2) scroll the Map Output dynamically (not just centering the player) so that it only includes the areas that would ever be visible. Meaning that when the player is at the lower boundary of a component of the world map, they would be lower than the center of the screen, etc.

Would that be a good compromise to resolve your concern without forcing users to add compat.ini annotations to fully enjoy their episodes?

**Comment by ds-sloth** [comment]
Oops, accidentally responded from professional account. :)

Regarding your most recent comment: it's not hard to work out the furthest point visible from anywhere on the contiguous path in the vanilla game. We could then (1) make the Map Output never be larger than the largest rectangle that is included in the visible map component, and (2) scroll the Map Output dynamically (not just centering the player) so that it only includes the areas that would ever be visible. Meaning that when the player is at the lower boundary of a component of the world map, they would be lower than the center of the screen, etc.

This would mean that on your top example, the level would be scrolled a little less to the right than it is currently.

Would that be a good compromise to resolve your concern without forcing users to add compat.ini annotations to fully enjoy their episodes?

**Comment by ds-sloth** [comment]
You say the seamless approach would benefit the World Map backgrounds, but I'm not sure how a nontrivial pattern (such as the clouds) could be made seamless given that we don't know how many repetitions would be possible. The world background isn't just a pattern, but is in fact different in each corner (see the shadows of the SMBX background, for example).

I honestly think that the current solution you showed in your two screenshots is ideal, but if you have a better suggestion, I'm happy to try it out.

**Comment by 0lhi** [comment]
> (1) make the Map Output never be larger than the largest rectangle that is included in the visible map component
> (2) scroll the Map Output dynamically (not just centering the player) so that it only includes the areas that would ever be visible.

Sounds good! However, the Output should be at least 668x404, as sometimes, Black Backgrounds are intentional. Example from SMB3 Remake:

![MapBlackBorder](https://user-images.githubusercontent.com/74732674/134672771-158ef50d-28ab-4650-90a2-56cb326b9217.png)

> but if you have a better suggestion, I'm happy to try it out.

Remove the Border from Interface4.png to make it seamless, and have TheXTech generate the border with a half-transparent shadow:

![Interface4](https://user-images.githubusercontent.com/74732674/134674077-dc0a64f7-2710-49c5-aab3-6ce60e6e669d.png)

Adventures of Demo would need a new Cloud Picture.

**Comment by Wohlstand** [comment]
Cloud picture was made from off background pictures, and crafted from off public domain images taken on Open-Game-Arts place, I may put something to here, it's need to make the seamless thing later

**Comment by Wohlstand** [comment]
[_misc.zip](https://github.com/Wohlstand/TheXTech/files/7228805/_misc.zip)

**Comment by ds-sloth** [comment]
Okay, I will set the world map up to accept either interface4.png with my current scaling algorithm or interface4_tile.png with the "seamless" tiling algorithm + shadow.

For the black screen replacement, I will do seamless tiling only. I think our discussion here made it clear that that is the best approach for most use cases.

**Comment by 0lhi** [comment]
> I may put something to here, it's need to make the seamless thing later
> [_misc.zip](https://github.com/Wohlstand/TheXTech/files/7228805/_misc.zip)

Draft:

![SeamlessClouds](https://user-images.githubusercontent.com/74732674/134775109-65c25461-3a69-455a-9793-a01ef5fa0167.png)

**Comment by ds-sloth** [comment]
All of these features (except smart world map screen crop, separate issue) should be ready to test.

Save some file as `graphics/ui/Backdrop.png`, another as `graphics/ui/WorldMapFrame_Tile.png`, and copy the example `docs/WorldMapFrame_Border.png` into `graphics/ui`. Let me know how the results look to you!

Custom configuration for `WorldMapFrame_Border.png` (the outer top, left, right, and bottom sizes, and the sizes of the "inner" top, left, right, and bottom areas) will be supported, but it is not supported currently. The current set up is as follows:

```
int t = 2;
int te = 18;
int l = 2;
int le = 18;
int b = 18;
int be = 0;
int r = 18;
int re = 0;
```

**Comment by 0lhi** [comment]
World Map looks good.

![Scr_2022-05-27_15-20-02](https://user-images.githubusercontent.com/74732674/170708131-c53b8d3a-0d8b-470e-b548-5500c8f44698.gif)

Could you add an Outline to the Level-Border? Maybe as ```Backdrop_Border.png```?

**Comment by ds-sloth** [comment]
Sure. I'll use the same code, and the same ini format (eventually) to render it.

**Comment by ds-sloth** [comment]
Still no INI loading for the formatting details, but the important code is there now.

<img src="https://user-images.githubusercontent.com/72112344/177016001-0bc8aa85-5e51-4d06-a99e-caa64884894a.gif" width=640 height=360>

**Comment by 0lhi** [comment]
Great! I suggest this combo for the SMBX Asset Pack:

[Backdrop.zip](https://github.com/Wohlstand/TheXTech/files/9033807/Backdrop.zip)
![Scr_2022-07-03_00-30-33](https://user-images.githubusercontent.com/74732674/177018037-5bb5b3cd-1cf1-4bac-a44c-40d7ef590ec7.gif)

**Comment by 0lhi** [comment]
Has been done =)
