### ISSUE TITLE
Suggestion: Improve Map UI at Lower Resolutions

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#194]
When the game is running at lower resolutions information becomes very crowded and cramped. It may be more ideal to migrate some of the counters to a more optimized position for visual parsing

![image](https://user-images.githubusercontent.com/30162808/135170577-f71b4b2a-c279-4c70-8156-2d2cb9488347.png)

This image from @ds-sloth  over on Discord also shows that the word-breaking is also sub-optimal.

I created a couple of mockups to visually showcase what I think could help here:
![image](https://user-images.githubusercontent.com/30162808/135170551-dc6b17c1-e2d6-4d0d-8bec-ac5d7194617d.png)

Improving how the game breaks level names up into multiple lines and optimizing the position of the informational elements can improve readability greatly.

**Comment by ds-sloth** [comment]
@ChristianSilvermoon is it okay for us to close this issue and consider the compressed world HUD as a future feature (possibly along with a compressed level HUD).

**Comment by ChristianSilvermoon** [comment]
> @ChristianSilvermoon is it okay for us to close this issue and consider the compressed world HUD as a future feature (possibly along with a compressed level HUD).

Yes, absolutely ^^

**Comment by ds-sloth** [comment]
Great! If you would like to file an additional issue for that feature now, feel free, or we can simply remember it. I don't think I'll be implementing it in the short-term future though.
