### ISSUE TITLE
Suggestion: A new version of the has-item (sound-12) sound

### ISSUE THREAD

**Issue by vitzie629** [Wohlstand/TheXTech#197]
In Super Mario World and Super Mario All Stars, when the player already has a power-up and touches the same power-up as earlier (example: Fire Mario in SMB, SMB3, and SMW touches a fire flower), the player-grow sound plays for SMB and SMB3, and for SMW, the player-grow and has-item sound plays together. The old has-item sound should be replaced with a new one which is the has-item and player-grow sounds combined together to make it sound like SMW.

[New has-item sound.zip](https://github.com/Wohlstand/TheXTech/files/7270678/New.has-item.sound.zip)

**Comment by Wohlstand** [comment]
The fact I don't need to replace the sound actually, but I can play two sounds in parallel :)

**Comment by vitzie629** [comment]
> The fact I don't need to replace the sound actually, but I can play two sounds in parallel :)

How do you play two sounds in parallel?

**Comment by Wohlstand** [comment]
> How do you play two sounds in parallel?

Easily, in the code making two lines of the sound play:
```cpp
PlaySound(SFX_PlayerGrow);
PlaySound(SFX_GotItem);
```

**Comment by vitzie629** [comment]
> > How do you play two sounds in parallel?
> 
> Easily, in the code making two lines of the sound play:
> 
> ```c++
> PlaySound(SFX_PlayerGrow);
> PlaySound(SFX_GotItem);
> ```
> 
> This call is fully asynchronious, once I call, the sound starts to play, calling them two, the two sounds will be played

Thanks! Will you do that for TheXTech 1.3.5.2 or 1.3.6?

**Comment by Wohlstand** [comment]
I made a quick test, I madded this behavir into hammer suit taking (kept old sound behavior for leaft and other things), so, see the result:
https://user-images.githubusercontent.com/6751442/135699059-26773d70-293d-419d-a32f-b41ea9077740.mp4

**Comment by vitzie629** [comment]
> I made a quick test, I madded this behavir into hammer suit taking (kept old sound behavior for leaft and other things), so, see the result:
> https://user-images.githubusercontent.com/6751442/135699059-26773d70-293d-419d-a32f-b41ea9077740.mp4

I saw the result and the hammer suit test with the two sounds together sound great!

**Comment by 0lhi** [comment]
I'm not sure where's the logic behind playing the grow sound when the Character isn't growing.

This should be optional and opt-in.

**Comment by P-Star7** [comment]
I think instead we can use a third unique sound, because New Super Mario Bros. and New Super Mario Bros. 2 have a unique sound for it.

**Comment by vitzie629** [comment]
> I think instead we can use a third unique sound, because New Super Mario Bros. and New Super Mario Bros. 2 have a unique sound for it.

Really? What does the unique sound sound like? Can you give me an audio clip of it?

**Comment by Wohlstand** [comment]
Feature has been merged and it's now on top of master. You'll find a new setting at settings/thextech.ini file at the "[effects]" section

**Comment by Wohlstand** [comment]
As @0lhi already tested its work, the issue has been complete.
