### ISSUE TITLE
compiling on 10.11 but it says "this app is for macos 10.12"

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#2]
i am who compiled this in 10.11, and the game works but i can't open it with two clicks, i need to get inside the bundle to run the game and that takes away the grace of using .app

**Comment by Wohlstand** [comment]
Modify this line into 10.11 https://github.com/Wohlstand/TheXTech/blob/master/CMakeLists.txt#L34 and re-run cmake, then, make clean and build it again.

**Comment by Wohlstand** [comment]
btw. I really need to try use the "10.5" setup :thinking: 
SDL2 by it's documentation seems has this version be a minimal...

**Comment by M0REKZ** [comment]
Before I had tried that with textedit and cmake did not work (error), now I tried with text wrangler and cmake worked, I will not use textedit again :T

**Comment by M0REKZ** [comment]
an answer.. .Would it affect a lot if I put "release" instead of "debug" in cmake?

**Comment by Wohlstand** [comment]
> an question.. .Would it affect a lot if I put "release" instead of "debug" in cmake?

The "release" build is different from "debug" that it has enabled optimizations and dead stripping on. Debug build keeps all internal debug symbols and no optimizations on which can be easily used with a debugger program (allows you to use break points in a code or catch a crash in a specific line, etc.)

> I will not use textedit again

Lol, it's a most clunkiness text editor in a universe! So, there are lots of alternatives are friendly for code editing (scripts, web pages, config files, source codes, etc.): Visual Studio Code, Atom, Xcode itself can be used for scripts editing. Also some plain text editors I had to find on App Store, etc.

**Comment by M0REKZ** [comment]
text wrangler is the king xd

**Comment by Wohlstand** [comment]
I see, also nice thing :fox_face:
