### ISSUE TITLE
(Option) SMW Original Yellow Beach Koopa/shell behaviour

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#207]
SMBX behaviour: When a green or red beach koopa takes a yellow shell, it turns into a rainbow shell. When a yellow beach koopa takes a green, red, or blue shell, it turns into a yellow koopa.
SMW behaviour: When a green or red beach koopa takes a yellow shell, it turns into a yellow koopa. When a yellow beach koopa takes a green, red, blue, or yellow shell, it turns into a rainbow koopa.

The summary is that in SMBX, the rainbow shell is determined by any beach koopa taking the yellow shell. But in SMW, it is determined by the yellow beach koopa taking any shell.

**Comment by ds-sloth** [comment]
This is obviously outside of the project's current aims. I'll close it now. Wohlstand, feel free to reopen if you disagree.
