### ISSUE TITLE
Split the FrmMain class into many role-specific things

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#210]
From a discussion for pull-request #200, we need to improve the platforms support between different sub-systems managed. Current FrmMain is a god thing that unites the graphics and controls at one big pagan god of the Game.

So, instead of FrmMain class, make:
- The static interface for graphical rendering (similar to that one made at Moondust Engine to support OpenGL of different versions and the SDL Render as a fallback).
- The similar static interface(s) to manage controls (joysticks, events, keyboard, and mouse).

Right now for the 1.3.5.2 it's too radical change, so, let's put it for future work.

**Comment by ds-sloth** [comment]
I am currently handling the Controls in the branch `wip-abstract-controls` -- anybody interested can follow recent changes there.

**Comment by Wohlstand** [comment]
Done at #241
