### ISSUE TITLE
[Suggestion] - Improve Episode List Navigation

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#211]
For those that play many episodes, the list can become very time consuming to navigate

It would be really nice if:
• The Top of the list always had a "Resume Last Episode" option. Possibly have the last loaded episode at the top, but with the name displayed in green. This would allow you to just mash the confirm button through menus until you got to the gameplay.
• Left/Right jumped a page up/down in the list (IE 5 episodes up and down if 5 episode names are displayed)
• Possibly a way to 'favourite' episodes to keep them sorted at the top? :thinking:

**Comment by ChristianSilvermoon** [comment]
As an update, e283c8e basically gives us the Resume Last Episode functionality mentioned above.

I would propose pressing **Alt Run** on the episode select menu 'favourite' an episode.  Doing so could change the episode's name color, or alternatively (or additionally) display the ★ gylph to the left of the name.

Pressing **Drop Item** could then toggle between showing all Episodes or only Favourite Episodes (along with the last episode)

**Comment by Wohlstand** [comment]
I made some here:
https://github.com/Wohlstand/TheXTech/commit/110cc713b91fb094a57fcc46aa9ddc823e747f68

I added more controls and a mouse wheel, but:
- because of menu specifics, I do scroll 3 items than 5
- mouse wheel can be used to scroll the list too
- I didn't made any resorting things because I think, that's reasonable to do after menu rework will be done

**Comment by Wohlstand** [comment]
This thing was done a while ago, so, it can be closed.
thanks to @0lhi for notice.

**Comment by Wohlstand** [comment]
There are next things done:
- Left-Right to scroll pages
- Alt-Run, Alt-Jump to go up and down of the list
- Drop to return to the recently played episode
- And, recently played episode will be remembered, so, can be quickly continued from the same place.
