### ISSUE TITLE
Suggestion: Add a simplified version of the Moondust Maintainer to TheXTech's Options

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#212]
This would allow Users to:

* Shrink the filesizes of their games by converting GIFs to PNGs and maybe MP3s to OGGs
* Fix the Friendly Star Bug [#84](https://github.com/Wohlstand/TheXTech/issues/84) for episodes in which it occurs

without having to quit the game.
![Maintainer](https://user-images.githubusercontent.com/74732674/137042110-c0d30a2e-3e47-4ec7-baff-0926029f1e37.png)

**Comment by 0lhi** [comment]
Closing this as I no longer think this would be a good fit for TheXTech.

**Comment by Wohlstand** [comment]
TheXTech is not an SDK or devkit, such functionality is better to be a part of devkit then. So, right.
