### ISSUE TITLE
Idea with the Menu UI graphics

### ISSUE THREAD

**Issue by vitzie629** [Wohlstand/TheXTech#219]
I have an idea for the menu UI graphics for the next version of TheXTech and they involve the logo and the bottom with the website URL. Firstly, the logo should feature the word "version" under the left of the name "Mario" as shown in the picture and under the word "version" is a version number which says "1.3.x.x". An example of a version number is "1.3.6" which has 3 digits and another example is "1.3.5.3" where it has 4 digits. If the version has 3 digits, the 4th number would be removed. 
![SMBX_Logo_With_Version_Number](https://user-images.githubusercontent.com/90484844/138535339-a608f656-9e1d-4e09-aff5-c89ae2a1cd7c.png)
Secondly, the website URL should have a copyright saying "Copyright 2020-202x Wohlstand" above the "Wohlsoft.ru" URL as pictured. The copyright idea is very similar to the one on SMBX-38A (1.4.x).
![copyright_wohlstand](https://user-images.githubusercontent.com/90484844/138535344-303a8990-50e5-449d-bab1-f9381171262c.png)
What do you think of my idea for future versions of TheXTech intended for the menu UI graphics?

**Comment by Wohlstand** [comment]
On-logo version should be configurable dynamically via gameinfo.ini, mainly, there are different assets packs that may have differently designed logo, and version number will make it suck. So, gameinfo.ini should define the relative coordinates where print the version number and which font to use.

Copyright notice instead lf url seems a good idea. Additionally, the "thanks for playing the game" at the credits looks better than just the url (again, was been saw at SMBX-38A). Anyway, the text at the bottom is just a picture at assets, so, can be easily replaced with another one, and, there is no limit on the size as we though for all 10 years, the Redigit's code against url at the bottom and the logo at the top, used dynamical logic.

**Comment by Wohlstand** [comment]
Anyway, the engine's version is already printing at the window's title, but, that won't work on mobiles and consoles that don't has window term at all and always work fullscreen.

**Comment by ds-sloth** [comment]
An in-game display of the current version is a very good idea. Separately, I think that Wohlstand has already adjusted the credits?

**Comment by ds-sloth** [comment]
I've added this to the title screen. How does this format look to you? The branch name is only shown at non main / stable branches, and the git commit hash is omitted in release builds.

<img src="https://github.com/Wohlstand/TheXTech/assets/72112344/28f7d0b0-27ae-4367-8ed4-00a8ab5cf11b" width="400" height="300">
<img src="https://github.com/Wohlstand/TheXTech/assets/72112344/ad49f0ee-5825-40b2-8849-7485d30613ae" width="400" height="300">

**Comment by ChristianSilvermoon** [comment]
@ds-sloth that's looking absolutely *perfect* to me

**Comment by ds-sloth** [comment]
I think we can close this issue now. We have an in-menu version display, and the copyright message is easy to add to the game assets if desired.
