### ISSUE TITLE
Small event sound glitch

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#23]
@LoveBodhi reports next:

> I found a message block sound bug:
> 
> If event was filled message, press "Jump" button still plays message sound after message disappeared......

See [original post](https://wohlsoft.ru/forum/viewtopic.php?f=5&t=3677&p=20760#p20760).

**Comment by LoveBodhi** [comment]
This was tested by me.

**Comment by Wohlstand** [comment]
"I can't test this yet" I mean that I am right now at my workplace, and I am be able to verify the thing and try to fix it once I'll be at home, at evening (UTC+3, -5 hours difference with China)

**Comment by Wohlstand** [comment]
I tried, but it won't reproduce the bug:
[Message box test.lvlx.zip](https://github.com/Wohlstand/TheXTech/files/5467766/Message.box.test.lvlx.zip)
Can you upload your demo level that can reproduce the bug?

**Comment by LoveBodhi** [comment]
Ohhh. Just a level which is misattached "Message" Sound!!!!

**Comment by Wohlstand** [comment]
I see, so, no bug, just a mistake in a level itself :fox_face:
