### ISSUE TITLE
Keyhole animation

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#237]
I still think about ways on implementing the keyhole animation, additionally putting my eye on X2's sources.

Quote from #63:
> @ChristianSilvermoon The Key Hole Effect (could zoom the keyhole graphic and shrink it to accomplish the effect with no additional assets maybe?)

So, there are some variants on how it could be implemented:
1) **Simple polygonal:** Draw the polygon which represents the keyhole, then, zoom in, pause, and zoom out with a specific time period. Gradually hide the player through the keyhole. It can be implemented using SDL Render API easily.
2) **True replica:** This method requires masking the drawn player inside the keyhole on the "disappearing" step. This method requires direct OpenGL use, otherwise, SDL Render API seems to lack the masking ability. Probably a recent update that introduces an ability to draw figures of any shape, but no idea about masking of drawn textures.
3) **Simple raster:** as @ChristianSilvermoon suggested, zoom in the BGO itself. This method allows using a different sort of keyhole replacement that has a different shape (for example, Lowser's Conquest Beta uses the star ball instead of the key and keyhole). However, the resulting quality wouldn't be clear as vector methods.

Maybe something also?

**Comment by Alucard648** [comment]
I would like it to be an option for key itself (NPC-31).

**Comment by ds-sloth** [comment]
I think simple raster might be good in the style and in keeping with the classic style of the game, while also remaining simple to implement.

**Comment by suicvne** [comment]
I was thinking about this overnight. I agree a simple scaling raster would be the easiest. 

I had an idea and wanted to mock it up, so I decided to make it. It involves a keyhole image of a size that looks like this: 
![KeyholeInverse](https://user-images.githubusercontent.com/861492/147830530-21b368be-dfe6-4371-b850-f1b150662281.png)

I adjusted Unity to have the 0,0 set at the bottom left. The C# script is fairly simple and could be translated to C code very easily. However, this allowed me to quickly visualize what would need to happen. 

It is pictured here with ugly red w/ green outline for easier visualization. Breaking it down, there are 5 components:

- Keyhole Image, being rendered at a specific x/y/w/h: KeyholeImagePosX, KeyholeImagePosY, KeyholeImageRenderedSizeW, KeyholeImageRenderedSizeH
- 4 simple renderRects 
- Left-Side: w = KeyholeImagePosX, H = ScreenHeight, x = 0, y = 0
- Right-Side: w =  ScreenWidth - (KeyholeImagePosX + KeyholeImageRendereredSizeW), H = ScreenHeight, x = ScreenWidth - w, y = 0
- Bottom Side: w = KeyHoleImageRenderedSizeW, h = KeyHoleImagePosY, x = KeyholeImagePosX, y = 0

For the purposes of a quick animation, the side rects can be updated every frame while the animation is active. As you can see, it's quite flexible. 

https://user-images.githubusercontent.com/861492/147830834-fae131be-d42f-45d0-b5e4-94fc72f73375.mp4



https://user-images.githubusercontent.com/861492/147831182-a192b73a-38cc-4b2c-8772-466395974ced.mov

Thoughts?

**Comment by Wohlstand** [comment]
Looks interesting, and I probably guess, if use SDL Rrender, I could try to trick using middle textures and "render to texture" thing, etc. Will try check more detailed tomorrow 👀

**Comment by suicvne** [comment]
I'm excited to see your implementation Wohlstand! This was the most direct way I could think to easily implement a raster based version, no doubt you'll have more cool tricks up your sleeve :D

**Comment by 0lhi** [comment]
Since #240 necessitates direct OpenGL usage, I think we should go with **2. True Replica** for Hardware Mode, and **1. Simple Polygonal** for Software Mode.

**Comment by ChristianSilvermoon** [comment]
> Since #240 necessitates direct OpenGL usage, I think we should go with **2. True Replica** for Hardware Mode, and **1. Simple Polygonal** for Software Mode.

I like that suggestion, but also think the third should perhaps be an option for custom episodes seeking to replace the graphic for whatever reason

**Comment by 0lhi** [comment]
> I like that suggestion, but also think the third should perhaps be an option for custom episodes seeking to replace the graphic for whatever reason

@ChristianSilvermoon The problem is that would change the kind of animation. With the graphics example, it would cover the entire screen, while Replica and Polygonal would just cover the Player.

What do you thing about allowing different shapes natively and letting the Player choose them with a compat effect entry?

```secret-exit-animation-shape = keyhole, star, square, orb, triangle, hexagon, etc```

> (for example, Bowser's Conquest Beta uses the star ball instead of the key and keyhole)

@Wohlstand  Can you post a GIF of how that looks like?

**Comment by ChristianSilvermoon** [comment]
> > I like that suggestion, but also think the third should perhaps be an option for custom episodes seeking to replace the graphic for whatever reason
> 
> @ChristianSilvermoon The problem is that would change the kind of animation. With the graphics example, it would cover the entire screen, while Replica and Polygonal would just cover the Player.
> 
> What do you think about allowing different shapes natively and letting the Player choose them with a compat effect entry?
> 
> `secret-exit-animation-shape = keyhole, star, square, orb, triangle, hexagon, etc`
> 
> _EDIT: Or, Special Values set at the Editor would seem even more appropriate here._
> 
> > (for example, Bowser's Conquest Beta uses the star ball instead of the key and keyhole)
> 
> @Wohlstand Can you post a GIF of how that looks like?

The example shown by @suicvne isn't actually accurate to SMW.

In SMW the keyhole zooms out from its position in world, behind the player, but over top of tiles, then zooms back in as if taking in the player like is seen [here](https://youtu.be/futxNTZQGTU?t=22)

**Comment by suicvne** [comment]
> The example shown by @suicvne isn't actually accurate to SMW.

Yes, I was aware when I created the example. It was really just an example of what *could* be done ;)

**Comment by ds-sloth** [comment]
<img src="https://user-images.githubusercontent.com/72112344/194680210-379cc5e5-22dd-4809-9b0e-c20d3a6d0d93.gif" width="400" height="300">
<img src="https://user-images.githubusercontent.com/72112344/194680235-3390d90f-d27f-40b0-b1e1-b7c88fa1d133.gif" width="400" height="300">

How does something like this look do everyone?

It doesn't require stencils or a separate render target, so it will be easy to support across all of our renderers, even ones like 3DS and Wii with limited VRAM where render-to-texture is difficult.

If people like it, I can implement it for real (this is just a quick and dirty mockup that only works for mountless Mario) after we merge the Wii and 3DS port branch. That branch includes simplified player render code that will make this easier to implement for all player/mount combinations.
