### ISSUE TITLE
Make Android build

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#24]
The game is already can be easily ported to Android.
Before starting, need:
- [x] Backport on-screen keyboard from PGE Engine
- ~~Make an archive package to deploy default resources and episodes~~ Let's make this later, it would be a nice feature for episode or game packages who won't allow free access into their game's resources.
- [x] Make proper read-write storage request of permission to retrieve custom episodes at the user's home. Don't ask permissions to play default episodes, packed with APK.

### Important and must be implemented first
- [x] Fix the glitchy touchscreen controller, make it don't release other keys when releasing any arrow keys.
- [x] Make the touchscreen controller scale the size depending on a screen diagonal (for small phones and big tablets, let have the layout of keys being different).
- [x] Allow users to use different assets path to allow installing the stuff on the SD card to save the phone local space.
- [x] Fix the Android 11 compatibility by using the alternative resources directory storage

### Optional and can be done later
- [x] Fix the Android 5.1 startup crash on Archos 70c Xenon tablet (caused by the wrong single-instance workflow). [Details here](https://github.com/libsdl-org/SDL/issues/4040). The good news that is confirmed the proper work on other Android 5.1-based devices: the game doesn't fail.
- [x] Fix the blind black screen after switching between different applications (make sure to reload all textures after the device reset event came). [Details here](https://github.com/libsdl-org/SDL/issues/4041).
- [x] Make the CI build (the article that explains things [is here](https://habr.com/ru/post/506700/))

P.S. Once the main TODO list will be completed, release the first public Android version of the game with the same version as the latest release.

**Comment by Wohlstand** [comment]
On Android 11 at the tablet of my friend @Coonrac, the game starts, but it won't able to see any files but pictures, it won't see INI files, it won't create folders and write log files, etc. There is a required solution to use the same sort of "<storage>/Android/data/ru.wohlsoft.thextech/", or something to store the game resources, etc. A similar one QQ thing does...

**Comment by Wohlstand** [comment]
Android 11 compatibility should be fixed by the ab7b5f0216ab82365f2676675ef5da27e9947ba2 change.

**Comment by Wohlstand** [comment]
Okay, the whole Android milestone has been completed!
Any next features/add-ons will be developed later for next version of the game.

**Comment by Djbrotherson** [comment]
Can this be updated so we can play 38A games?

**Comment by Wohlstand** [comment]
Support of 38A games is a long term task that has many things needed to be implemented.
