### ISSUE TITLE
TheXTech fails to build on ppc64le

### ISSUE THREAD

**Issue by anengineer1** [Wohlstand/TheXTech#25]
I might not have the programming skills but I do have the hardare to test

Engine fails to build with the following output:

[ 37%] Linking CXX executable output/bin/thextech
/usr/bin/ld: output/lib/libFreeImageLite.a(pngrutil.c.o): in function `png_read_filter_row':
pngrutil.c:(.text+0x8ce8): undefined reference to `png_init_filter_functions_vsx'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/thextech.dir/build.make:1157: output/bin/thextech] Error 1
make[1]: *** [CMakeFiles/Makefile2:148: CMakeFiles/thextech.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

Thank you

**Comment by Wohlstand** [comment]
I guess you had an old build of libFreeImage and it reports the call missing at libPNG. Try to remove the "build/external" directory and run the build again.

**Comment by anengineer1** [comment]
Tried what you said, the result is the same... I know someone who might have the answer to this... I hope he accepts the challenge... he is quite busy

**Comment by Wohlstand** [comment]
btw, what CMake arguments you typed, and what distro you have?

**Comment by anengineer1** [comment]
I use void and I used no cmake arguments, btw, the person replied me with this:

yeah the problem is freeimage bundling its own libpng but not the ppc64 vsx code that libpng has.                                                                              
a workaround might be putting -DPNG_POWERPC_VSX_OPT=0 into your CFLAGS/CXXFLAGS                                                                                                
which will disable the vsx paths entirely                                                                                                                                      it's slower, but probably least effort

**Comment by Wohlstand** [comment]
> I use void and I used no cmake arguments, btw, the person replied me with this:
> 
> yeah the problem is freeimage bundling its own libpng but not the ppc64 vsx code that libpng has.
> a workaround might be putting -DPNG_POWERPC_VSX_OPT=0 into your CFLAGS/CXXFLAGS
> which will disable the vsx paths entirely it's slower, but probably least effort

!!!!
I think you should specify the CMake option to prefer use system libraries rather build own, my FreeImageLite supports that:
`-DUSE_SYSTEM_LIBS=ON`. You also can install libsdl2-dev and use SDL2 from the system: `-DUSE_SYSTEM_SDL2=ON`.

**Comment by Wohlstand** [comment]
> -DPNG_POWERPC_VSX_OPT=0 into your CFLAGS/CXXFLAGS

Or I should detect the PowerPC architecture, and set this flag inside of FreeImage when the "build in a place" option was specified :thinking:

**Comment by q66** [comment]
the right solution is just importing the right files and incorporating them into the build conditionally

(for distribution, using system libs is the best idea though)

**Comment by Wohlstand** [comment]
> the right solution is just importing the right files and incorporating them into the build conditionally

You right :fox_face:  However, the local build of "libpng" at FreeImage is a workaround itself: the original author made that. I made the option to use libraries from the system or built externally rather than use this workaround. The only purpose of this workaround is quick builds on raw platforms and Windows where the presence of libPNG may not be.

> (for distribution, using system libs is the best idea though)

When generating packages for target distros, rather than generating standalone portable executables.

**Comment by q66** [comment]
well, freeimage upstream is really where this should be fixed

it shouldn't be much work, probably

**Comment by Wohlstand** [comment]
At me here the forked version is used:
https://github.com/WohlSoft/libFreeImage
I can fix that easily.

**Comment by Wohlstand** [comment]
I called it as `libFreeImageLite`.

**Comment by pancakers2001** [comment]
hey sorry to revive an old issue, but I'm having the same problem on aarch64 - anything I can do to get this working myself or should I wait for a fix?

**Comment by Wohlstand** [comment]
> hey sorry to revive an old issue, but I'm having the same problem on aarch64 - anything I can do to get this working myself or should I wait for a fix?

Please try to build with the `-DUSE_SYSTEM_LIBS=ON` CMake flag

**Comment by pancakers2001** [comment]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/pancakes/TheXTech/FREEIMAGELITE_HEAD_DIR
   used as include directory in directory /home/pancakes/TheXTech
/home/pancakes/TheXTech/MIXERX_HEAD_DIR
   used as include directory in directory /home/pancakes/TheXTech

**Comment by Wohlstand** [comment]
Damn... I need to make the ability to bypass build flags to FreeImage to enforce it use system libPNG and libJPEG rather try to build them in a place.

**Comment by Wohlstand** [comment]
@pancakers2001 , just now I added a thing: 
* please pull
* build with `-DUSE_SYSTEM_LIBS=OFF -DUSE_FREEIMAGE_SYSTEM_LIBS=ON`

**Comment by Wohlstand** [comment]
make sure libpng-dev and libjpeg-dev (or packages with different names) installed

**Comment by pancakers2001** [comment]
https://pastebin.com/SX3mfuR9

**Comment by Wohlstand** [comment]
Damn, I forgot to add `find_library` and linking of libPNG and libJPEG, sorry, gotta to fix that...

**Comment by Wohlstand** [comment]
@pancakers2001 , I made a fix just now, please pull and try to build again.

**Comment by pancakers2001** [comment]
successful build on aarch64, thanks for the help.

**Comment by Wohlstand** [comment]
Then, I'll close this issue, but I'll add the issue task into my FreeImage library to make it produce proper build of libPNG in the box on PowerPC builds.
