### ISSUE TITLE
Modern Mario & Luigi GFX for TheXTech

### ISSUE THREAD

**Issue by vitzie629** [Wohlstand/TheXTech#260]
![Modern_Mario_ _Luigi_GFX](https://user-images.githubusercontent.com/90484844/151433508-a9f54eac-2151-4c32-a466-bed167f7e164.png)
SMBX is a Mario fan-game based on mainly SMAS SMB3 and while the Mario & Luigi graphics are from SMAS SMB3, they have always been like that ever since and all SMBX branches are like that without differences. To me, the SMAS SMB3 Mario & Luigi graphics are VERY outdated and modern Nintendo games have Mario & Luigi appear like that with white gloves and yellow buttons on the overalls as pictured above. For the next version of TheXTech, Mario and Luigi should have an updated look for the new default SMBX graphics while keeping the SMAS SMB3 style outline-wise.

**Comment by Wohlstand** [comment]
Good thing, that's more for assets package than for TheXTech itself (except for releases with pre-packed assets), so, Android users and users who prefer to combine assets and plain executables by theme selves, would get this update quicker even with a current version :fox_face:

**Comment by vitzie629** [comment]
> Good thing, that's more for assets package than for TheXTech itself (except for releases with pre-packed assets), so, new Android users and users who prefer to combine assets and plain executables manually, would get this update quicker even with a current version 🦊

As you mentioned that this change is designed for the assets package, the real reason I wanted to commit this idea is because Toad now has more of a modern look for full consistency with modern Nintendo games and I feel Mario & Luigi should have full consistency with modern Nintendo games featuring Mario & Luigi.

**Comment by Wohlstand** [comment]
Right, I think, @0lhi would join this discussion

**Comment by vitzie629** [comment]
> Right, I think, @0lhi would join this discussion

Excellent idea!

**Comment by 0lhi** [comment]
> the real reason I wanted to commit this idea is because Toad now has more of a modern look for full consistency with modern Nintendo games

For Toad, there was more of a reason to update because the old Ice & Fire Toad sprites were confusing. There was a vote on the [Wohlsoft Forums](https://wohlsoft.ru/forum/viewtopic.php?f=94&t=4289) that concluded the SMB2 Toad should be replaced with the Blue SMB3 Toad. The reason that hasn't happened yet is because there's no system for backward-compatibility yet, which would be needed for levels like the example from RMN.

Many months ago I have suggested a costume system that allows users to choose their preference, but to fallback to Vanilla sprites or any other costume chosen by compat.ini. I think, that would be good for this case, too. I can open a GitHub Issue on it these days.

Once that is done, there should be no issue to add your updated Sprites. If you'd like them to be the default ones, it would have to meet (at least) two requirements:

* Shapes identical to the original (I can verify that if you send me)
* The Community votes to replace them (probably here or on Wohlsoft)

**Comment by vitzie629** [comment]
1. Shapes identical to the original (I can verify that if you send me), what are you talking about and how do I do that?
> * The Community votes to replace them (probably here or on Wohlsoft), when would the poll begin and end.

**Comment by Wohlstand** [comment]
> What are you talking about and how do I do that?

Means, that is needed to keep the same mask shape, otherwise this would break the compatibility with a set of custom GIF graphics that replaces fronts only but don't changes any masks (so, masks are re-generated vendored PNG assets)

**Comment by Wohlstand** [comment]
Otherwise, old sprites will take one another `fallback` mask copies for these cases

**Comment by vitzie629** [comment]
> Otherwise, old sprites will take one another `fallback` mask copies for these cases

Thanks.

**Comment by vitzie629** [comment]
> > What are you talking about and how do I do that?
> 
> Means, that is needed to keep the same mask shape, otherwise this would break the compatibility with a set of custom GIF graphics that replaces fronts only but don't changes any masks (so, masks are re-generated vendored PNG assets)

Thank you! The new default GFX for Mario and Luigi WILL DEFINITELY have the EXACT same mask shape with no differences and it’s just recolored GFX.

**Comment by LoveBodhi** [comment]
Maybe this is for original SMBX Asset?!

**Comment by LoveBodhi** [comment]
Seems still a palette change.

**Comment by 0lhi** [comment]
> What are you talking about and how do I do that?

Basically what you said, *keeping the SMAS SMB3 style outline-wise.* If you are only changing colors from the default assets, you should be good.

> When would the poll begin and end?

Once you open the thread. 2-3 weeks would be a reasonable time to keep it running, I think. But don't open it before you made the sprites and sent me to verify.

**Comment by vitzie629** [comment]
> But don't open it before you made the sprites and sent me to verify.

You mean you want me to make the sprites and I would send it to you for verification, right?

**Comment by 0lhi** [comment]
> You mean you want me to make the sprites and I would send it to you for verification, right?

Right. You can send them here or in the Moondust Server (ping me if you do).

**Comment by vitzie629** [comment]
> > You mean you want me to make the sprites and I would send it to you for verification, right?
> 
> Right. You can send them here or in the Moondust Server (ping me if you do).

Excellent thank you!

**Comment by vitzie629** [comment]
> in the Moondust Server (ping me if you do).

Ping me, what do you mean?

**Comment by ChristianSilvermoon** [comment]
> > the real reason I wanted to commit this idea is because Toad now has more of a modern look for full consistency with modern Nintendo games
> 
> For Toad, there was more of a reason to update because the old Ice & Fire Toad sprites were confusing. There was a vote on the [Wohlsoft Forums](https://wohlsoft.ru/forum/viewtopic.php?f=94&t=4289) that concluded the SMB2 Toad should be replaced with the Blue SMB3 Toad. The reason that hasn't happened yet is because there's no system for backward-compatibility yet, which would be needed for levels like the example from RMN.
> 
> Many months ago I have suggested a costume system that allows users to choose their preference, but to fallback to Vanilla sprites or any other costume chosen by compat.ini. I think, that would be good for this case, too. I can open a GitHub Issue on it these days.
> 
> Once that is done, there should be no issue to add your updated Sprites. If you'd like them to be the default ones, it would have to meet (at least) two requirements:
> 
>     * Shapes identical to the original (I can verify that if you send me)
> 
>     * The Community votes to replace them (probably here or on Wohlsoft)

I'm personally in favor of a costume system, as it allows players to select whichever style sprites they want.

**Comment by LoveBodhi** [comment]
It's a system of SMBX2.
Porting to TheXTech should be a good idea.

**Comment by vitzie629** [comment]
> It's a system of SMBX2. Porting to TheXTech should be a good idea.

I'd find it cool to have a costume system for TheXTech! How would you select a costume for the player on TheXTech in the future?

**Comment by ds-sloth** [comment]
This was a good discussion, but the issue itself isn't in-scope for the engine. An asset pack using these sprites could be created, and if we implement a costume system, an asset pack with both these sprites and the original SMBX 1.3 sprites could be created.
