### ISSUE TITLE
[ Feature Request ] - Optional Voice FX Support

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#263]
I feel like this one might be a bit decisive... as I know some really do not like the voices... *but* I grew up playing Super Mario All Stars on SNES, and then eventually the Super Mario Advance games on GBA. It had been really satisfying to have them portable and to have the voice clips... they added just a bit more personality to things.

I think it would be really neat to have support for having the same in TheXTech (though perhaps not enabled by default since I know some really don't like it... plus it would be extra assets to load which might not be so ideal on lower end platforms)

If such a feature were added, I think it'd be good if it was also made with #261 in mind, so that costumes could also change the voice clips (or disable them) since they may not be ideal for certain costumes, or certain costumes may have a more appropriate alternative sounds.

**Comment by vitzie629** [comment]
I would find the optional voice effects support for Mario, Luigi, Peach, Toad, and Link in SMBX to be very fascinating to me because it would give consistency with modern Nintendo games in SMBX!

**Comment by Wohlstand** [comment]
You may don't worry as Sound FX feature I made, will never work implocitly until episode maker will add it's usage explicitly 😉

**Comment by Wohlstand** [comment]
I guess, there are could be an additional set of sounds added into the same bank, and will be played when special hooks (intended to play voices) will be handled

**Comment by vitzie629** [comment]
> I guess, there are could be an additional set of sounds added into the same bank, and will be played when special hooks (intended to play voices) will be handled

An additional set of sounds like what?

**Comment by Wohlstand** [comment]
Just add them into sounds.ini, and internally, assign these new-added sounds with voice roles

**Comment by vitzie629** [comment]
> Just add them into sounds.ini, and internally, assign these new-added sounds with voice roles

Thank you! 😊

**Comment by LoveBodhi** [comment]
This is like NSMBWii!

**Comment by P-Star7** [comment]
Players:
- [ ] Getting a powerup
- [ ] Entering a level on the map
- [ ] Getting harmed
- [ ] Dying
- [ ] Grabbing a sprout
- [ ] Throwing an item
- [ ] Completing the level (Optional: "A crystal!" for SMB2 orb and "Here we go!" for SMB3 star)
- [ ] Getting a 1up
- [ ] Lava death sound ("Yow ow ow")
- [ ] Yoshi's death sound (when the player dies instantly [pit, lava, crushed] while riding Yoshi, or Yoshi falls into a pit or gets burnt in lava)

NPC's talking
- [ ] Toad
- [ ] Luigi
- [ ] Link
- [ ] Bob-Omb Buddy
- [ ] Mr. Saturn
- [ ] Princess Peach

Enemies' talking voices (when friendly)
- [ ] Goombas (and Galoomba)
- [ ] Koopas (Unknown if it should play for talking to shells)
- [ ] Piranha Plants
- [ ] Bob-Ombs
- [ ] Boos
- [ ] Thwomps
- [ ] Shy Guys
- [ ] Lakitus
- [ ] Bowser
- [ ] Birdo
- [ ] Mouser
- [ ] Wart
- [ ] Larry
- [ ] Ludwig
- [ ] Boom Boom
- [ ] Zoomer
- [ ] Mother Brain
- [ ] Mega Mole (reused from Monty Mole)
- [ ] Bully

Enemies' action voices
- [ ] Boo when it starts chasing the player
- [ ] Big Boo when it starts chasing the player
- [ ] Boo death
- [ ] Thwomp when it touches the ground
- [ ] Boom Boom's appearance sound
- [ ] Boom Boom's stomped sound
- [ ] Boom Boom's death sound
- [ ] Larry's appearance sound
- [ ] Larry's get stomped or thrown object (putting him in shell) sound
- [ ] Larry's death sound
- [ ] Ludwig's appearance sound
- [ ] Ludwig's get stomped sound
- [ ] Ludwig's death sound
- [ ] Bowser's appearance sound
- [ ] Bowser's getting hit by a thrown object sound
- [ ] Bowser's death sound
- [ ] Birdo's appearance sound
- [ ] Birdo's hurt sound
- [ ] Birdo's death sound
- [ ] Mouser's appearance sound
- [ ] Mouser's hurt sound
- [ ] Mouser's death sound
- [ ] Wart's appearance suond
- [ ] Wart's hurt sound
- [ ] Wart's death sound

Note: To use the SMA2 sounds for Larry/Ludwig's deaths, the player simply assigns Larry/Ludwig's death sounds to use the same file

**Comment by LoveBodhi** [comment]
Another one: Message Box appeared (HME)

**Comment by LoveBodhi** [comment]
We shouldn't add pre-load SFX's anymore, as it affects load time.

**Comment by ds-sloth** [comment]
Yes, sounds good to close to me, thanks for the note.
