### ISSUE TITLE
(Enhancement) More Sound Effects

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#265]
The option to add more sound effects to TheXTech, let's discuss which ones should be added and which ones will be annoying and should not be added. This does NOT include any voices which is put in a separate issue!

The Classic Games

Player's
- [ ] Raccoon/Tanooki flight sound from SMAS SMB3
- [ ] Slowed fall from Raccoon/Tanooki (like SML2 bunny ears noise)
- [ ] Maximum running speed (maybe only used for Raccoon/Tanooki?) from SMAS SMB3
- [x] Link's fireball (LTTP lantern sound, LTTP fire rod sound, or BS Zelda candle sound)
- [x] Link's iceball (LTTP ice rod shooting sound)
- [ ] Link's bomb throw (LTTP throwing sound)
- [ ] SMB2 increased health fanfare (used only when the SMB2 mushroom duplicates Mario/Luigi's powerup into the item box, normal mushroom sound will still be used if they are in forms 1 or 2)

Mounts & Items
- [ ] Purple Yoshi's ground pound noise (YI or SM64)
- [ ] Hurt inside the Koopa Clown Car (Bowser's hurt noise in SMW)
- [ ] Killed while inside the Koopa Clown Car (Bowser's death noise before he drops Princess Peach in SMW)
- [ ] Red Coin sound (YI or SM64)
- [ ] Blue Coin sound (SM64)
- [ ] Moon's 3up sound (SMW)
- [ ] Star collection sound (the sparkles from SM64 while Mario is falling, before the fanfare plays and "Here We Go")
- [ ] SMB3 Star collection fanfare (made different from Battle Game Won noise, used the fanfare from SM64 but without the voice "Here We Go")
- [ ] Propeller Block/Propeller Flamethrower's jump sound (NSMBWII)
- [ ] Swap Mushroom's noise (is it a unique noise in SMAS SMB3?)

Enemies
- [ ] Different noise for falling heavy block NPCs (SMB3) than Thwomp noise (Big Steely from SMW)
- [ ] Larry's inside the shell noise (SMAS SMB3)
- [ ] Ludwig gets stomped (SMW)
- [ ] Ludwig's death (SMW)
- [ ] Wart's death (SMAS SMB2)
- [ ] Bully gets knocked back or stomped (SM64)
- [ ] Bully touches lava (SM64)
- [ ] A Snifit shoots a bullet (YI)
- [ ] Big Boo's death (SMW, this is seen in the boss version of him in Donut Secret House, which the SMBX version is a hybrid of normal and boss versions)

Miscellaneous
- [ ] The sound for the Battle Game starting (SMAS SMB3)
- [ ] Using a Star Road warp (level-15) (ONLY when it is a warp to another location on the world map, instead of puts the player inside a level!)
- [ ] The sound when you do not have enough stars to enter a door or pipe (The scary music and Bowser's laugh from SM64)
- [ ] A SMB2 bombable block is destroyed (SMAS SMB2)
- [ ] The menu is cancelled out of on the title screen

The Modern Games (NSMB/Mario Maker)

Items and Mounts
- [ ] The player's fireball poofs against a wall (NSMB)
- [ ] All Red Coins or Dragon Coins in level are collected (Applause, NSMB)
- [ ] Yoshi shoots his three fireballs (NSMBWII)
- [ ] Springboard small jump (button not held)
- [ ] Springboard big jump (button held)

Enemies
- [ ] A Banzai Bill appears or is generated from a generator (NSMB)
- [ ] Hammer Bro and Bowser's unique hammer/bone throwing noise (NSMB)
- [ ] The Dry Bones reassembles (NSMB, which sounds like a backwards version of its crumbling noise)
- [ ] A Boo hides its face (NSMB)
- [ ] A Fishbone dies (NSMBWII)
- [ ] A Piranha Plant chomps (SM64 or NSMB)
- [ ] A big Piranha Plant chomps (SMB3 Giant and Misc. Tall Piranha Plants, NSMB)
- [ ] A Venus Fire Trap shoots a fireball (NSMB)
- [ ] A Bob-Omb is going to explode (NSMB)
- [ ] A SMW Lakitu throws its NPC (NSMB)
- [ ] A SMW Spiny egg turns into a Spiny (NSMB)
- [ ] A Koopaling enters their shell (NSMBWII)
- [ ] A Koopaling's shell is on the ground (NSMBWII)
- [ ] A Koopaling's shell hits the wall (can just reuse the old shell hits a wall sound, but this feature was introduced in modern games only)

Miscellaneous

- [ ] The player starts sliding on a slope (NSMB)
- [ ] A note block is hit on most occasions (NSMB2)
- [ ] The player is holding the button and gets a large boost from the note block (NSMB2)
- [ ] Unpause sound (NSMB)
- [ ] The player or an NPC splashes in the water [NSMB, Sonic]

Event-Only Sounds (Optional sounds that would be nice for level creation, not used automatically but only for events)
-Applause sound (can be used for collecting all coins on a layer, like P-Switch or timed red coins) (NSMB)
-Water rising sound (NSMB)
-Water falling sound (NSMB)
-Zelda secret sound (LTTP or OOT)
-SM64 star appearance sound
-SM64 1up appearance sound (possibly used by default for 1ups/3ups in blocks, sprouts, or eggs?)
-Bowser roars and laughs (SM64)
-Boo laugh (SM64, the small boo laugh and not Big Boo's laugh on carousel)

**Comment by 0lhi** [comment]
When discussing the Sound for the Ice Flower, it has been established that new sounds should be 16-bits to stay consistent with the general SNES feel of the game. So new additions would have to either be taken from a 16-bit source or made from scratch.

**Comment by LoveBodhi** [comment]
Mario Party 9's "Happening Space" addition can be added as well.

**Comment by LoveBodhi** [comment]
Modern Games SFX are for my Modern Games Sound Pack.

**Comment by LoveBodhi** [comment]
Menu Cancel should be added!

**Comment by LoveBodhi** [comment]
My one is:

- [ ] Menu Cancel

**Comment by P-Star7** [comment]
> My one is:
> 
> * [ ]  Menu Cancel
> * [ ]  Spring Board High Jump
> * [ ]  SM64 Sequential Jump (SMM NSMBU have sounds for Sequential Jump)

I will add the first two.

**Comment by P-Star7** [comment]
I added missing Lakitu and Spiny SFX.

**Comment by LoveBodhi** [comment]
I'm also suggesting new in-game editor specific sounds.

**Comment by LoveBodhi** [comment]
Link's Fireball & Iceball SFX is now completed.

**Comment by LoveBodhi** [comment]
New In-game Editor Specific:

- [ ] Select Element
- [ ] Show Pane
- [ ] Test Play
- [ ] Open File
- [ ] Save File
- [ ] Background Chosen
- [ ] Set Bound

**Comment by ds-sloth** [comment]
@LoveBodhi, I like the idea of revisiting the sound design for the editor. Let's try to re-use existing game SFX, because every new SFX increases the game load time and RAM requirements, as well as the asset pack's size.

Could you please suggest the best existing SFX for each of those editor features? (Some of them, we might not need a sound.) It might be good to make a new issue for this. Then, I can implement them, and you could review the results and see if they feel right to you.

**Comment by LoveBodhi** [comment]
> @LoveBodhi, I like the idea of revisiting the sound design for the editor. Let's try to re-use existing game SFX, because every new SFX increases the game load time and RAM requirements, as well as the asset pack's size.
> 
> Could you please suggest the best existing SFX for each of those editor features? (Some of them, we might not need a sound.) It might be good to make a new issue for this. Then, I can implement them, and you could review the results and see if they feel right to you.

If there's the case, it will be Mario Editor-like system instead of UniMaker-like system.

**Comment by LoveBodhi** [comment]
Also, some sound effects, such as "Fishbone Died", can be acheived via scripting.

**Comment by LoveBodhi** [comment]
also:

- [ ] POW Block hit (which doesn't share with Thwomp).

**Comment by ds-sloth** [comment]
I think this is no longer in scope for the project. Does that sound right to the rest of the development team?

**Comment by LoveBodhi** [comment]
So, does #462 make sense?

**Comment by LoveBodhi** [comment]
Does #462 , which is a part of Moondust Project feature, make sense?

**Comment by LoveBodhi** [comment]
Also, I thought that this should be a part of Asset Pack thing?
我想，这应该是TheXTech组件的一部分吧？

**Comment by LoveBodhi** [comment]
I have checked sounds that implemented in TheXTech.

**Comment by LoveBodhi** [comment]
The major problem is how do we make new SFX that supporting [my modern SFX Pack](https://wohlsoft.ru/forum/viewtopic.php?f=29&t=4239) (NOT basegame)...
