### ISSUE TITLE
[LunaDLL] Level Hud don't working

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#270]
**Describe the issue**

Well... this level must have a hud and... it don't appear, and glitches
**Example Case**

(https://www.mediafire.com/download/m1vmro8r19ia9c3/Forêt+bleue.zip)

Screenshot:

<img width="1440" alt="Captura de Pantalla 2022-01-31 a la(s) 23 23 54" src="https://user-images.githubusercontent.com/60852359/151904607-6abaa911-2fed-463b-a485-f19d8bf2ec93.png">

Original Screenshot (from the internet, can be found on [this post](https://www.supermariobrosx.org/forums/viewtopic.php?f=89&t=17207&p=248343&hilit=lunadll#p248343))

![](https://i59.servimg.com/u/f59/15/77/52/78/910.png)

**Comment by Wohlstand** [comment]
There are two bugs:
- the PlaceSprite at the script was given BEFORE the image got been actually loaded, doesn't look correct, will try to verify this more
- junk six zeroes "000000" got been printed additionally, gonna check out, why that happens...

**Comment by Wohlstand** [comment]
And the third case: transparent color for BMPs isn't implemented yet, so, quickly made it just now

**Comment by Wohlstand** [comment]
So, two bugs got solved, now I need to make sure that the order between "PlaceSprite" and "LoadImage" shouldn't matter

**Comment by Wohlstand** [comment]
I did another check, and older LunaDLL, and X2 has a similar behavior with a missing sprite:
![Снимок экрана от 2022-02-01 13-50-40](https://user-images.githubusercontent.com/6751442/151955403-7cf9a38a-5ece-4de1-8ca3-51e4b0e1f8bf.png)

So, to solve this, you should make the next change at `lunadll.txt`:
- find the next block:
```
// Charge l'image "HUD.bmp"
LoadImage,1,0xDC00FF,0,0,0,HUD.bmp
```
- Cut it
- Find the next block:
```
// Place l'image "HUD.bmp"
PlaceSprite,1,1,0,0,0,0
```
- Paste above it, so, make next:
```
// Charge l'image "HUD.bmp"
LoadImage,1,0xDC00FF,0,0,0,HUD.bmp

// Place l'image "HUD.bmp"
PlaceSprite,1,1,0,0,0,0
```
- voil'a:
![Снимок экрана от 2022-02-01 13-52-45](https://user-images.githubusercontent.com/6751442/151955703-8d82d682-aa1c-432a-ab9a-0d2b4d0252e4.png)

**Comment by Wohlstand** [comment]
Little note: X2 and early LunaLua kills the ability to draw sprites with transparency (I fixed that at my side few minutes ago):
![Снимок экрана от 2022-02-01 13-02-45](https://user-images.githubusercontent.com/6751442/151955798-1a1c1b69-2e0b-4253-8670-58d0d04839f3.png)

![Снимок экрана от 2022-02-01 13-49-26](https://user-images.githubusercontent.com/6751442/151955813-ab600786-667a-468b-916b-bda0eb7c3eee.png)

**Comment by Wohlstand** [comment]
So, I made the workaround, and thing now works as-is:

![Снимок экрана от 2022-02-01 14-18-55](https://user-images.githubusercontent.com/6751442/151959389-3631c240-3bcc-4cbf-8e28-236257ede377.png)

**Comment by Wohlstand** [comment]
btw, Castkart, nice level :fox_face: :+1:

**Comment by Wohlstand** [comment]
@M0REKZ, please download an updated build and try to play this level again. If it works fine, close the issue as solved.

**Comment by M0REKZ** [comment]
Downloaded the last build and tested, the Hud is working well now  ;)

Also, I see that there is a flash text that appears at the beginning of the level, it's kind of weird, but it doesn't affect the gameplay...

**Comment by Wohlstand** [comment]
> I see that there is a flash text that appears at the beginning of the level

That a warning message that tells player "LunaDLL v8+ is required", will stay shown persistently if you run this level at unsupported engine.

**Comment by M0REKZ** [comment]
Oh, ok, thanks :p
