### ISSUE TITLE
[Bug] Fairy player going through an upwards pipe creates softlock

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#284]
**Describe the issue**

If the player is a fairy while they go through an upwards pipe, they turn back into normal form, but they do not go through the pipe. They are stuck even if shadowstar is turned on, so they must be stuck in the warping state forever.

**Example Case**

[Fairy Link in the pipe.zip](https://github.com/Wohlstand/TheXTech/files/8035534/Fairy.Link.in.the.pipe.zip)
Level created by Namyrr for Yoshi and the Quest Through Time. I removed the irrelevant custom graphics and changed the spawn position. Best way to test this bug is by testing as Link.

**Recording**

![Scr_2022-02-09_13-06-43](https://user-images.githubusercontent.com/26371167/153273163-5389ced6-284c-48e4-951b-707fbba4064f.gif)

**Comment by Wohlstand** [comment]
Bug is fully vanilla
![Снимок экрана от 2022-02-10 00-20-05](https://user-images.githubusercontent.com/6751442/153291917-d9b42bf8-4c1d-4209-a390-b19c71caef46.png)

**Comment by Wohlstand** [comment]
(btw, didn't figured first to take the coin and beat miniboss :grin:)

**Comment by P-Star7** [comment]
Bug fixed in latest build.

**Comment by P-Star7** [comment]
Bug fixed in latest build.

**Comment by 0lhi** [comment]
Additional context:

1. Player cannot die while in Pipe.

![Scr_2022-09-15_02-16-26_(1)](https://user-images.githubusercontent.com/74732674/190876479-fbce69c7-809d-4d80-9d2e-529e35f42dc1.gif)

2. Power-Up Cheatcode can release Player:

![Scr_2022-09-15_02-22-16](https://user-images.githubusercontent.com/74732674/190876494-77389e93-dfbc-4d90-ab31-2a1d00059260.gif)

3. Actual Power-Up cannot release Player:

![Scr_2022-09-15_02-24-34](https://user-images.githubusercontent.com/74732674/190876517-87cc92f1-3ee0-4c47-abda-3871aa6ad59b.gif)
