### ISSUE TITLE
(Enhancement) Holding down arrow while swimming cancels vertical acceleration

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#286]
SMBX contains the feature from SMW where pressing up or down while swimming makes a tall or short swim. But one feature that it annoyingly does not contain is the ability to press down (no other button needed) to cancel the vertical acceleration in swimming. This makes the player stop ascending and after the short time when they decelerate, they start to descend again. The lack of this can be annoying in SMBX because the player might make a too tall swim. I can't make a video because I don't know how to show the controller buttons being pressed on my video, so please tell me how to show that or just playtest it yourself.

**Comment by ChristianSilvermoon** [comment]
> SMBX contains the feature from SMW where pressing up or down while swimming makes a tall or short swim. But one feature that it annoyingly does not contain is the ability to press down (no other button needed) to cancel the vertical acceleration in swimming. This makes the player stop ascending and after the short time when they decelerate, they start to descend again. The lack of this can be annoying in SMBX because the player might make a too tall swim. I can't make a video because I don't know how to show the controller buttons being pressed on my video, so please tell me how to show that or just playtest it yourself.

You should be able to enable the in-game control display by setting
`display-controllers` to `1` under the `[video]` section of `settings.ini`

or by running the game with the `--show-controls` command-line argument

**Comment by P-Star7** [comment]
> > SMBX contains the feature from SMW where pressing up or down while swimming makes a tall or short swim. But one feature that it annoyingly does not contain is the ability to press down (no other button needed) to cancel the vertical acceleration in swimming. This makes the player stop ascending and after the short time when they decelerate, they start to descend again. The lack of this can be annoying in SMBX because the player might make a too tall swim. I can't make a video because I don't know how to show the controller buttons being pressed on my video, so please tell me how to show that or just playtest it yourself.
> 
> You should be able to enable the in-game control display by setting `display-controllers` to `1` under the `[video]` section of `settings.ini`
> 
> or by running the game with the `--show-controls` command-line argument

Thanks, but I meant on the Super Mario World SNES emulation, not SMBX.

**Comment by ChristianSilvermoon** [comment]
> > > SMBX contains the feature from SMW where pressing up or down while swimming makes a tall or short swim. But one feature that it annoyingly does not contain is the ability to press down (no other button needed) to cancel the vertical acceleration in swimming. This makes the player stop ascending and after the short time when they decelerate, they start to descend again. The lack of this can be annoying in SMBX because the player might make a too tall swim. I can't make a video because I don't know how to show the controller buttons being pressed on my video, so please tell me how to show that or just playtest it yourself.
> > 
> > 
> > You should be able to enable the in-game control display by setting `display-controllers` to `1` under the `[video]` section of `settings.ini`
> > or by running the game with the `--show-controls` command-line argument
> 
> Thanks, but I meant on the Super Mario World SNES emulation, not SMBX.

Oh.. XD
My bad, I misunderstood X3

**Comment by P-Star7** [comment]
Another swimming enhancement idea: Allowing to run underwater. I'd rename this issue but I can't.

**Comment by ds-sloth** [comment]
These gameplay modifications seem out of scope for the engine now. They may or may not be possible to achieve using our future scripting API.
