### ISSUE TITLE
(Enhancement) 1.3.6 Fade-out/in enhancements

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#288]
Note: This is using the latest development build as a reference

- [ ] A fade-out of the player and lives component after a level is loaded, not just the black screen
- [ ] A fade-out and fade-in when exiting a level through a warp, and also when entering the world map when a warp has placed the player onto the world map

**Comment by LoveBodhi** [comment]
Customizable Fade should be added.

**Comment by Wohlstand** [comment]
This was added a while ago, forgot to close.
