### ISSUE TITLE
(Bug) Alt-Jump Tail Falling Animation Issue

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#290]
**Describe the issue**

When jumping and then holding down the Alt-Jump key, the Raccoon/Tanooki player's tail does not animate.

**Recording**

First jump: Held down jump key while descending.
Second jump: Held down alt-jump key while descending.
![Scr_2022-02-14_15-57-03](https://user-images.githubusercontent.com/26371167/154179811-8cae4826-e6e0-4f8a-81d1-396f83d84560.gif)

Vanilla bug.

**Comment by SkullGamer205** [comment]
As for me, it's normal that there is no animation with Alt-Jump.

**Comment by 0lhi** [comment]
This is definitely more of a peculiarity than a bug. Also, not sure if this needs fixing. In SMW, there is no distinction in the animation between pressing either Jump or Alt Jump and falling. To have a minor indicator of which button is pressed doesn't seem like a bad thing to me.

**Comment by P-Star7** [comment]
> This is definitely more of a peculiarity than a bug. Also, not sure if this needs fixing. In SMW, there is no distinction in the animation between pressing either Jump or Alt Jump and falling. To have a minor indicator of which button is pressed doesn't seem like a bad thing to me.

Why should there be an animation distinction if there is no gameplay distinction?

**Comment by 0lhi** [comment]
> Why should there be an animation distinction if there is no gameplay distinction?

Not saying that there *should* be one, but that it's not necessarily a bad thing if there *happens* to be one.

If we are strict, we can't say that "*there is no gameplay distinction*" cause that would be an absolute statement that requires a perfect understanding of the game. The only thing we can say for sure is that "_we don't know of a gameplay distinction_". If one will ever be discovered, for example in a Let's Play, we'll have a visual indicator of which button was used, even if the controller display is disabled.

**Comment by ds-sloth** [comment]
@0lhi, @Wohlstand, okay to close?

**Comment by Shadowblitz16** [comment]
@ds-sloth could this be reopened?
What exactly is the issue with making the alt jump hover animate the same as the jump hover?

**Comment by ds-sloth** [comment]
The problem is that in any case where it is not game-breaking to follow SMBX 1.3's behavior (including visuals) we do so.

**Comment by Shadowblitz16** [comment]
@ds-sloth Visuals are not game breaking though.

**Comment by ds-sloth** [comment]
Exactly. Since it's not game breaking, we keep it.
