### ISSUE TITLE
[Enhancement] Disable double press of escape to quit episode during a level

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#292]
This is so annoying when I do it on accident!

**Comment by ds-sloth** [comment]
@P-Star7 is this the current behavior? Was it the behavior on 1.3.5.x?

I want to understand because it's very possible that abstract controls either inadvertently introduced, or inadvertently fixed this.

**Comment by ds-sloth** [comment]
An update: this was a TheXTech-specific bug, and it was inadvertently fixed during the abstract controls update. It does not affect versions after v1.3.6.
