### ISSUE TITLE
[Vanilla peculiarity] Rotodisk behaviour when direction is set to "Random"

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#295]
The unusual behaviour of a Rotodisk set to "random" direction...

![Scr_2022-02-19_17-49-49](https://user-images.githubusercontent.com/26371167/154822994-a566c7ab-3bbc-471e-b40f-a7d36c7cfd26.gif)

[rotodisk set to random direction.zip](https://github.com/Wohlstand/TheXTech/files/8103183/rotodisk.set.to.random.direction.zip)

**Comment by 0lhi** [comment]
It seems that it will actually be random when putting it behind a Generator:

![Scr_2022-08-30_15-59-51](https://user-images.githubusercontent.com/74732674/187457602-b6db7b16-df1e-4e93-a2ed-f1d2dc0a23c1.gif)

**Comment by ds-sloth** [comment]
Thanks for this interesting find!
