### ISSUE TITLE
[Bug] Rotodisc effect rendered at wrong size compared to SMBX 1.3

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#296]
**Describe the issue**

The Rotodisc effect is being rendered at the wrong size when compared to vanilla SMBX.

**Example Case**

[rotodisk set to random direction.zip](https://github.com/Wohlstand/TheXTech/files/8103185/rotodisk.set.to.random.direction.zip)

**Recording**

![Scr_2022-02-19_17-49-49](https://user-images.githubusercontent.com/26371167/154823034-ec983f20-46e7-4eb3-9b85-9edb7021a046.gif)

**Comment by Wohlstand** [comment]
Should be fixed now:
![Scr_2022-06-04_04-42-06](https://user-images.githubusercontent.com/6751442/171971733-833b4d38-a607-4569-824d-15ba766a911e.gif)

**Comment by P-Star7** [comment]
Fixed in latest nightly
![Scr_2022-06-04_02-02-28](https://user-images.githubusercontent.com/26371167/171988766-2b055f0e-b6af-4ff5-ae02-780571cce19f.png)
