### ISSUE TITLE
[Vanilla Bug] Vine NPCs do not change graphics depending on NPC direction

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#298]
**Describe the issue**

Vine graphics do not work with "framestyle". Attempting to set a vine NPC to "Left" or "Right" always uses the "Left" graphics.

**Example Case**

[Vines (Don't work).zip](https://github.com/Wohlstand/TheXTech/files/8146185/Vines.Don.t.work.zip)

Thanks to Murphmario for making these graphics and bringing the bug to my attention.

**Comment by ds-sloth** [comment]
This wasn't possible in SMBX 1.3 because vines had specialized NPC Frame code. It will be possible to clone a vine NPC and give it a different NPC Frame method once we have the scripting API.
