### ISSUE TITLE
2-way locked door warp issue

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#300]
![Scr_2022-02-28_17-16-43](https://user-images.githubusercontent.com/37089530/155956669-5f6c8b11-e66a-492f-bc84-0d0053400719.gif)
[无标题 1.zip](https://github.com/Wohlstand/TheXTech/files/8152009/1.zip)

2nd side doesn't show lock BGO, after open in 2nd side, lock BGO of 1st side doesn't vanish.

Tested in Fairy Tale World asset 1.2.

**Comment by Wohlstand** [comment]
Reasonable to show the lock on both doors, and remove both locks from both doors (reasonable: it's the "same" door that got locked)

**Comment by Wohlstand** [comment]
Should work fine now:
![Scr_2022-06-04_05-18-30](https://user-images.githubusercontent.com/6751442/171974394-85521e75-9214-4e8d-8708-eb67c9228bee.gif)

Please verify the latest build "master"

**Comment by LoveBodhi** [comment]
Works now.
