### ISSUE TITLE
Pressing up and down disconnect the game input

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#309]
I press multiple times up and down at same time, and it make me lose on some levels, ¿is there a way to change the combination for disconnecting game input (maybe)?

**Comment by Wohlstand** [comment]
This is a known bug reported by @ChristianSilvermoon, and reason of it was the old debug code lefft by @ds-sloth to simulate the disconnection

**Comment by ds-sloth** [comment]
Should be fixed now, thanks for the report!

(PS: I didn't realize that writing "fixes" in the commit description would auto-close the issue.)

**Comment by ds-sloth** [comment]
@M0REKZ once the CI auto-build is done, would you mind checking that this is solved on your end? Should be a simple fix but I'd like confirmation before we close the issue.

**Comment by M0REKZ** [comment]
is solved, thanks
