### ISSUE TITLE
CMake error trying to build on aarch64

### ISSUE THREAD

**Issue by pancakers2001** [Wohlstand/TheXTech#31]
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!

**Comment by Wohlstand** [comment]
Sorry, missed up on the issue... 

Did you actually install the compiler toolchain? What distribution you do use? If you do cross-compiling, you should pass the toolchain file that points to the compiler toolchain you want to use for the cross-compilation. If you do local compilation on a thing like Raspberry Pi, you need to install the GCC / G++ / build-essential (on Ubuntu-like distros), etc.

**Comment by Wohlstand** [comment]
Closing this because of no response for a long time. The issue is most probably because of the proper cross-compilation toolchain file missing.
