### ISSUE TITLE
[Vanilla Bug] Falling from water as Raccoon/Tanooki

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#317]
**Describe the issue**

When you hold the button to slow your fall as you exit a water zone in raccoon or Tanooki form, the sprites used for descending are the swimming-idle sprites instead of the normal sprites.

**Example Case**

[water falling.zip](https://github.com/Wohlstand/TheXTech/files/8359798/water.falling.zip)

**Recording**

![Scr_2022-03-27_17-22-27](https://user-images.githubusercontent.com/26371167/160330713-6e2cecaa-2d9d-476e-b09d-b14d32d195d7.gif)

**Comment by ds-sloth** [comment]
Nice find!
