### ISSUE TITLE
No Sound is Played When a Leaf Emerges from a Block

### ISSUE THREAD

**Issue by DerpyBubblez** [Wohlstand/TheXTech#32]
If you hit a block that contains a raccoon leaf, no sound is played when it pops out.

**Comment by Wohlstand** [comment]
That is intended behavior, the sound for leaf punching was disabled to match the original SMB3 behavior when you punch a leaf from a block. The used sound is valid when object goes off block gradually, but leaf as Yoshi Eggs goes off the block immediately.

https://youtu.be/tuDFWalgwcY
