### ISSUE TITLE
Thwomp Laugh Sound from Mario Forever

### ISSUE THREAD

**Issue by vitzie629** [Wohlstand/TheXTech#322]
In SMBX, when a player hit a thwomp, it doesn't nothing just like SMB3 & SMW. However, how could would it be if a new sound for the thwomp exists which it would make a evil laugh just like Mario Forever by Buziol Games/Softendo as well as Mario Worker when the player touches the thwomp in TheXTech? If the thwomp's laugh was added, it should be a compat option which could be on or off. Do you think the thwomp's laugh sound from Mario Forever should be implemented for TheXTech?

**Comment by ds-sloth** [comment]
This is a cool idea, but it won't be implemented in the core engine. It may be possible to do something like it via scripting in the future.
