### ISSUE TITLE
Fix memory leak in input method type joystick destructor

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#326]
I'm not on my development account right now so taking these notes to remember later. Thanks to Wohlstand for finding this issue.

The severity of the memory leak is very low since it only affects the end-of-program deallocation of resources.

https://github.com/Wohlstand/TheXTech/blob/aa80c1b292a6e3234716e4d30901d9827e9fff28/src/control/joystick.cpp#L1435-L1442

Code above should be updated to include roughly the following:

```std::vector<int> open_joystick_ids;
for(const std::pair<const int, JoystickDevices*>& p : this->m_availableJoysticks)
    open_joystick_ids.push_back(p.first);

for(int joystick_id : open_joystick_ids)
    this->CloseJoystick(id);```

**Comment by ds-sloth** [comment]
Still needs a test, I have to remember not to use the word "fix"...

**Comment by ds-sloth** [comment]
@Wohlstand would you mind using your memory validation tool and perform the same actions (probably with gamecontroller) that showed the leak originally?

**Comment by Wohlstand** [comment]
I'll test the thing as soon as I power on my computer...

**Comment by Wohlstand** [comment]
Seems all fine now:
![изображение](https://user-images.githubusercontent.com/6751442/167291537-cfb22877-5073-40df-b2aa-6c3b36fb4a8e.png)
