### ISSUE TITLE
(New Editor) Unable to place more than one of the same type (ID) of sizable block in a level

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#329]
![Scr_2022-05-08_15-58-41](https://user-images.githubusercontent.com/37089530/167287152-68d67382-8c6a-4004-b162-4d7c4f72312e.gif)

This occurs in my side (Windows®10 x64).

**Comment by ds-sloth** [comment]
@Wohlstand I'm reproducing this on wine and `fEqual` returns `true` for two different locations. Can you verify whether your `fEqual` implementation might have any issues on Windows? Thanks!

(See in log, `Debug: Block was rejected at block at EC Loc (-199520.000000, -200448.000000), other block loc (-199776.000000, -200448.000000)`)

**Comment by ds-sloth** [comment]
Commit 02a3e25e69193540f19f126cbf28d001d65e1905 should fix this by avoiding the use of the function in the editor, but it will be interesting to see what is going on here.

@LoveBodhi, is your issue fixed?

**Comment by LoveBodhi** [comment]
Fixed now, thanks❤
