### ISSUE TITLE
NPC won't get a hit from carrying egg when it touches another egg

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#330]
This bug was been reported by **MLuna** (`MLuna#8988`) at Discord.

Original report:

> - TheXTech win64    1.3.6 [WIP]
> - The princess cliche (spiny farm level)
> If I keep running holding an egg the second enemy (after picking up a second egg) wont get killed, it'll kill me instead, like if the egg was not there.

When grabbing an egg item, and attempting to go forward to hit an NPC, when held egg touches another egg at the same time, NPC won't get any hit, and more, players can get hurt by the NPC.

**Example Case**
[Egg kill.lvlx.zip](https://github.com/Wohlstand/TheXTech/files/8646870/Egg.kill.lvlx.zip)

**Recording**
Original screenshot:
![изображение](https://user-images.githubusercontent.com/6751442/167293644-60cc86bf-6ba1-4d58-84a9-d36a2fe66f94.png)

![Scr_2022-05-08_13-25-39](https://user-images.githubusercontent.com/6751442/167293556-c4dc7aa6-414b-46ad-81b0-04fdad8d02e9.gif)

NPC among eggs is immune from held eggs:
![Scr_2022-05-08_13-31-31](https://user-images.githubusercontent.com/6751442/167293547-41ea6390-5682-4f6b-923d-91a36cfa39ec.gif)

**Vanilla Recording**

https://user-images.githubusercontent.com/6751442/167293465-868c0cee-75bc-4abb-aa70-9229a5d7f1f9.mp4

**Comment by ds-sloth** [comment]
Made a fix; a held NPC is now only canceled if it kills an NPC that it touches or is killed.

This also affects held veggies; I updated the test case to show that.

[Egg kill.lvlx.zip](https://github.com/Wohlstand/TheXTech/files/12196571/Egg.kill.lvlx.zip)

<img src="https://github.com/Wohlstand/TheXTech/assets/72112344/0ba80ed1-ff76-4c09-994b-ed92535a5821" width="400" height="300"> <img src="https://github.com/Wohlstand/TheXTech/assets/72112344/6d9b51fc-8a1b-41e5-9afa-b142cdb3760a" width="400" height="300">

**Comment by ds-sloth** [comment]
@Wohlstand, can you please check the commit and confirm everything looks good?

**Comment by Wohlstand** [comment]
The thing looks good. But, unfortunately, the user who reported, lost an account, so can't get a feedback...

**Comment by Wohlstand** [comment]
I'll just close this as the thing has been completed.
