### ISSUE TITLE
During Cutscenes, force Purple Yoshi's Ground Pound input to be "Down"

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#331]
**Describe the issue**

An Event triggering Jump+Down may not have the intended effect when on a Purple Yoshi.

**Example Case**

[PurpleCutscene.lvl.zip](https://github.com/Wohlstand/TheXTech/files/8683091/PurpleCutscene.lvl.zip)

**Recording**

Ground-Pound-By-Alt-Run

![Scr_2022-05-13_01-22-57](https://user-images.githubusercontent.com/74732674/168183886-82debdb0-ae60-4aca-8957-a51d45b24677.gif)

Ground-Pound-By-Down

![Scr_2022-05-13_01-27-19](https://user-images.githubusercontent.com/74732674/168183995-759faa18-118d-4784-b13b-16f275dbb33d.gif)

**Comment by ds-sloth** [comment]
Thanks for the report!

Please let me know if this fixes your issue. I don't have a test case available right now.

**Comment by 0lhi** [comment]
Works 👍

**Comment by ds-sloth** [comment]
Great! Thanks again for the report.
