### ISSUE TITLE
A New Option Behavior for the Poison Mushroom

### ISSUE THREAD

**Issue by vitzie629** [Wohlstand/TheXTech#332]
In SMBX, when a player touches a poison mushroom when big, fire, leaf, tanooki, hammer, or ice flower, the player turns to small form & when touching it while small, you lose a life. Mario Forever & Mario Worker on the other hand, no matter if you are small, big, or flower, you lose a life instantly! I feel that an option to change the behavior of the poison mushroom in TheXTech should have a Mario Forever option which no matter if you are small, big, fire, or other, you lose a life instantly just like in Mario Forever.

**Comment by Wohlstand** [comment]
Could be done as a custom NPC special value that you can set to define behavior.

**Comment by vitzie629** [comment]
> Could be done as a custom NPC special value that you can set to define behavior.

How would I know what to do?

**Comment by LoveBodhi** [comment]
This sorts like MrDoableA's Super Devil Mushroom.

**Comment by ds-sloth** [comment]
@vitzie629 Wohlstand was discussing implementation details -- we might use the NPC's new `special_data2` field in the LVLX format to specify this, and then we would internally use the NPC's `Special7` value to indicate if the mushroom was an instakill. This should be a pretty simple thing to implement.
@Wohlstand, if you do this, maybe you can update the `npc_special_data.h` code I added when implementing the editor and think about whether it is an easy format to work with? If not, I can refactor it.

**Comment by ds-sloth** [comment]
I don't think this is in scope for the project. An NPC like this can be created via scripting in the future.
