### ISSUE TITLE
Add the playthrough timer

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#34]
It's a feature suggested by speed-runners. It should count the timer spent on an episode (or a single level) playthrough.

There are two ideas of the timer (probably will just show both timers):
- Real-time counter, that will rely on the system clock
- Physics cycles counter, that will count the actual number of the physics cycles (treat each cycle as the 1/65 of the second)

Any ideas, suggestions, tips, notes are welcome :fox_face: :+1:

**Comment by Alucard648** [comment]
Physics cycles counter is better as a physics cycle is minimal game time unit which is independent from FPS.

**Comment by Wohlstand** [comment]
Added!
