### ISSUE TITLE
[Feature Request] - Enhance Path Apperance Cosmetics

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#356]
The way paths appear on the World Map currently is without animation and jarring.

The game has become a lot more polished and it would be nice to see the camera pan smoothly and paths fade in SMW-style as opposed to the current jumpy camera behavior with the path just suddenly being there.

Ideally, this should occur at the same speed so that the change is purely cosmetic.

**Comment by 0lhi** [comment]
38A Example: https://youtu.be/MTQZqztLHd4?t=1120

**Comment by ds-sloth** [comment]
Completed and present in the main branch since a267ac27abc806afe2384c2cfe786c7d600d7714, but please let me know if there are any tweaks you'd like to see here.

**Comment by ChristianSilvermoon** [comment]
Just tested and it seems all good to me ^^

**Comment by ds-sloth** [comment]
Awesome, thank you!
