### ISSUE TITLE
[Enhancement] - Improved Roto Disc Options

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#358]
Everybody's favorite Disco Waffles only seem to do their classical circular pattern from SMB3...

But in [Mario Forever (Video with specific time linked)](https://youtu.be/EfH9-X1w8K0?t=1949)

They jam out in some more... *interesting* patterns.

**Describe the solution you'd like**
I think it would be really neat if we could choose between:
* Circle (classic)
* Flower (Mario Forever)
* Lemniscate (Like this ∞)

**Comment by ds-sloth** [comment]
I think this should be done in the future via scripting, not as a part of the base engine. Can we close this issue?

**Comment by ChristianSilvermoon** [comment]
> I think this should be done in the future via scripting, not as a part of the base engine. Can we close this issue?

I think that'd be ideal ^^

**Comment by LoveBodhi** [comment]
Seems a part of SMBX-38A feature?
