### ISSUE TITLE
Click by right mouse button at character selection menu causes weird behaviour

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#361]
Recently, I found a weird case: when you attempt to go back in menu using mouse, the game will start (the HUB-based episode) with a nobody instead of character, and this will repeat infinitely, and lives will decrease every loop:

![Scr_2022-07-28_16-35-29](https://user-images.githubusercontent.com/6751442/181518886-ac8dcb08-8e21-4e77-9070-79be9fb89f67.gif)

**Comment by 0lhi** [comment]
Ah, I kinda ended up forgetting about it, but a few days ago the same thing happened to me.

**Comment by ds-sloth** [comment]
Please take a look -- this should have been fixed as of 6dd4ad56e425eacc3f790f4fe755a417a699388b.

**Comment by 0lhi** [comment]
Am confirming, it no longer occurs on my newest master build.

**Comment by ds-sloth** [comment]
Great! It was a pretty simple fix.
