### ISSUE TITLE
[Enhancement] - Camera Improvements for Lower Resolutions

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#362]
For lower Resolutions, I think it's important to be able to pan the camera.

Many platformers allow panning up/down while holding up or down.

Right now the current behavior is to always center the player, but this leads to a lot of jumping to platforms you can't necessarily see ahead of time.

I think it would be good if holding still and up or down (for a period of roughly 500+ ms) would change how the camera (whilst playing `sound-13`) follows the player, centering them at the top or bottom, like so:

![image](https://user-images.githubusercontent.com/30162808/181803948-e203837a-4fac-43f3-b08f-0a7b80ec3f34.png)

Someone also suggested added a new a dedicated camera control button to enable panning up/down/left/right
While I do think this would be a good thing, I think it's important that the feature not be locked behind any additional inputs, so that devices with fewer buttons can still take advantage of camera panning (even if only vertical camera panning)

Some option to keep the player more to the left or the right of the screen depending on which direction they're facing and moving may also be ideal. For example, if they start moving left, keep them 3/4s of the way to the right side of the screen instead of centered.

So a sort of **Dynamic Horizontal Camera** option, that will gradually change how the camera horizontally centers the player based on movement and direction, and a **Manual Vertical Camera** option that changes how the camera vertically centers on the player based on holding up, or down while not moving for a brief period of time.

**Comment by ds-sloth** [comment]
How does this sort of thing fit your vision? I'm adding it as a default-off config option (`[effects] -> small-screen-camera-features = 1`) on the multires branch for now so you can feel free to test it out.

<img src="https://user-images.githubusercontent.com/72112344/181861369-d7bac142-0c3c-4a51-9e24-8efe37150194.gif" width="240" height="160">

**Comment by ChristianSilvermoon** [comment]
My thoughts are:

## Vertical Panning
I strongly feel that the vertical panning should work differently. While holding completely still and not pressing other inputs, holding **up** or **down** for a few moments should pan the camera the respective direction to a specific offset and *lock it to that new offset*.

If you need to mostly watch out below you for some speedy platforming, it's going to be essential that you don't have to manage the vertical camera position and your movement at the same time.

## Horizontal Panning
![Scr_2022-07-29_17-17-07](https://user-images.githubusercontent.com/30162808/181863089-87ebb3e8-b88f-49b3-ae43-8f764fe22da9.gif)

It feels good! Although it probably should not allow the player to hug the edge of the screen x3

I'd suggest the player should be **at most** this far to either side
![image](https://user-images.githubusercontent.com/30162808/181863155-ab20f19b-7baf-4cee-bc50-18eba9d3ad52.png)

I'd also really recommend that when the player comes to a stop, wait a little bit before re-centering the camera to be a little less disorientating.

Otherwise, the Horizontal Camera movement feels **perfect**

**Comment by ChristianSilvermoon** [comment]
Suggested icon to display (possibly in lower right, SM64 style) to indicate the camera is locked vertically 
![image](https://user-images.githubusercontent.com/30162808/181870863-cafaecd9-3a4c-412f-9eec-0f8648fb981c.png)

**Comment by ChristianSilvermoon** [comment]
Okay, adding *expanded* icons...
![image](https://user-images.githubusercontent.com/30162808/182015696-b749a3ee-3680-4571-8d52-73e0c9766bb6.png)

* Red Camera + Up Arrow = Camera is locked pointing up
* Red Camera + Down Arrow = Camera is locked pointing down
* Blue Camera = Camera Controls Available; not locked

A visual indicator in the lower right corner I think would be a very good thing.

**Comment by ds-sloth** [comment]
Hi @ChristianSilvermoon, is the current implementation in the multires branch to your liking? If so, we can close this issue for now.

**Comment by ChristianSilvermoon** [comment]
> Hi @ChristianSilvermoon, is the current implementation in the multires branch to your liking? If so, we can close this issue for now.

Sorry, about the delay, just tested off of `wip-multires-backport` @ ba58f1a3

I would say it feels good. The only thing I can think of is that you cannot pan the locked camera down while jumping, but you can pan it up while jumping. While I don't think this is an issue personally, I could see some people finding it to be inconsistent.

But I think it's good enough as is in its current implementation.

**Comment by ds-sloth** [comment]
I see your point about consistency. So, maybe re-enable the camera panning during duck jumps? Or disable it during all jumps?

**Comment by ChristianSilvermoon** [comment]
> I see your point about consistency. So, maybe re-enable the camera panning during duck jumps? Or disable it during all jumps?

Maybe all jumps for consistency's sake... worst case scenario with a setting to enable/disable, but I know you want to avoid adding gajillions of settings

**Comment by ds-sloth** [comment]
I see your point about consistency. So, maybe re-enable the camera panning during duck jumps? Or disable it during all jumps?

**Comment by ChristianSilvermoon** [comment]
> I see your point about consistency. So, maybe re-enable the camera panning during duck jumps? Or disable it during all jumps?

you've got a copy/paste of two days ago there... did you mean to send something different? :thinking:

**Comment by ChristianSilvermoon** [comment]
Tested off commit 162f6614

The game appears to warn of invisible friendly NPCs
![Scr_2022-09-09_17-39-54](https://user-images.githubusercontent.com/30162808/189461935-60136a9e-9607-495c-ba7e-ebbceaf09b56.gif)

**Comment by ds-sloth** [comment]
@ChristianSilvermoon I think this is fully implemented. Do you think it's done too?

**Comment by ChristianSilvermoon** [comment]
> @ChristianSilvermoon I think this is fully implemented. Do you think it's done too?

I would say yes, between the camera panning, and the NPC Indicator low resolution play is as solid as it can be in my opinion :smile:

**Comment by ds-sloth** [comment]
Great! Then I think this issue can be closed as we await #328 to merge.
