### ISSUE TITLE
Fix the "Run" touch button behaviour when "hold run" mode is active

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#363]
Touch-screen actions for "hold run" mode should always work on Press with a cost of one frame, never for release, as this behaviour confuses and makes gameplay messed up.

**Comment by LoveBodhi** [comment]
I tested it, no longer needs to release "B" button.

**Comment by Wohlstand** [comment]
Okay, at least, this is enough to close the issue :)
