### ISSUE TITLE
3DS platform support

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#366]
After the implementation of multi-res support and abstract controls, it needs to make the 3DS port again.

For my side, I need to make the tweaking the audio support to make sure the thing would work here.

**Comment by ds-sloth** [comment]
For the audio, I think we could try to set up an XAudio system like the XRender, etc. This would simplify making ports to any other targets that use a hardware mixer. Does that seem like a good plan to you?

**Comment by ds-sloth** [comment]
I'm starting work on this while awaiting the multires merge. For audio, I am currently using the old system from the `devel` branch. Here, the MixerX functions that are used are all declared explicitly in an internal header, and certain calls are declared using `MixPlatform_*` functions. Then the MixerX targets would link the MixerX implementations, and the hardware mixer targets would link their own internal implementations.

For the `SDL_*` generic calls (like `SDL_strcmp`), I would like to replace them with calls in the `XStd` namespace, which would alias the SDL functions on SDL2 builds, and alias POSIX functions on POSIX systems without SDL2.

Alternatively, we could take the approach above and include a header that includes the standard SDL headers on SDL platforms, and has lines like `#define SDL_strstr strstr` on other platforms.

How would you like me to proceed on these two issues?

**Comment by ds-sloth** [comment]
Done with #424 !
