### ISSUE TITLE
In some case, level is not enterable on world map

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#371]
The bug reported by `ReintendoO` at Discord.

After starting the episode "The Lost levels (Remake)", and entering the world map after the intro, the player won't enter World 1-1 (nothings happen on the "jump" button press). However, when saving and quitting the episode and entering the world map again, that level gets successfully entered normally.

**Example Case**

The episode where bug happens: https://smbxarchive.wohlsoft.ru/SMBX%202/The%20Lost%20Levels%20%28Remake%29%20by%20Yung%20Gotenks.zip
Note: The episode was made for SMBX2 Beta 3, but works on TheXTech normally except of absence starman NPC.

**Recording**

https://user-images.githubusercontent.com/6751442/182928840-14b5d9cf-d12e-4d74-9f5a-b07fb0315d52.mp4

**Vanilla Recording**
The level gets normally entered on vanilla SMBX 1.3 and on TheXTech 1.3.5.3 and older.

**Additional context**

This bug gets reproduced on the 1.3.6-dev version (latest state of `master`).

**Comment by ds-sloth** [comment]
A proper solution to this bug should also resolve a few other issues including not unloading levels' unique custom GFX when returning to the world map.

**Comment by 0lhi** [comment]
> including not unloading levels' unique custom GFX when returning to the world map.

Hasn't that been fixed already? #141

**Comment by ds-sloth** [comment]
Oh, great point. I didn’t realize we had a partial solution already. We would just need to correct the g_dirEpisode and g_dirCustom paths in the same place we have the comment “Restore the previously preserved world map paths”. Should be a straightforward fix.

**Comment by Wohlstand** [comment]
I confirm the bug has been fixed, now wait for when **Reintendo** will test on his end.

**Comment by Wohlstand** [comment]
Okay, the fix has been confirmed!
