### ISSUE TITLE
Any chance to add frog suit?

### ISSUE THREAD

**Issue by Yave-Yu** [Wohlstand/TheXTech#374]
I think it's nice to have frog suit֍
Any character add 8th form.

**Comment by LoveBodhi** [comment]
Also: 

- Super Crown
- Penguin Suit
- Bee Shroom
- Carrot
- Propeller
- Bomb Shroom
- Super Flower
- etc...

**Comment by ChristianSilvermoon** [comment]
> I think it's nice to have frog suit֍ Any character add 8th form.

The discussion #239 Maybe relevant as it includes the potential of including the Frog Suit, Propeller Mushroom, and Penguin Suit

**Comment by ds-sloth** [comment]
Thanks for the suggestions. The SMBX-38A powerups aren't at the top of our priority list but they are in the long-term roadmap. We're tracking them in #379.

We are also planning the ability to implement powerups by scripting.
