### ISSUE TITLE
Secondary Input Options

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#38]
Hi! We already talked about this, so I'd like to add it to the idea-pool.

![SMBXInputs](https://i.imgur.com/3p3ag3h.png)

It would allow Controller users to use both, D-Pad and Analog-Stick at once, without forcing the option on them.

And it would allow Keyboard users to have identical controls as Vanilla SMBX (which currently isn't possible, as TheXTech differentiates between *Left Shift* and *Right Shift*).

**Comment by Wohlstand** [comment]
As we discussed with @0lhi via XMPP, this feature is not needed for the recent future as it looks like a workaround to the goal that got solved by the recent gamepads support upgrade.
