### ISSUE TITLE
Idea: Optional Discord Rich Presence

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#39]
I think it'd be pretty cool to have Discord Rich Presence support :P

Perhaps showing: 
Episode Title (or Title Screen / Battle)
Level Title (or filename if blank)

**Comment by Wohlstand** [comment]
That will need to use the GameSDK, would check for some

**Comment by Wohlstand** [comment]
Okay, I was found that I can to implement some by using this:
https://github.com/discord/discord-rpc

so, I will need to add this and rapidjson libraries into dependencies to get this thing being supported.

**Comment by ChristianSilvermoon** [comment]
> Okay, I was found that I can to implement some by using this:
> https://github.com/discord/discord-rpc
> 
> so, I will need to add this and rapidjson libraries into dependencies to get this thing being supported.

The README implies it's depreciated, is that alright?

**Comment by Wohlstand** [comment]
I had to test the example, and it worked, but if deprecated, maybe there is some another thing?

**Comment by Wohlstand** [comment]
Has been implemented: #523
