### ISSUE TITLE
A glitch is dont working

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#4]
(lel, fix for make a glitch)

i cant make work this glitch on thexthec: https://www.supermariobrosx.org/forums/viewtopic.php?f=69&t=2691

i used pge editor for making a level for this, on original smbx engine it work

**Comment by Wohlstand** [comment]
I did a little look, and here is a difference: this glitch happens in only files are saved by SMBX itself, and glitch never happens when level was saved by PGE Editor. I may guess it's because of NPCs ordering :thinking: 
EDIT: No, it's not matters. I found an another factor: you should place a ballast AFTER placing a key. So, you must remove a ballast and place it again to cause it being in array after key.

**Comment by Wohlstand** [comment]
A video: https://www.youtube.com/watch?v=eR0VmbTIec0
A level: http://wohlsoft.ru/docs/Levels/SMBX-Experiments/pipe-glitch.7z

**Comment by Wohlstand** [comment]
Please try it again and tell me, does this working?

**Comment by M0REKZ** [comment]
it works, (but with the 3up moon dont work for some reason)

**Comment by Wohlstand** [comment]
Don't forget about an order! Place that 3up-moon after key!

**Comment by Wohlstand** [comment]
3up moon at me works:
![Scr_2020-04-12_03-03-06](https://user-images.githubusercontent.com/6751442/79057423-34a7a100-7c6a-11ea-9030-de5ed6acf8e8.gif)

**Comment by M0REKZ** [comment]
i test on my .lvl with the moon (that i put after the key) and it not worked

**Comment by Wohlstand** [comment]
> edit: no, forget it, it's a problem of my level

You can do next:
- remove that 3up moon
- place it from scratch as a new item

**Comment by M0REKZ** [comment]
i tried it before, but now it worked



(by the way, this glitch also works with shells or, as shown eclipsed here, yoshi: https://www.youtube.com/watch?v=WEmyi6ea6EQ )

**Comment by Wohlstand** [comment]
So, I'll close this issue.

> (by the way, this glitch also works with shells or, as shown eclipsed here, yoshi: https://www.youtube.com/watch?v=WEmyi6ea6EQ )

I did check of what is here... lol! :joy_cat:
