### ISSUE TITLE
Spinning into a Life Block on a Top-Only Block and a Sizable Click causes clip downwards

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#401]
**Describe the issue**

Spinning into a Block containing a 1Up makes player fall down when standing on a sizable block and the 1Up-Block lies on a Top-Only-Block.

**Example Case**

To be added by @Wohlstand 

**Recording**

Bug happens at:

* TheXTech 1.3.4+
* TheXTech Mode 2
* SMBX2

![Scr_2022-08-28_22-11-36](https://user-images.githubusercontent.com/74732674/187092898-730a23d3-3096-4d50-a908-619896433390.gif)

**Vanilla Recording**

The Bug doesn't happen at:

* SMBX 1.3
* TheXTech Mode 3
* TheXTech 1.3.3 or lower

![Scr_2022-08-28_22-12-10](https://user-images.githubusercontent.com/74732674/187092899-5e167860-bc7e-4573-9da5-0343be50a5a6.gif)

**Additional context**

First reported by @ds-sloth - discovered in Yoshi's Archipelagos "Colorful Playground".

**Comment by Wohlstand** [comment]
Some of my demos: [Death spin 3 demos.zip](https://github.com/Wohlstand/TheXTech/files/9440421/Death.spin.3.demos.zip)

**Comment by Wohlstand** [comment]
Just now I made the fix for this bug, and seems it helps:
https://github.com/Wohlstand/TheXTech/commit/e004f4c96f1553fdcdc312a654969366882388b9

**Comment by 0lhi** [comment]
Fixed in all Modes!

![Scr_2022-08-29_00-32-42](https://user-images.githubusercontent.com/74732674/187097249-833d0f32-7cec-4383-a728-109b56974a67.gif)

**Comment by Wohlstand** [comment]
Perfekto! :)
