### ISSUE TITLE
Backport the Moondust Engine's font engine to provide the multi-language and the unicode support

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#41]
Since the foundation, the game uses the old vanilla font engine made by Redigit that can print ASCII only. This adds a lot of limitations and strongly prevents the translation of the game into other languages. Together with that, as a separate task, develop the episode translation system to allow non-damage translation of episodes (by making the separate translation files in addition to existing levels and world maps).

**Comment by LoveBodhi** [comment]
I found some Free Software Font files (e.g. Source Han Series, Maoken TangYuanTi, etc.), maybe there'll be used? or like SMBX-38A?

**Comment by ds-sloth** [comment]
This can get pretty close to the hardware on homebrew targets. I propose that for this we first standardize: all fonts are 8 internal pixels and 16 render pixels tall, and all strings are in UTF-8.

Then, would you be willing to follow the following font interface? It would offer at least the following functions (each should have versions for `const std::string& str`, `const char* str`, and `const char* str, size_t n`, which would likely be the implementation):
`int Font::printWidth(const std::string& str);
void Font::printLocaleAlign(const std::string& str, int y, int left, int right);
void Font::printMultilineLocaleAlign(const std::string& str, int y, int left, int right);
void Font::printLeftAlign(const std::string& str, int y, int left);
void Font::printRightAlign(const std::string& str, int y, int right);
void Font::printCenterAlign(const std::string& str, int y, int right);
void Font::printScreenCenter(const std::string& str, int y);`

Then you could write your SuperPrint / freetype implementation and I could write a bcfnt implementation that is fast on 3DS?

**Comment by Wohlstand** [comment]
> Then you could write your SuperPrint / freetype implementation and I could write a bcfnt implementation that is fast on 3DS?

Speaking about `bcfnt`: you could inherit the base font class at my font engine, and use it instead of FreeType's one. However, if FreeType itself will work on 3DS (in a condition when you implement the raw texture loading function at 3DS renderer), then it should be consistent with other platforms.
