### ISSUE TITLE
Additional LTTP Ice-rod FX

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#410]
[lttp icerod.zip](https://github.com/Wohlstand/TheXTech/files/9540344/lttp.icerod.zip)

*Recorded by me via Mesen-SX*

For Link's Ice Shooting. It's meant to be separated with 'zelda-fire'.

**Comment by Wohlstand** [comment]
Good idea, I'll take it.

**Comment by Wohlstand** [comment]
Done:
https://user-images.githubusercontent.com/6751442/189501600-cebd20fa-ecb5-4b85-899c-370f449239d9.mp4
Soon I'll add this into assets.
