### ISSUE TITLE
The Infinite 1-up Trick from SMB1/SMB2J

### ISSUE THREAD

**Issue by vitzie629** [Wohlstand/TheXTech#413]
While SMB1/SMB2J provides the 1-up trick by jumping on the Koopa Troopa's shell multiple times as you can see in the video below...
https://user-images.githubusercontent.com/90484844/190289190-f87891f9-57ee-43a6-bc19-65521741c2e9.mp4
it's not really possible to do it in SMBX as you can see in this animation below.
![Scr_2022-09-14_21-06-49](https://user-images.githubusercontent.com/90484844/190289542-1b80e956-488a-485e-86c7-6c1aeb6d3f64.gif)
I would like to let the infinite 1-up trick in SMBX to be possible & it would be cool to have it!

**Comment by Alucard648** [comment]
I think, it`s fine as is. Say no to cheap tricks. Not a bug.

**Comment by ds-sloth** [comment]
TheXTech is a faithful port of the SMBX64 engine, and our logic is not based on any other games. This issue raises an interesting idea, but it's outside of the scope of the project.

**Comment by LoveBodhi** [comment]
Same mechanic of SMB Wonder; Maybe do this by LUA script system?
