### ISSUE TITLE
Abstract Controls: Give P2's Pause the Green Arrow

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#415]
Right now there is no visual distinction between Player 1's Pause and Player 2's Pause.

![Scr_2022-09-17_17-57-15](https://user-images.githubusercontent.com/74732674/190865685-6723bd08-f3d2-489f-b95a-b85ccae197de.gif)

Additionally, Player 2's Controller doesn't appear on the Map, even though it can cause an Action here (Character Change).

**Comment by 0lhi** [comment]
Neutral ESCAPE-Pause should have grey arrow:

![Scr_2023-08-19_18-55-05](https://github.com/Wohlstand/TheXTech/assets/74732674/c4ce38eb-cf6b-473b-a2ee-aaac910de85c)

In DM we spoke about replacing the "P2 Disconnected" Message with the Input Display Controller containing a "searching" visual. Can you do that?

![Scr_2023-08-19_18-54-19](https://github.com/Wohlstand/TheXTech/assets/74732674/9f3031a8-15cf-4a0c-9a80-7cc2774ba03a)

**Comment by ds-sloth** [comment]
> Neutral ESCAPE-Pause should have grey arrow:

I think you don't have `graphics/ui/PCursor.png`. I previously rotated one of the grey up/down arrows from the world select menu as the fallback, but that messed up Yingchun's assets, so I switched to using the P1 selector as the fallback. In any case, we need to make sure that `graphics/ui/PCursor.png` is included in the main asset packs.

> In DM we spoke about replacing the "P2 Disconnected" Message with the Input Display Controller containing a "searching" visual. Can you do that?

I still like this idea but it belongs in a different issue.

**Comment by 0lhi** [comment]
> I switched to using the P1 selector as the fallback.

Is P1 in grayscale not an option?

> I still like this idea but it belongs in a different issue.

Done: #587

**Comment by ds-sloth** [comment]
> Is P1 in grayscale not an option?

That would require a custom shader, not easy to do in SDL.

But, I think I resolved this issue by a "trick" of making there be no more distinction between P1 and P2 pauses in modern gameplay.

The only player-specific pauses are the Chats from NPCs.

**Comment by 0lhi** [comment]
Doesn't work with Testing Pause:

![Scr_2023-08-19_22-47-49](https://github.com/Wohlstand/TheXTech/assets/74732674/6a3792d5-a225-4724-8c7c-1469cd096121)
