### ISSUE TITLE
[Android]: Level files won't be opened from some file managers

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#417]
Attempt to load a level file using some of the file managers on Android (for example, "CX Explorer"), level won't open, because there is a wrong or abnormal absolute path passed.

![изображение](https://user-images.githubusercontent.com/6751442/190893436-5d05da7c-7d67-45ae-b397-eab4736a3300.png)

- To resolve this, the passed absolute path must be converted into a real and valid file path.
- The level gets opened correctly when using Total Commander or ES Explorer.

**Comment by Wohlstand** [comment]
I fixed this thing just now, files now gets open properly from various file managers, including CX Explorer (I downloaded and installed it to test out the work).

**Comment by Wohlstand** [comment]
@SkullGamer205, please test this as soon as you can. Just a reminder.

**Comment by SkullGamer205** [comment]
CX Explorer - Good
My Files - program picker menu don't shown, shown "play store" menu
Total Commander - Good

**Comment by Wohlstand** [comment]
> My Files - program picker menu don't shown, shown "play store" menu

At me, on Samsung, the "My files" thing does open levels/worlds by engine, BUT, it can't open file directly: instead it gives data only, that can be written to internal store only, and therefore, custom resources are inacessible (so, warning will pop up). What device you do use?

**Comment by Wohlstand** [comment]
I guess, the main problem has been solved. Other things are different issues because of Samsung's "My Files" weirdness regarding to content of Intent contexts, etc.
