### ISSUE TITLE
Background Rendering Bug on Section Size Change

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#42]
![TheXTech - BKG Render Bug](https://user-images.githubusercontent.com/30162808/108460033-005f2280-7235-11eb-9902-4d5a2c7e7c5a.gif)

So, it looks like the background isn't properly redrawn if the section size changes vertically. I've only tested this with this particular background, but I'd done a horizontal resize in another location previously and didn't have any trouble.

This was tested with the binary for Ubuntu 20.04 from release [v.1.3.4](https://github.com/Wohlstand/TheXTech/releases/tag/v.1.3.4)

**Comment by Wohlstand** [comment]
This bug is pretty vanilla: you do expansion of the section down, which is lower than the actual bottom of the section. The workaround is probably needed here, probably just fill with a black.

**Comment by ChristianSilvermoon** [comment]
I figured it was a Vanilla Bug, yeah, since the game uses more-or-less identical logic :P

I'll probably fill the background for now... if the bug were fixed, would the background tile? Does it tile normally?

**Comment by Wohlstand** [comment]
>  would the background tile?

Depending on the background itself, otherwise, the look will be a bit messy because of a seam :thinking:

**Comment by Alucard648** [comment]
> > would the background tile?
> 
> Depending on the background itself, otherwise, the look will be a bit messy because of a seam 🤔

What about repeating bottom pixels of background with gradient fading to black?

**Comment by ChristianSilvermoon** [comment]
@Alucard648 I really, really *like* that suggestion. That'd work pretty well, in my opinion if possible.

**Comment by ChristianSilvermoon** [comment]
![image](https://user-images.githubusercontent.com/30162808/108518188-83a86480-7285-11eb-8eaa-19a849b7c160.png)

Update: The issue also occurs when resizing sections past their original size horizontally and up too :(

Would definitely like to see this fixed. The only work around I could think of are covering up the background in those areas like suggested, or starting with a large section and shrinking it right away through an event and then making it bigger after that maybe.

If I had to hazard a guess the way the background drawing is currently handled would lead to some odd looking results if the game suddenly displayed as if the section had been larger the whole time (IE background image jumping).

But I'd also have to hazard a guess that there must be some logical way of dealing with the background, since the game appears to decide where to draw it based on the initial section size. I honestly have no idea. o.O

**Comment by Wohlstand** [comment]
BTW, can you include demo levels here? To let me easier verify the stuff? I'll try some once I'll have a free time (probably tomorrow)

**Comment by ChristianSilvermoon** [comment]
Sure thing!

[Offending Levels.zip](https://github.com/Wohlstand/TheXTech/files/6010949/Offending.Levels.zip)
* **Boss Test**
* * I was experimenting with a boss fight, much like in Super Mario Bros 3 where the screen scrolls and locks into place
* * To trigger, just progress right through the (very short) level
* **Secret Aquarium**
* * A throwback to classic Mario Bros as well as the Secret Aquarium from Super Mario 64
* * To trigger, collect the 5 blue coins at the start

**Comment by Alucard648** [comment]
Here is another synthetic test level for testing section resizing.

**Comment by Wohlstand** [comment]
Okay, I do think to resume the work on this. I think I can make the next:
- for left-right expansions, I can safely draw the background image until it uses the "fit" alignment algorithm (the example - SMB2 underground)
- for the down and up expansions, I will draw the black overlay that will fill the missing part of the background (counting the big pictures which have a bigger height than the original section and have been aligned to the top, when aligned to the bottom, then draw an overlay always)
- I also will need to backport my screen aligner fron the PGE Engine when section is smaller than the screen

**Comment by Wohlstand** [comment]
I mean the next:

* The section itself:
![Снимок экрана от 2021-04-19 13-18-17](https://user-images.githubusercontent.com/6751442/115220898-c5cd1580-a111-11eb-8b5d-67358a5f2cce.png)

* How SMBX 1.3 / SMBX 2 / TheXTech draws it:
![Снимок экрана от 2021-04-19 13-18-23](https://user-images.githubusercontent.com/6751442/115220894-c5347f00-a111-11eb-93cf-a42e05e5222d.png)

* How PGE Engine draws it:
![Снимок экрана от 2021-04-19 13-18-32](https://user-images.githubusercontent.com/6751442/115220891-c49be880-a111-11eb-8c4b-02257d807e3c.png)

* **Bonus**: how SMBX-38A draws it:
![Снимок экрана от 2021-04-19 13-20-23](https://user-images.githubusercontent.com/6751442/115221161-0dec3800-a112-11eb-9ed3-9871a99172cf.png)

it simply automatically expands the section around :grin:

**Comment by ds-sloth** [comment]
I've tested and confirmed that #328 fixes this.
