### ISSUE TITLE
Joystick controller profiles gets wrongly assigned between different gamepads

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#420]
When I have multiple gamepads plugged in and when I start the game from the scratch (settings/controls.ini removed), and when I attempt to activate one of the gamepads, it gets its new profile. When I restart the game and I attempt to press buttons on two other gamepads (I have three different gamepads), they get to share the same profile! (UUID of each gamepad wasn't actually saved into controls.ini)

![Снимок экрана от 2022-09-21 08-00-53](https://user-images.githubusercontent.com/6751442/191419701-9a679aa3-9571-4fe1-9f36-a0c8f098923d.png)

**Comment by ds-sloth** [comment]
Successfully reproduced the bug! Inspecting closely now...

**Comment by ds-sloth** [comment]
It wasn't a bug, it was a "feature". Successfully removed, I think. Can you please confirm?

**Comment by Wohlstand** [comment]
Oh, forgot to verify that... I'll try very soon.

**Comment by Wohlstand** [comment]
Tested just now: all works just fine!
