### ISSUE TITLE
question about other smbx versions

### ISSUE THREAD

**Issue by Fenius64** [Wohlstand/TheXTech#429]
will there be support  for 3X8A or SMBX2 anytime soon?

**Comment by Wohlstand** [comment]
Very partially. More likely 38A features will be supported easier. X2 episodes will require porting to get rid of the memory hacking code, etc. Anyway, these episodes will require to have the separated assets packs for each type of episodes as their base content is different between each version.

**Comment by vitzie629** [comment]
> Very partially. More likely 38A features will be supported easier. X2 episodes will require porting to get rid of the memory hacking code, etc. Anyway, these episodes will require to have the separated assets packs for each type of episodes as their base content is different between each version.

Separate assets pack, do you mean an assets pack for SMBX-38A, an assets pack for SMBX2, & an assets pack for vanilla SMBX 1.3 (SMBX64) three or each SMBX versions, right?

**Comment by Wohlstand** [comment]
Yes, that is. Anyway, third main SMBX pack for TheXTech will have its own extension (I plan to select the best of items at both standards, and append them into the new pack. For needs to run 38A or X2 episodes with the similar itemsets, there are two separated packages are planned.

**Comment by vitzie629** [comment]
> Yes, that is. Anyway, third main SMBX pack for TheXTech will have its own extension (I plan to select the best of items at both standards, and append them into the new pack. For needs to run 38A or X2 episodes with the similar itemsets, there are two separated packages are planned.

Cool, thanks! For the third assets pack for TheXTech consists of its own extension, what would happen if every single thing from Super Mario All Stars, & some from the NSMB series (NSMB DS, NSMBW, NSMB2, & NSMBU) for TheXTech at its own extension with non SMBX-64 content just like the fake SMBX 1.4 (made with Paint on Windows back in 2011 for SMBX 1.4 as fake screenshots)?

**Comment by ds-sloth** [comment]
Generally, the goal of TheXTech is not to copy existing games. The one exception is that we are porting some content from 38A and X2 because many of our players/creators also play/create content for those engines.

But if there are particular mechanisms from existing game series that you think are really valuable, we can think about whether and how to make similar mechanisms with new, original assets.

**Comment by vitzie629** [comment]
> Generally, the goal of TheXTech is not to copy existing games. The one exception is that we are porting some content from 38A and X2 because many of our players/creators also play/create content for those engines.
> 
> But if there are particular mechanisms from existing game series that you think are really valuable, we can think about whether and how to make similar mechanisms with new, original assets.

Ok. When it comes to SMBX-38a assets pack will content from SMBX 1.4.5 work?

**Comment by ds-sloth** [comment]
As Wohlstand said, it will be partial. We won't be able to fully support scripted content, and we certainly won't try to replicate 38A logic in a frame-perfect way. But the aim is for most content, especially content that uses fewer scripts, to be at least playable.

Wohlstand is also planning to implement a partial script converter that will make it easier for a level creator to port their content to TheXTech, but since our own scripting API is still in the very early discussion stages, I don't know which features will and won't be possible to support.

**Comment by vitzie629** [comment]
> As Wohlstand said, it will be partial. We won't be able to fully support scripted content, and we certainly won't try to replicate 38A logic in a frame-perfect way. But the aim is for most content, especially content that uses fewer scripts, to be at least playable.
> 
> Wohlstand is also planning to implement a partial script converter that will make it easier for a level creator to port their content to TheXTech, but since our own scripting API is still in the very early discussion stages, I don't know which features will and won't be possible to support.

Ok thanks & partial is better than nothing for 38A content!

**Comment by LoveBodhi** [comment]
Another issue is it won't be compatible when a level/world is made by another asset (e.g. Nostalgic Paradise).

**Comment by vitzie629** [comment]
> Another issue is it won't be compatible when a level/world is made by another asset (e.g. Nostalgic Paradise).

Unless you add non SMBX-64 content in the style of their assets pack to match, it might help the issue!

**Comment by LoveBodhi** [comment]
Also, extension of Nostalgic Paradise and Third Returns are different, so no longer revelent to any of main SMBX Asset Pack.

**Comment by LoveBodhi** [comment]
Let's call the 3rd SMBX Asset Pack "SMBX+".

**Comment by Wohlstand** [comment]
> Let's call the 3rd SMBX Asset Pack "SMBX+".

Good idea 🦊

**Comment by vitzie629** [comment]
> > Let's call the 3rd SMBX Asset Pack "SMBX+".
> 
> Good idea 🦊

It should be called SMBX Deluxe or SMBX Special!

**Comment by Wohlstand** [comment]
If so many ideas, maybe start a poll?

**Comment by vitzie629** [comment]
> 

Great idea! The poll should be the name of the third X-Tech assets pack with new features which involve title names including: 1.) SMBX+ 2.) SMBX Revived 3.) SMBXtra 4.) SMBXtended 5.) SMBX Deluxe 6.) SMBX Special & 7.) SMBXpaned!

**Comment by LoveBodhi** [comment]
8 Mixed Mushroom Kingdom

**Comment by LoveBodhi** [comment]
Here is a poll: https://github.com/Wohlstand/TheXTech/discussions/433

**Comment by Fenius64** [comment]
damn dude I'm glad I opened this lol
