### ISSUE TITLE
Resizing A Section The Player Isn't In Freezes The Game

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#43]
![TheXTech - Wut Bug](https://user-images.githubusercontent.com/30162808/108637165-b3eb3100-7446-11eb-8d64-9a20aa54dcde.gif)

Wat... o.O

Okay, this is _weird_.

I'll try to provide as much information as I can...

After collecting all the stars, I saved and exited. Upon loading up, I appear at the door to the last level I exited. I re-enter... the music plays, the above GIF happens, and the game stops responding to any input.

There is no related terminal output with `--verbose` just the usual stuff.

The issue occurs on a specific save (Save 1), but not a mostly new one (Save 2).

I've attched my episode and saves below (minus custom graphics and music, they aren't needed for this or present in the GIF above, and the issue still ocured without them when I tested)

Again using the pre-built binary for Ubuntu 20.04 from [Release 1.3.4](https://github.com/Wohlstand/TheXTech/releases/tag/v.1.3.4)

[Stars of Night - Weird Bug.zip](https://github.com/Wohlstand/TheXTech/files/6018423/Stars.of.Night.-.Weird.Bug.zip)
I feel oddly talented at breaking the game XD

**Comment by Wohlstand** [comment]
This looks like the section resize event got triggered at the different section that player entered

**Comment by ChristianSilvermoon** [comment]
> This looks like the section resize event got triggered at the different section that player entered

Ooooh, I think I have an idea of what may have caused it, then.
There's an SMW Star in one section, that after collecting, resizes that section.

...perhaps since that star is already gotten it's Death Event Triggers instantly?

I'll just remove the event.

Hmm... but why would resizing a section the player isn't in do... uh... well... _that_?

**Comment by Wohlstand** [comment]
btw, I'll try on vanilla engine this to check, is its vanilla bug, I guess, vanilla

**Comment by Wohlstand** [comment]
Okay, it's truly vanilla bug:
![изображение](https://user-images.githubusercontent.com/6751442/108639134-f8f18080-74a3-11eb-8b01-7454dfb0506f.png)
However, I had to replace "portal" type with "instant" as "portal" wasn't exist at the vanilla engine. BTW, If you target to TheXTech, feel free to use LVLX and WLDX files, they are fully supported by TheXTech include its special features :wink:

**Comment by ChristianSilvermoon** [comment]
I actually haven't been too sure what's different between the "Instant" and "Portal" types they appear to do the same thing. 

Though I have noticed neither of them are capable of taking you to a different level, instead they just warp you in place if set to do so.

And yeah, removing the event did it, it's definitely a section resize thing. (Going to change the title of the issue to reflect that)

**Comment by Wohlstand** [comment]
Anyway, the section resizing that was done over a different sections, should never affect the case when player at a different section.

> I actually haven't been too sure what's different between the "Instant" and "Portal" types they appear to do the same thing.

The difference is: the "Instant" warp makes the player's X speed being zeroed. The "Portal" warp doesn't zero player's move. I.e. Player's kinetic energy is kept.

**Comment by ChristianSilvermoon** [comment]
> Anyway, the section resizing that was done over a different sections, should never affect the case when player at a different section.
> 
> > I actually haven't been too sure what's different between the "Instant" and "Portal" types they appear to do the same thing.
> 
> The difference is: the "Instant" warp makes the player's X speed being zeroed. The "Portal" warp doesn't zero player's move. I.e. Player's kinetic energy is kept.

Oooh I *see* that actually makes a lot of sense! I'm glad that's around actually it's very handy ^^

**Comment by ds-sloth** [comment]
This is fixed by default in multires and guarded by the compat option `modern-section-change`. Can you please confirm that it is fixed on your side?

**Comment by ChristianSilvermoon** [comment]
Tested with the CI build of 2e2c265 from `wip-multires-backport` and can verify, this issue no longer occurs!

**Comment by ds-sloth** [comment]
Great! I'll set this issue up to automatically close when multires is merged.

Also, a fun fact: this bug does not freeze the game. It just travels from the previous section to the new one at a rate of 2px/frame.

**Comment by ds-sloth** [comment]
This bug causes apparent softlocks and has ALREADY BEEN FIXED. I think it'd be good for me to make a PR backporting the portion of multires code that fixes this issue so that we can get it fixed in the 1.3.6.1 release.
