### ISSUE TITLE
Can't change the android launcher background image

### ISSUE THREAD

**Issue by leandro-maciel** [Wohlstand/TheXTech#430]
Even after  editing the gameinfo.ini to use other image on the launcher, it still uses the default one. This also happens after creating a new folder only with the image I want to use

**Comment by Wohlstand** [comment]
Can you show me your `[android]` section of gameinfo.ini file? It should work with no matter where background is placed, the path should be relative to the file itself.

**Comment by leandro-maciel** [comment]
; ---- Android Launcher specific tweaks ----
;[android]
;logo = "graphics/ui/MenuGFX2.png"               ; Android Launcher's logo
;background = "graphics/background2/background2-10.png"    ; Android Launcher's background
;background-frames = 1                                     ; Number of frames on background (if animated)
;background-delay = 125                                    ; Background animation inter-frame delay in milliseconds

**Comment by Wohlstand** [comment]
Heh, you didn't paid attention on the semicolon at begin of each line: the whole block is commented, you should uncomment it by removing semicolons from the begin of line (keep a note, every line and everything after semicolon ; sing, is a comment line, addressed to human to describe the parameter, or something)

**Comment by Wohlstand** [comment]
So, you could make:
```ini
[android]
logo = "path/to/logo-picture.png"                          ; Android Launcher's logo
background = "path/to/your/background.png"                 ; Android Launcher's background
background-frames = 1                                      ; Number of frames on background (if animated)
background-delay = 125                                     ; Background animation inter-frame delay in milliseconds
```
So, use this example as a template and replace paths at "logo" and "background" with proper paths. And, if needed, set up the animation (number of frames and delay of each frame)

**Comment by leandro-maciel** [comment]
thank you, I had no idea about the semicolon indicating comments. I will fix it now

**Comment by Wohlstand** [comment]
Let me know if anything works (or not)

**Comment by Wohlstand** [comment]
I'll close this as no responsce for a long time.
