### ISSUE TITLE
Feature Request: Keep old Save File upon deletion; make empty savx instead

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#436]
The current behavior is that the old Vanilla *save1.sav* gets removed from the Episode Folder. This is undesirable behavior, as the content inside there shouldn't under any circumstances be changed outside of the Editor.

Instead, an empty file should be made in the gamesave directory that would tell TheXTech to ignore the Vanilla .sav file.

**Comment by ds-sloth** [comment]
Great report, @0lhi . This is a pressing issue and I agree we should require it for 1.3.6.1.

**Comment by Wohlstand** [comment]
I have another idea on this:
- make the empty file "xxxx.sav-deleted" that will tell about the fact that file must be ignored
