### ISSUE TITLE
Vanilla bug with AutoScroll events

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#44]
In the original code, an event that changed autoscroll would only produce intended behavior if its event index equaled the layer index.
`AutoX[Events[A].AutoSection] = Events[Events[A].AutoSection].AutoX;`
should say `AutoX[Events[A].AutoSection] = Events[A].AutoX;`
(See [https://github.com/Wohlstand/TheXTech/blob/master/src/layers.cpp#L532](url))
(This is a vanilla bug. See [https://github.com/smbx/smbx-legacy-source/blob/master/modLayers.bas#L322](url))

I didn't change this in my 3DS port because the fix would break unintended behavior that episode developers might have used.

**Comment by Wohlstand** [comment]
If you make the fix of vanilla bugs, you should add the compat.ini flag (see compat.cpp, and the `g_compatibility` global object) that may re-enable it. In the most, autoscrolling had worked when section is zero (aka firsr), and it didn't worked at other sections. I had to fix a doze of them, but I left an ability to re-enable them if needed.

**Comment by Wohlstand** [comment]
Anyway, the rest of episode developers were used the section 0 for the autoscrolling, and, additionally, the autoscroll does work from only the "Level - Start" event at level begin. At the side, on PGE Engine I implemented the dynamically-controlled autoscroller: you can start many of them at different sections, and they will start to scroll once player enter the scrolling section. Also, player can re-enter section again and pass the way from begin of the section. The autoscrolling also can be toggled on the fly by events. I.e. started from the idle, turned into different direction, slowed down, speeded-up, etc. I have some thinks, maybe implement the similar system at here on TheXTech? Shouldn't be hard, at least it's need to make the structure and array of them for the autoscrolling per section, and do the autoscroll processing from looking into that structure at current section (also, have an ability to reset it when player re-enters the section at begin). And, this thing will also require the compat.ini flag to choose the behavior: extended autoscroll suppor, and the matching to same SMBX 1.3 messy behaviour.

**Comment by Wohlstand** [comment]
WOW! When I made this small fix, it's now possible to control the autoscrolling dynamically

[Autoscroller.lvl.zip](https://github.com/Wohlstand/TheXTech/files/6360771/Autoscroller.lvl.zip)
![Scr_2021-04-22_22-18-00_(1)](https://user-images.githubusercontent.com/6751442/115773283-c9ce9100-a3b8-11eb-81e2-59e3e759195b.gif)

**Comment by Wohlstand** [comment]
The one thing I got found: if there are many autostart events, each other will override the auto-scroll rule and as result, you'll get zero auto scroll speed. So, I have a little idea on how to avoid that:
when multiple autostart events were are, don't override auto-scroll if all other events have a zero value. That is probably the same old problem of the PGE Engine where was the same mess. However, I have another idea on how we can re-use this thing: I should allow using the 38A's autoscrolling fields (they are per-section with having the boolean flag to do re-define it or don't, etc.) So, when using a vanilla autoscroll setup, ignore zero speed values. However, do redefine non-zero values.

**Comment by Wohlstand** [comment]
Okay, I made the support for the "Simple" auto scroll of the SMBX-38A and it does working!

[Autoscroller-38a.lvl.zip](https://github.com/Wohlstand/TheXTech/files/6360917/Autoscroller-38a.lvl.zip)

![Scr_2021-04-22_23-01-17](https://user-images.githubusercontent.com/6751442/115778066-c211eb00-a3be-11eb-85dd-d4fc42168eb2.gif)

So, I kept the vanilla autoscrolling setup being fixed but I did it to never override the existing autoscroll setup if zero one got set.

**Comment by Wohlstand** [comment]
btw, it works even I'll re-save it into LVLX format:
[Autoscroller-38a.lvlx.zip](https://github.com/Wohlstand/TheXTech/files/6360951/Autoscroller-38a.lvlx.zip)

**Comment by Wohlstand** [comment]
The only thing is left - add the ability to change these parameters via PGE Editor, otherwise, the SMBX-38A editor is required to set up these fields.

**Comment by Wohlstand** [comment]
So, I did this, together with some other refactoring and cleaning-up. Please check the work! :fox_face:

**Comment by Wohlstand** [comment]
Okay, I had to set the auto-scroll fix into `false`, mainly because there are several faulty levels that kept bad auto-scroll data after unsuccess experiments done by users, they making much more pain than proper use of this thing.
