### ISSUE TITLE
[Feature Request] Player moving faster in the world

### ISSUE THREAD

**Issue by Ashetf2** [Wohlstand/TheXTech#440]
I hate that the player moves so slow in the world. Could you increase the speed to something similar to the speed of the player in SMB3?

**Comment by Wohlstand** [comment]
You can enable the auto-move option in your `settings/thextech.ini` file. Players will move MUCH faster than in the usual way.

**Comment by Wohlstand** [comment]
So, open your `settings/thextech.ini` (which appears in the game's user directory),
- find the section `[gameplay]`
- set the `world-map-fast-move` field with the `true` (or `1`) value
- run the game
