### ISSUE TITLE
[Feature Request] An SMB3-Styled Toad in SMBX

### ISSUE THREAD

**Issue by Superbloxen** [Wohlstand/TheXTech#454]
Hello, I was curious if the current sprite for Toad could be replaced with his SMB3 variant from SMM2. It would give Toad more consistency with the SMB3 theme that Mario, Luigi, and Link already have in the game. This version of Toad could also potentially include his missing swimming animations and his sprites for riding Yoshi, if that would be possible to add into the game. However, I'm unsure how to handle Toad's carrying sprites. IN SMBX, Toad carries things above his head, but in SMM2, he carries objects in front of him, unless he is carrying a player. With these sprites existing ingame, I could create either version, since my sprites are almost finished.

**Comment by ds-sloth** [comment]
Our goal isn't to recreate any existing franchise's content but rather to preserve the SMBX64 engine, so I don't think we'll reimplement Char 3's logic to match a different version of Toad.

Please continue work on your sprites assuming that the item carry logic will stay the same as it is currently. (Sometime in the distant future it may be possible to script a character that acts the way you're describing, but not soon.) Good luck!

**Comment by ds-sloth** [comment]
Thanks again for the note. This is primarily an asset pack issue and not an engine level issue.

It would be a valid enhancement to add swimming and riding animations to Characters 3, 4, and 5 in the future.

I do not think we will change Character 3's item carry position.
