### ISSUE TITLE
Editor should focus player start loc on level open

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#455]
Currently it focuses on the top left of section 0 and often it's difficult to find the level start from here.

**Comment by ds-sloth** [comment]
@Wohlstand I just tested this on Mario Prime and a few other episodes with large levels.

If you can take a quick look on your own "large levels" too and confirm it works, then I think we can close the issue.

**Comment by Wohlstand** [comment]
I'll take a look... I have some examples in my mind, I'll check some later...

**Comment by Wohlstand** [comment]
Tested the thing, works just fine: I surfed through many levels on my end, where player start points was placed and different random places and different sections.
