### ISSUE TITLE
[ Feature Request ] - Data Driven Player Physics

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#460]
I don't think this topic is new here, but it keeps coming up in one form or another, but the idea of modifying various characters' physics, etc, seems to be a common one.

I am not sure if it is realistic or not, but, I could imagine an episode side `player.ini` to customize physics

I'd like to say what I believe this is for and is not for here

I believe this is FOR:
* Customizing how a character moves at a fundamental level
* Swapping between player projectile logic
* Turning a character into a modified clone of another behavior-wise

I believe this *isn't* FOR:
* excessive arbitrary additions beyond the base game (these should be handled in scripting)

## Possible example
```ini
[player-1]
sheet-type=0           ; Character Sheet logic, player-1 vs player-5
char-blocks=0          ; Which Character Blocks should be solid or not?
walk-acceleration=1    ; how fast to speed up to walk-speed
walk-speed=3           ; top walk speed
walk-deceleration=1    ; how fast to slow down from moving
run-acceleration=1     ; how fast running-speed increases
run-speed=6            ; running speed
runway-delay=12        ; how long it takes to get up to flight speed
runway-speed=8         ; running speed when flying is ready
jump-acceleration=6    ; how fast to speed up while jumping
jump-time=3            ; how long should a jump last?
ice-phyiscs=0          ; 0 = normal, 1 = always, 2 = never
lift-speed=1           ; how fast can the player lift something?
health-type=0          ; 0 = Reserve Item, 1 = Hearts, 2 = Neither, 3 = Any Damage Kills
can-mount=0            ; 0 = All, 1 = Living Mounts, 2 = Shoes, 3 = None
state-3-projectile=?   ; NPC ID of projectile Spawned by State 3
state-3-throw-alt=0    ; 0 = normal, 1 = can hold, 2 = Veggie Carry
state-4-flight=0       ; 0 = Racoon behavior, 1 = Fairy Behavior, 2 = 
None
state-4-flight-time=8  ; How long does flight last?
state-5-flight=0       ; same parameters as state-4-flight
state-5-flight-time=8  ; How long does flight last?
state-5-statue=0       ; 0 = Enabled, 1 = Disabled
state-6-projectile=?   ; NPC ID of projectile Spawned by State 6
state-6-throw-alt=0    ; 0 = normal, 1 = can hold, 2 = Veggie Carry
state-6-crouch-guard=0 ; 0 = shields against fire, 1 = vulnerable
state-7-projectile=?   ; NPC ID of projectile Spawned by State 7
state-7-throw-alt=0    ; 0 = normal, 1 = can hold, 2 = Veggie Carry
```

Though I'd suggest perhaps the following for all states
* `state-x-projectile`
* `state-x-throw-alt`
* `state-x-crouch-guard`
* `state-x-flight`
* `state-x-flight-time`

**Comment by ds-sloth** [comment]
The Customizable Player Physics suggestion is related to this but is more directly focused on scripting.

It's possible the easiest way to implement the `playerX.ini` idea will be via the scripting API. Until we have a concrete plan for customizing player physics, let's keep track of and discuss both ideas together.

**Comment by LoveBodhi** [comment]
Returning to here; will this can be changed between modes (for example: Classic and Wonder modes in Nostalgic Paradise), with two different parameters?

**Comment by 0lhi** [comment]
A new discussion for possible physics changes has been opened to keep things coordinated:

https://github.com/Wohlstand/TheXTech/discussions/636

Feel free to bring up your idea there!

**Comment by LoveBodhi** [comment]
Overall, it's now out of scope for TheXTech engine because it won't be customizable.

But it's planned for Nostalgic Paradise

**Comment by ds-sloth** [comment]
We can keep this one unlocked for the sake of discussion, but participants in the conversation should note that the decision not to implement this is final.

**Comment by LoveBodhi** [comment]
> We can keep this one unlocked for the sake of discussion, but participants in the conversation should note that the decision not to implement this is final.

OK then.

**Comment by ChristianSilvermoon** [comment]
> decision not to implement this is final.

Is it safe to say that this should be reserved for the eventual Lua API or perhaps that this functionality shouldn't/won't be implemented at all?

**Comment by ds-sloth** [comment]
I'd prefer not to implement these at all, because there are performance benefits to keeping these constants hardcoded. But I'm not 100% confident in that decision.

**Comment by ChristianSilvermoon** [comment]
> I'd prefer not to implement these at all, because there are performance benefits to keeping these constants hardcoded. But I'm not 100% confident in that decision.

That's understandable, thank you ^^

**Comment by LoveBodhi** [comment]
The problem is NsPr would keep 100% game speed...

Maybe we just change from Source Code...
