### ISSUE TITLE
Customizable Sound Role System

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#462]
I should suggest a "Customizable Sound Role System" for SMBX64 basegame objects, rather than suggesting for sound replacements or separations.

For example:

- Thwomp Fall
- POW Block shake
- Hitting goal tape

(Asset-varied; From Moondust Project)

**Comment by fexhvhbdsf864** [comment]
This idea is cool.

**Comment by LoveBodhi** [comment]
Maybe this option have to rely with Lua?
可能这个也脱离不了Lua脚本系统？

**Comment by LoveBodhi** [comment]
Also: Not just a simple replacement of sounds.ini, Some situations, such as player 1 and 2, and specific NPC, need to be considered...

Therefore this feature can't get rid with Lua script system, as I mentioned above.

**Comment by LoveBodhi** [comment]
Further Researches will go to #681 instead.

**Comment by LoveBodhi** [comment]
Another situation: TheXTech engine is NOT intended for creation right now.
