### ISSUE TITLE
[1.3.6.1] Warn users or auto-convert deprecated compat flags

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#464]
For the compat flag names we deprecated in 1.3.6 and will REMOVE in 1.3.7, I believe our plan is the following:

* If the episode / level is on an editable medium, either (1) update the compat silently, (2) update it while warning the user, or (3) ask the user if they would like to update it.
* If the episode / level is on a non-editable medium, warn the user of this and ask them to update it with the episode creator or by using TheXTech on a desktop.

In any case, "warn" refers to a full Message screen so that the user will certainly see it.

**Comment by 0lhi** [comment]
1 and 2 seem a bit intrusive, 3 could get annoying. How about asking only on the first time and remembering the setting?

**Comment by Wohlstand** [comment]
The "non-editable" medium is the assets directory separated from the user directory for the first case. Also, the App bundle on macOS gets treated as a "read-only" de-jure even if it's writeable de-facto. Basically, that leads to a panic in various security software that finds app bundle attempts to modify the content of self.

**Comment by ds-sloth** [comment]
@0lhi That sounds fine to me. Ask first time and then be silent. (Maybe the internal setting can have three levels "Reject", "Acknowledge", and "Acknowledge non-editable", so that the user will be warned the first time they open something on a non-editable volume, even if they've already accepted converting their editable content.)
