### ISSUE TITLE
Fix default kill score for powerups

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#465]
The changes made a while ago to make powerup collection score configurable introduced some inaccuracies in score calculation compared with SMBX64.

SMBX64 behavior:
* Kill: npc-score (default 100)
* Collect: fixed at 1000

New behavior:
* Kill: npc-score (default 1000)
* Collect: npc-score (default 1000)

The new behavior was not controllable by a compatibility flag, which invalidates Mode 3 speedrun scores if those speedruns involved killing powerups.

Behavior at 1.3.5.0
<img src="https://user-images.githubusercontent.com/72112344/211399432-0b8d0bd0-d0fb-4723-9480-bef2a4433bda.gif" width="400" height="300">

Behavior since 100e4af2 and 26ef229d
<img src="https://user-images.githubusercontent.com/72112344/211401069-c6bb1839-73e0-4564-abfb-423656edf36d.gif" width="400" height="300">

I've introduced a compat flag (naming can be flexible until 1.3.6.1) to choose between these two behaviors.

@0lhi, I believe you made the new behavior originally and had a specific use case for it; maybe you would be able to test that your use case still works in modern mode and not in compat mode.

@Wohlstand if you can give a quick code review before we close the issue that would be nice too. All the changes are in the commit I just submitted.

**Comment by 0lhi** [comment]
Success!

![Scr_2023-01-10_17-39-51](https://user-images.githubusercontent.com/74732674/211610450-e4277ff4-cfc7-43f8-8e26-615210440fed.png)
![Scr_2023-01-10_17-40-13](https://user-images.githubusercontent.com/74732674/211610458-11b52a69-085c-4cba-b90f-48df608f3abb.png)
