### ISSUE TITLE
Fix MCursor asset customization

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#467]
In 1.3.6, I decided to use a rotated and recolored MCursor1.png to indicate the player cursor on the player select screen. This was not friendly to asset creators and I regret the decision. I just added a commit to address this issue. Now, if `PCursor.png` is found, it will be recolored for all Player Cursors. If not, then `MCursor0.png` and `MCursor3.png` will be used as before. 

@LoveBodhi, can you please test that your asset pack works as expected now? I'm sorry for the inconvenience.

**Comment by LoveBodhi** [comment]
![Scr_2023-01-11_07-04-53](https://user-images.githubusercontent.com/37089530/211680790-e4061ac4-05e6-4a05-91d7-fed19d18de5e.png)

OK then.

**Comment by ds-sloth** [comment]
Great! Closing this issue now.
