### ISSUE TITLE
Holding Jump, and pressing Alt Jump, causes Peach to Spin Jump

### ISSUE THREAD

**Issue by DerpyBubblez** [Wohlstand/TheXTech#47]
![Scr_2021-04-10_13-21-16](https://user-images.githubusercontent.com/19195170/114280736-49934d80-9a00-11eb-97fa-0563bb7cbbf8.gif)
Found this a couple days ago, seems pretty weird.

**Comment by Wohlstand** [comment]
Whoops, I guess I know why that happens, that probably because of a small miss while fixing the vanilla bug which makes no way for Kood to escape the rainbow shell-surf riding. I'll try to check out this as fast as possible and make sure this thing will not work except for the real need. Also, Kood can spin-jump from off ladders and vines because of the same bug.

**Comment by Wohlstand** [comment]
Just now I reproduced this, heh:
![Scr_2021-04-10_21-33-21](https://user-images.githubusercontent.com/6751442/114280981-779a8100-9a44-11eb-9379-455cc32c7c5c.gif)

**Comment by Wohlstand** [comment]
Anyway, the ability of Peach to spin-jump would be an optional toggleable feature at the episode side to not give this skill at old episodes to not break the gameplay logic.

**Comment by Wohlstand** [comment]
Fixed that bug just now! Please try the latest dev builds after ~10 minutes (once new builds will come up)

**Comment by Wohlstand** [comment]
I made the condition to make sure the thing will work at the shell-surf only, and will not be affected by other cases.

**Comment by Wohlstand** [comment]
![Scr_2021-04-10_22-32-33](https://user-images.githubusercontent.com/6751442/114282445-c3e9bf00-9a4c-11eb-8816-a3e4b0fdf82e.gif)

And with the showing the ability of Peach to escape the shell-surfing:
![Scr_2021-04-10_22-32-52](https://user-images.githubusercontent.com/6751442/114282449-c6e4af80-9a4c-11eb-803c-79a1c0280379.gif)

**Comment by Wohlstand** [comment]
Forgot to mark this as "need a test"... Please download the dev build and try to verify the game on how it will work now. At this repository wiki you'll find the article that contains all dev build links.

**Comment by DerpyBubblez** [comment]
Working as expected.
