### ISSUE TITLE
Replace the SM64 main theme SPC with the real theme

### ISSUE THREAD

**Issue by The-Shotgun** [Wohlstand/TheXTech#481]
mario64-maintheme.spc included in the default asset pack is actually a bit different from [the real Bob-Omb Battlefield theme](https://fi.zophar.net/soundfiles/nintendo-ds-2sf/super-mario-64-ds/32%20BGM%20%2332%20%5BNCS_BGM_CHIJOU%5D.mp3) - the latter is a bit slower, richer in sounds and loops differently. 
Also, replacing all other SM64 songs with their 64DS versions would be beneficial too, due to their increased quality. Currently only the main theme appears to be the DS version (or rather, a recreation of it) while all other songs are from the N64 version.

**Comment by LoveBodhi** [comment]
Also replace Mushroom Gorge with MK8DX Version

**Comment by ds-sloth** [comment]
This is a nice suggestion, but it's focused on the asset pack, not the game engine.

Please join the Moondust Zone Discord server (https://discord.gg/bymVmcCh) or the linked Matrix space (https://matrix.to/#/#moondust-lobby:matrix.org), which has dedicated channels to discuss SMBX-specific content. Thank you!
