### ISSUE TITLE
[Switch] Skull Rafts crash the game

### ISSUE THREAD

**Issue by JoeChungusThrows** [Wohlstand/TheXTech#487]
**Describe the issue**

Attempting to activate a skull raft will stop the game and return to the homebrew screen.

**Example Case**

This happens consistently in Pyramid of Fail

**Additional context**

1.3.7 Dev Versions
Switch CI #374: Pull request https://github.com/Wohlstand/TheXTech/pull/328
Windows CI #521: Pull request https://github.com/Wohlstand/TheXTech/pull/328

**Comment by Wohlstand** [comment]
Does the same happen at the main branch too?

**Comment by JoeChungusThrows** [comment]
Yes it does.
Windows CI #540: Commit [5b6c770](https://github.com/Wohlstand/TheXTech/commit/5b6c770a8c930c92f3f0818c9ef593cb935478e9)
![image](https://user-images.githubusercontent.com/26609059/217700820-a5ad352e-f96e-49e7-bb8c-ffcd4076ef05.png)

**Comment by Wohlstand** [comment]
Seems it's a bug of the new performance update made by my co-developer @ds-sloth, thanks you for the report, we will fix this as soon as possible.

**Comment by ds-sloth** [comment]
That assert indicates that there's unexpected deep nested logic here, maybe a recurrent function used a tree query by mistake. I'll try to refactor now.

**Comment by ds-sloth** [comment]
@JoeChungusThrows I'm sorry this happened during your gameplay, it seems like a frustrating case. Can you please review whether a new `main` build works for you now? (To keep the code history clear, I won't merge it into multires until it's tested.)

Please review my commit above, @Wohlstand. It's slightly complicated so I preserved the reference recursive implementations in `#if 0` comments. I tried to comment it well but it will be nice to get your manual review and style tweaks.

Also, sounds like the SDL message box might be stubbed on Switch. That's not good. If it wasn't stubbed, there still would have been a crash, but a bit more user-friendly than what Joe saw. We could try to write a patch for this, but there aren't any safe libraries for message boxes on Switch (the only applet I found logs a system report which could lead to bans).

**Comment by JoeChungusThrows** [comment]
Tested on the latest Windows versions (Both main and dynamic res) and Switch version (dynamic res)
The rafts no longer crash the game.

![image](https://user-images.githubusercontent.com/26609059/218349390-5b287dc1-d022-4d33-8c9a-65b3636232c9.png)

**Comment by ds-sloth** [comment]
Fantastic, thanks again for the report!
