### ISSUE TITLE
Weird behavior at LunaDLL/LunaScript NPCs

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#488]
There are 3 oddities that i found while testing some scripts on thextech, however, i cant be sure if they are vanilla bugs since i cant test it in Original LunaDLL SMBX:

i downloaded the first two from smbx archive, third one i got it when scripting:

* Bony Bettle:

   This npc never would show any spike

   (no screenshot)

    level example: 
[5.zip](https://github.com/Wohlstand/TheXTech/files/10702031/5.zip)

* Pipe Lakitu

   Spinies spawned from lakitu will have the wrong size (the one with correct size, i put it manually in level)
  
<img width="1440" alt="scrn" src="https://user-images.githubusercontent.com/60852359/217953443-870b0cd3-9016-4c9d-a31a-8aada6762af1.png">

   level: 
[6.zip](https://github.com/Wohlstand/TheXTech/files/10702045/6.zip)

* ~~Custom GFX~~

  ~~Some bug with (maybe) Lunadll.txt would cause the custom enemy go back using the original graphic~~
  
  ~~(no screenshot)~~

  ~~level:~~
~~7.zip~~ for this one was my bad

**Comment by ds-sloth** [comment]
Thanks very much for the report!

Can you please check the 1.3.6 release?

It's possible this requires https://github.com/Wohlstand/TheXTech/tree/wip-npc-mememu-fix to work with the most recent builds. If so, I'll prioritize testing and finishing that.

**Comment by M0REKZ** [comment]
i tested the three levels at 1.3.6 and are the same thing, also, now i included a level for the third one

**Comment by ds-sloth** [comment]
Thanks for checking this, that's very helpful. Then, I think we need to compare the behavior directly to the original SMBX + LunaDLL. I'll try to do this on one of my Windows virtual machines.

**Comment by P-Star7** [comment]
@M0REKZ Oh, this Pipe Lakitu bug is a vanilla bug, it is because I, the creator of the graphic, neglected to make npc-246.txt. The size of the old NPC is retained when switching to the new NPC. Make a npc-246.txt that is:
height=32
gfxheight=32
width=32
gfxwidth=32

**Comment by Wohlstand** [comment]
I tested the thing on LunaDll v7 (Appears at the first release of A2XT Analogue Funk) using my second debug computer (it runs Windows 10), and result is the same. Before, I had to convert all resources into legacy format, and TXT files into CRLF format to get it work.

https://github.com/Wohlstand/TheXTech/assets/6751442/0a273c18-9aaa-4daa-817d-aff25608342a

The demo 5 just doesn't work here, because it requires LunaDLL v8. I need to pull LunaLua-SMBX package and try it again.

**Comment by Wohlstand** [comment]
Okay, I tested out the Demo 5, it works absolutely same as on TheXTech (except of the invalid number printing, it's a bug of LunaDLL tha got been fixed at TheXTech side):

https://github.com/Wohlstand/TheXTech/assets/6751442/409d463b-a809-4a7b-8aec-c6bd7fd5489e


And Demo 6 again, it works absolutely same:

https://github.com/Wohlstand/TheXTech/assets/6751442/0124c1d1-c1aa-407b-a389-316a5f781a90

My conclusion: both are NOT a bugs of TheXTech. This is, possibly, your mistake in the scripts that you made.

There is a tip for Demo 6: if you changing a spawning NPC of firefly, also override size values BEFORE replacing the ID.

Tip for Demo 5: If you going to perform a chain, please use more than two calls, to execute each other. Maybe I'll try to tweak your examples soon during random relaxing time...

**Comment by Wohlstand** [comment]
Also, if you want to ask help to fix these scripts, please make a topic at Discussions, or ask at Discord.

**Comment by M0REKZ** [comment]
Well, after all, looks like i just downloaded bad scripts... Thanks for the help 🥶
