### ISSUE TITLE
Message Box Indentations Are Broken

### ISSUE THREAD

**Issue by DerpyBubblez** [Wohlstand/TheXTech#49]
I've been playing through ASMBXT and noticed that the textboxes were looking kinda weird. Suspicions were confirmed during one of its cutscenes, and comparing to a video.

The X-Tech
![Screenshot_20210417_100853](https://user-images.githubusercontent.com/19195170/115117826-0ee06680-9f66-11eb-9db6-76ad50d79174.png)

SMBX (Screenshot from a video)
![Screenshot_20210417_101637](https://user-images.githubusercontent.com/19195170/115117843-1ef84600-9f66-11eb-8c13-ed09a5d41f97.png)

**Comment by Wohlstand** [comment]
I need to check that...

Btw, some level require you to type the cheat code and then,  type the "redigitiscool" after the "raomode" to remove 128 demos from off the hab.
At the side, I do work on the repack for this, I do have to provide all cheat names that equal to the actual game, and repair the passwords system (I have been talked with a dude who originally built it)

**Comment by Wohlstand** [comment]
P.S. I did a little test, and that is how the PGE Engine draws the same message box:

![Снимок экрана от 2021-04-18 00-55-34](https://user-images.githubusercontent.com/6751442/115127729-7687c780-9fe1-11eb-9205-40c53f1d7d05.png)

**Comment by Wohlstand** [comment]
Yeah, in my test app (where I re-implemented the same message box's algorithm), the bug gets reproduced:
![изображение](https://user-images.githubusercontent.com/6751442/115127790-0cbbed80-9fe2-11eb-9362-07f4afa19280.png)
I'll try to fix that now...

The quote:
```
Kood: Okay, the poision          cow problem has been       taken care of, Jowey       won't be bothering         us anymore.
```

**Comment by Wohlstand** [comment]
When I do set the "vanilla mode", it prints the text properly:
![изображение](https://user-images.githubusercontent.com/6751442/115127826-645a5900-9fe2-11eb-9eab-14294a755079.png)

The reason for the mess that I had to update the message box algorithm to resolve the overflow problem caused by too long space-less strings such as `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`. I understand that the case here the extra space got added into every next line, that is not good...

**Comment by Wohlstand** [comment]
What the goal of this thing is:
![изображение](https://user-images.githubusercontent.com/6751442/115128077-f57dff80-9fe3-11eb-98ee-32e1e5570a71.png)

when the Vanilla case:
![изображение](https://user-images.githubusercontent.com/6751442/115128082-00389480-9fe4-11eb-8138-50091735f2d4.png)

Anyway, just now I managed to fix this mess completely:
![изображение](https://user-images.githubusercontent.com/6751442/115128093-0dee1a00-9fe4-11eb-8e98-bad5bacfa6ef.png)

**Comment by Wohlstand** [comment]
Fixed at the game too:
![изображение](https://user-images.githubusercontent.com/6751442/115128226-f2cfda00-9fe4-11eb-80d9-a005cd06418d.png)

**Comment by Wohlstand** [comment]
Just now I sent the fix, please try the dev build of the game when it gets ready (or pull the latest source code from the repo) to verify the work

**Comment by DerpyBubblez** [comment]
Working
![Screenshot_20210417_203948](https://user-images.githubusercontent.com/19195170/115131395-7b3a8480-9fbd-11eb-8a9a-a298a8494725.png)

**Comment by Wohlstand** [comment]
Now you can simply put the fixed executable into the game you played and resume the normal game :fox_face:
