### ISSUE TITLE
Add New Game Mode

### ISSUE THREAD

**Issue by fexhvhbdsf864** [Wohlstand/TheXTech#490]
My Idea is:

- [ ] Rush Mode (Random choose any already existed level and episodes, but is some time limit(can custom))
- [ ] Coin Battle (NSMBW)
- [ ] Coin Rush (NSMB2)
- [ ] Challenge Mode (NSMBU)
- [ ] Boss Rush
- [ ] Mini Games
- [ ] Puzzle Mode
- [ ] Survival Mode
And more etc.

**Comment by LoveBodhi** [comment]
- [] Random Challenge (SMM)
- [] Time Attack Mode

**Comment by M0REKZ** [comment]
this seems interesting 😏...

**Comment by LoveBodhi** [comment]
Another one is Party Mode (similiar as Encore Mode in Sonic Mania)

**Comment by LoveBodhi** [comment]
New mode: Fanta, SMB Wonder-like gameplay system. (No score)

**Comment by LoveBodhi** [comment]
... Maybe these should be achieveable with LUA script system??

**Comment by LoveBodhi** [comment]
Anyways, "Recreating commercial stuff" isn't the project goal.

**Comment by LoveBodhi** [comment]
Anyways: This is consider as OoS!
