### ISSUE TITLE
[Multires] World Map View Expands When Swapping Characters

### ISSUE THREAD

**Issue by JoeChungusThrows** [Wohlstand/TheXTech#493]
**Describe the issue**
When pausing the game on the world map, swapping characters results in the world map's view expanding.

**Additional context**
Build: Windows CI #565: Pull request https://github.com/Wohlstand/TheXTech/pull/328
This also happened on the Switch version that I've tried.
This issue does not occur on the main branch.
Happens on any resolution.

**Recording**
![Scr_2023-02-22_19-27-22](https://user-images.githubusercontent.com/26609059/220802129-bb54730e-494a-43b3-92c5-296c3300e2b6.gif)

**Comment by ds-sloth** [comment]
Hi, thanks for the report and sorry for the delay on getting to this. I should have just pushed a fix to the multires branch. Can you confirm whether the behavior has returned to normal for you? Thanks!

**Comment by JoeChungusThrows** [comment]
Should be good now.

![Scr_2023-02-27_19-40-37](https://user-images.githubusercontent.com/26609059/221730855-1edee404-4f50-4ada-97d0-11289d4fe9a9.gif)

**Comment by ds-sloth** [comment]
Awesome, thanks again for the report!
