### ISSUE TITLE
multiplayer camera glitch

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#5]
see this: 
![Sin-titulo](https://user-images.githubusercontent.com/60852359/79704165-06375080-827e-11ea-8ed3-f63eb0b4508d.gif)

**Comment by Wohlstand** [comment]
Whops...
Does this happens with a "no background" only?

**Comment by Wohlstand** [comment]
I guess that there is a missing of a black rectangle drawing, that should fix this issue...

**Comment by Wohlstand** [comment]
Okay, another question: do you have a HDPI screen?

**Comment by Wohlstand** [comment]
![Снимок экрана от 2020-04-20 04-04-53](https://user-images.githubusercontent.com/6751442/79704864-1c640180-82bc-11ea-858f-f7a2f74f1e7a.png)
Okay, I see that glitch appears here in only a case of non-proportional scaling of window ... :thinking:

**Comment by Wohlstand** [comment]
Okay, I had found a real reason of this glitch and I got fixed it quickly!
My mistake was that to "reset" viewport I need to simply pass a `NULL` as a viewport area to tell it use "entire target" instead of an incorrect guessing.
https://wiki.libsdl.org/SDL_RenderSetViewport

**Comment by Wohlstand** [comment]
Please test this.

**Comment by M0REKZ** [comment]
it worked good
