### ISSUE TITLE
[Feature Request] Add the P-Meter

### ISSUE THREAD

**Issue by GoombarioFan** [Wohlstand/TheXTech#503]
Add the P-Meter first seen in Mario Bros. 3, perhaps as a togglable/optional feature. It would be nice to have a visual representation of the player's momentum. To prevent the top of the screen from being overcrowded, I would suggest its position on the screen be similar to where it was in New Super Mario Bros. 2 (lower left).

Perhaps the P-Meter could be visually configured (relating to #460?) on a per episode/level basis similar to the effects of [a certain Mario Advanced 4 e-reader card](https://www.mariowiki.com/Sugu_ni_mantan!_Power_Meter!!). In other words, the amount of effort it would take to reach full speed could be adjusted by the number of arrows present on the P-Meter.

**Comment by ds-sloth** [comment]
Thanks for the suggestion! We aren't planning to reimplement features of any commercial games other than the features of SMBX64. But, this sort of thing should be possible via scripting in the future.

**Comment by LoveBodhi** [comment]
> We aren't planning to reimplement features of any commercial games other than the features of SMBX64

And therefore it's outscoped (NOT follow on contributing guidelines). We have to switch engine for this.
