### ISSUE TITLE
Transparent Colour of Message Box image issue

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#508]
**Describe the issue**

When the message box has transparent colour, it blends (instead of crop) and causes the middle part of transparent colour issue.

**Example Case**

[TransparentMsgBox.zip](https://github.com/Wohlstand/TheXTech/files/11144861/TransparentMsgBox.zip)

(Nostalgic Paradise asset)

Multi-line, works fine
![Scr_2023-04-04_13-02-01](https://user-images.githubusercontent.com/37089530/229691795-1dad7ae3-0e82-4c8b-b58f-5a49fabcaee4.png)
Single-line, transparency layer was blended between two images, middle part loses transparency
![Scr_2023-04-04_13-02-04](https://user-images.githubusercontent.com/37089530/229691798-b68d1d2c-5ebf-4f0f-b4c7-2c0706265b45.png)

**Recording**

None

**Vanilla Recording**

None

**Additional context**

None

**Comment by Wohlstand** [comment]
Vanilla logic isn't ideal while forming a message box. I'll try to compare with Moondust's that avoids such mess.

**Comment by ds-sloth** [comment]
Now that I read this code, I see that it was not the fault of the vanilla logic, but my fault.

I wasn't considering the case where semi-transparent boxes would be used and let them overlap when the total height was below 40px. Can you please check the behavior now?

**Comment by LoveBodhi** [comment]
![Scr_2023-07-09_11-53-05](https://github.com/Wohlstand/TheXTech/assets/37089530/063bf5a8-9e6c-4309-b842-cc2c7b5a5d4a)
Test works
