### ISSUE TITLE
SMW Koopas are not tied to Beach Koopas they spawn

### ISSUE THREAD

**Issue by GoombarioFan** [Wohlstand/TheXTech#514]
The expectation is that defeating a Beach Koopa that spawned from a SMW Koopa would count as its death, however this is not the case. Instead their defeat is linked to their shell specifically, meaning that going off-screen and coming back after having defeated a Beach Koopa simply respawns the full SMW Koopa.

This is probably linked to how SMW Koopas turn into shells when frozen rather than maintaining their form like a Rex would. I imagine this is all because they simply reuse code from SMB3 Koopas.

These issues were present on vanilla 1.3.

![Scr_2023-04-11_01-06-11](https://user-images.githubusercontent.com/80182971/231061473-5654668f-53f5-41a2-9d34-83411c90e18e.gif)

**Comment by Wohlstand** [comment]
That because beech Koopa is new-spawned NPC, and she'll remain an original NPC. So, if it gets reset, it turns back into Koopa. So, make more beech Koopa for a God of Beech Koopas!

**Comment by ds-sloth** [comment]
Thanks for helping us document this. It's an interesting behavior but I don't think it's necessary for TheXTech to change it.
