### ISSUE TITLE
Confirm autocode compatibility with recent performance updates

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#516]
We have made significant performance updates to the block, background, and NPC systems for 1.3.6.1. However, these updates require certain information about the object arrays to be maintained and updated during gameplay.

It will be useful to test and confirm the compatibility of Autocode writes to these arrays prior to the 1.3.6.1 release to ensure that total compatibility is maintained and users don't experience any unexpected behavior.

I'll take a first attempt at this, and request @Wohlstand's review of any linked commits if I find things to fix.

**Comment by ds-sloth** [comment]
Wohlstand made some recent changes to `lunanpc.cpp` and `mememu.cpp` that should fix all possible problems, but I'll leave this issue open in case anybody finds anything before the 1.3.6.1 release.

**Comment by Wohlstand** [comment]
On my side, there is no issues found right now. I have one thing to verify - the demos sent by +KZ who reported that they are problematic.

**Comment by Wohlstand** [comment]
After I checked +KZ's files on vanulla LunaLua-SMBX (LunaDLL v8) and on A2MBXT (LunaDLL v7), and behaviour is absolutely same. From my side, I can tell, there is nothing also to verify. Some other things may happen at MultiRes thing. If you think, all fine, feel free to close this.

**Comment by ds-sloth** [comment]
Fine to close. Thanks for verifying these cases.
