### ISSUE TITLE
Checkpoint System Update Breaks "It's a Wonderful Demo"

### ISSUE THREAD

**Issue by DerpyBubblez** [Wohlstand/TheXTech#52]
The level relies on checkpoint system being jank to allow you to get the second star.

https://youtu.be/CnbhdPtH86o?list=PLHoMTgXllvVZIDxLB5LWIv-6UVQwNcAiy&t=565

**Comment by Wohlstand** [comment]
I guess I should add the "compat.ini" option to re-enable it back (you will need to make the "compat.ini" file at the level's custom directory with the option), I'll notify you when it will be ready. :wink:

**Comment by Wohlstand** [comment]
Okay, just now I pushed the commit that adds an ability to restore old checkpoints behavior, so, you only need to:
* Updated the engine's executable
* At the level's directory, make the "compat.ini" file with the next content:
```ini
[compatibility]
enable-multipoints = false
```
and the level should get working

**Comment by Wohlstand** [comment]
I tested that level at me, now it works :fox_face:

**Comment by DerpyBubblez** [comment]
Working.
