### ISSUE TITLE
CN locale layout issues in the editor

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#531]
# 01

![Scr_2023-05-04_11-41-55](https://github.com/Wohlstand/TheXTech/assets/37089530/3350a834-8892-484c-9d6a-a1d875a0466a)

This (友好 and 信息) should be Right Aligned

# 02

![Scr_2023-06-10_13-07-36](https://github.com/Wohlstand/TheXTech/assets/37089530/87a18b80-5422-4a90-9ecd-799ff2d49fa1)

宽 and 高 should be in a same column

(More soon)

**Comment by ds-sloth** [comment]
I made a lot of alignment changes, including the improvements you mentioned. Please test again and let me know whether everything looks good.

<img src="https://github.com/Wohlstand/TheXTech/assets/72112344/9e325ae2-678c-4164-a7db-38a6e729f3e1" width="400" height="300">

<img src="https://github.com/Wohlstand/TheXTech/assets/72112344/6c8a91fe-f484-4eee-9835-c7733c1c5ed8" width="400" height="300">

**Comment by LoveBodhi** [comment]
![Scr_2023-07-19_10-55-09](https://github.com/Wohlstand/TheXTech/assets/37089530/bbcff2fd-8676-4169-9bcf-b487e2df8974)
