### ISSUE TITLE
Completion counter overlaps star counter

### ISSUE THREAD

**Issue by r543** [Wohlstand/TheXTech#541]
The percentage (%) symbol of the completion counter overlaps the star counter if you get 100% and have 1 star in an episode.
(You need to have at least 1 star for the star counter to show)
![smbx-win64_20230610_235401993_nFhqeLC3hK](https://github.com/Wohlstand/TheXTech/assets/21023189/207bf2a1-0703-4fec-85a9-b61dcdbe4412)

This doesn't happen in vanilla SMBX due to it lacking the percentage symbol.

Below is a 100% save of the Invasion 2, to quickly test this issue:
[world.wldx-save1.savx.zip](https://github.com/Wohlstand/TheXTech/files/11713629/world.wldx-save1.savx.zip)

My suggested fix would be to move the star counter by 4 pixels to the right, that way it no longer overlaps at 100% and has a 2 pixel space between it, like the rest of the font.
Of course, the spacing can also be bigger if you'd like.

(Note that the star icon (ui/Interface5.png) is also placed one pixel too low on the save select. I'll report this in a separate issue as that's a vanilla peculiarity and there's several UI elements that aren't aligned properly.)

**Comment by Wohlstand** [comment]
Sounds like a small tweak in the menu code to make the star to be aligned properly.

**Comment by Wohlstand** [comment]
Made a tweak. Please test out the latest development version.

**Comment by r543** [comment]
Apologies for only getting to this now, tested it using the latest development version and the counter no longer overlaps:
![Scr_2023-07-01_22-17-02](https://github.com/Wohlstand/TheXTech/assets/21023189/18e7b3ff-0632-443a-af36-c2e9f6555a3a)
I'd consider increasing the spacing (current development version has 6, vanilla had 16 pixels, which is the same amount used between the words "NEW GAME") but that's just cosmetic, so you can go ahead and close this as resolved.

**Comment by Wohlstand** [comment]
Thanks for the confirmation!
