### ISSUE TITLE
PS4 Controller freeze on macOS

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#549]
**Describe the issue**

Im using an Unofficial Ps4 controller to play, connected via bluetooth, it works without problems at other games, however when i turn on the controller and open TheXTech, the controller will Freeze and ill need to reset it with a clip.

The bug its only at bluetooth, works well while wired, and on android there are no problems at bluetooth.

**Additional context**

I can find things like these in the log, note that at the last line i didn't shutdown the controller:

```
Debug: Opening joystick id 0...
Debug:   successfully opened!
Debug:   Name: PS4 Controller
Debug:   GUID: 03008fe54c050000c405000000016800
Debug:   Number of Axes: 6
Debug:   Number of Buttons: 16
Debug:   Number of Balls: 0
Debug:   claims to be a game controller...
Debug:     successfully opened game controller!
Debug:   does not support haptic.
Debug:   received ID 6. adding to poll list!
Debug: joystick with ID 6 removed.
```

**Comment by Wohlstand** [comment]
Which version of the game you do use? Do you use the stable 1.3.6 or the latest dev build? Please try the latest dev version, this looks like a problem of SDL2 that had been fixed at some moment.

**Comment by M0REKZ** [comment]
> Which version of the game you do use? Do you use the stable 1.3.6 or the latest dev build? Please try the latest dev version, this looks like a problem of SDL2 that had been fixed at some moment.

At the moment of writing the issue i was using:
Super Mario Bros. X - (TheXTech v1.3.7-dev, #503006e)

Now tried latest dev build, same bluetooth problem.

**Comment by Wohlstand** [comment]
And now, try the stable version to confirm, was that bug before, or it had been introduced recently? Sounds like I should write an issue to the SDL folks about this. Also, could you tell me explicit model number of your unofficial PS4 controller if presented?

**Comment by M0REKZ** [comment]
> And now, try the stable version to confirm, was that bug before, or it had been introduced recently? Sounds like I should write an issue to the SDL folks about this. Also, could you tell me explicit model number of your unofficial PS4 controller if presented? And the manufacturer who made it.

Tried Stable 1.3.6, controller is working fine, the model is CUH-ZCT2E, couldn't find manufacturer

**Comment by Wohlstand** [comment]
Sounds, like, this is a new bug then... I should report this to SDL folks.

**Comment by Wohlstand** [comment]
Just now I checked: I had the version 2.28.0. Just now I updated the version to 2.28.1, please test the most fresh build once it gets built.

**Comment by Wohlstand** [comment]
(In the set of chaned files, there are PS4 related tweaks was found)

**Comment by Wohlstand** [comment]
And, if bug is still presented, I will report problem to SDL folks.

**Comment by M0REKZ** [comment]
> Just now I checked: I had the version 2.28.0. Just now I updated the version to 2.28.1, please test the most fresh build once it gets built.

Tested new build, still same bug 🥶

**Comment by M0REKZ** [comment]
Just also realized that the stable version will exit normally when clicking exit or closing the window, while the dev version will close the window but the process wont be terminated (it still shows as open in the dock) so i need to force-quit... (unrelated to controller)

**Comment by Wohlstand** [comment]
> Tested new build, still same bug :cold_face:

Going to report to SDL folks...

**Comment by Wohlstand** [comment]
Reported: https://github.com/libsdl-org/SDL/issues/7960

**Comment by Wohlstand** [comment]
@M0REKZ, just now I pushed the update that adds a tweak to the SDL2 <https://github.com/libsdl-org/SDL/commit/6bf5f5a221f971a5804062e365a281c30668dd9c>. Please test out the thing once it gets built.

**Comment by M0REKZ** [comment]
> @M0REKZ, just now I pushed the update that adds a tweak to the SDL2 [libsdl-org/SDL@6bf5f5a](https://github.com/libsdl-org/SDL/commit/6bf5f5a221f971a5804062e365a281c30668dd9c). Please test out the thing once it gets built.

Now tried the latest build, controller is working fine 👍

**Comment by Wohlstand** [comment]
Súper!
