### ISSUE TITLE
Add New Playable Characters

### ISSUE THREAD

**Issue by fexhvhbdsf864** [Wohlstand/TheXTech#568]
My Idea is:
From SMBX2:
Mega Man
Wario
Bowser
Klonoa
Ninja Bomberman
Rosalina
Snake
Zelda
Ultimate Rinka
Uncle Broadsword
Samus
Juni (Only Beta 3)
Princess Rinka (same too)

Other:
Sonic
Tails
Knuckles
Amy
Kirby
Roll
Proto Man
Bass
Waluigi
Crash Bandicoot
Ryu Hayabusa (From Ninja Gaiden)
SOPHIA III
Arthur
Simon Belmont
Vile
Zero
The Kid (From IWBTG)
Pikachu (From Pokemon)
Meta Knight
Yoshi (Playable)
Bill Rizer (From Contra)

**Comment by LoveBodhi** [comment]
Should this be "Asset Pack" varied?

**Comment by ds-sloth** [comment]
Yes, this is something that an asset pack creator would implement in the future, not a part of the core engine. It's good to know people are interested in custom characters!
