### ISSUE TITLE
Level Tests won't work when level forgoes starting point in favor of Warp Entrance

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#574]
Currently, levels with entrance warps but no start position cannot be tested. Example shows warp5.lvlx from Invasion 2.

![Scr_2023-08-01_00-19-32](https://github.com/Wohlstand/TheXTech/assets/74732674/95007caa-b8b9-45ee-8f8e-b86e7a5b6746)

X2 provides a solution for this:

![2023-08-01_00_23_01](https://github.com/Wohlstand/TheXTech/assets/74732674/ead62968-c8d3-4bb1-a8c5-a67eda4aa6f6)

**Comment by ds-sloth** [comment]
Should be working now, via a selector in the test level settings screen and a command line option `-w` / `--start-warp`.

**Comment by ds-sloth** [comment]
Ah, before we close this: should `-w` refer to `--start-warp` or `--world`? (See #36)

**Comment by Wohlstand** [comment]
That could work for both, however, an overcomplication. For the world map testing, that can be easily recognised is that a world map or a level supplied:
- When supplying a level file, the level testing gets started, and `-w`/`--start-warp` works.
- When supplying a world map file, the episode playing gets started. And the `-w` is totally unneeded.

In the past, I had the `-l` argument to supply a level test, but I had been deprecated it, because it's a mess.

**Comment by ds-sloth** [comment]
Ah, good plan. So the world map argument will simply be a special case of the supplied filename.

**Comment by 0lhi** [comment]
Warp Start Point overrides collected Checkpoint.

![Scr_2023-08-19_20-00-43](https://github.com/Wohlstand/TheXTech/assets/74732674/7b789f56-9ce6-496f-aa82-212e7d860542)

**Comment by Wohlstand** [comment]
I forgot to say, that I added an error on attempt to start level without a start point or warp entrance selected: https://github.com/Wohlstand/TheXTech/commit/68af3093d9100fb82625d662757bf363bf382467

**Comment by Wohlstand** [comment]
So, user will know about this error explicitly, and won't get being confused because being spawned into nowhere.

**Comment by 0lhi** [comment]
@Wohlstand Good addition for command line. But it breaks when entering via editor:

![Scr_2023-08-19_22-17-18](https://github.com/Wohlstand/TheXTech/assets/74732674/2888bae4-a49a-43dc-b60b-a1ed74c94d6c)

@ds-sloth I guess best fix would be to remove the `START POS` option when there is no start position?

**Comment by 0lhi** [comment]
@Wohlstand Good addition for command line. But it breaks when entering via editor:

![Scr_2023-08-19_22-21-55](https://github.com/Wohlstand/TheXTech/assets/74732674/6ca696c8-6af0-4e9f-af9d-11881d938858)

@ds-sloth I guess best fix would be to remove the `START POS` option when there is no start position?

**Comment by Wohlstand** [comment]
> But it breaks when entering via editor:

Good catch! Ye, I already wrote in my code `FIXME: Verify this`. Sounds like need to tweak a code to properly return back into the Editor when starting an errored level.

**Comment by ds-sloth** [comment]
> Warp Start Point overrides collected Checkpoint.

This one is fixed, and Wohlstand and I have fixed the new warning message.

**Comment by 0lhi** [comment]
Okay, Testing Menu will need a revisit for 1.3.7, but for now it's fine.
