### ISSUE TITLE
Replace "P2 Disconnected" Message with the Input Display Controller containing a 'searching' visual

### ISSUE THREAD

**Issue by 0lhi** [Wohlstand/TheXTech#587]
To prevent overlaps in Multiplayer and make space for Multires, the "P2 Disconnected" message should be replaced with an emptied Input Controller Display containing a visual indicator (like "..." or a rotating 🔍).

![Scr_2023-08-19_18-54-19](https://github.com/Wohlstand/TheXTech/assets/74732674/9f184bd5-fe19-4ec1-8d8e-d7da433da9c1)

Minimum for 1.3.6.1 is to place the text where the Player's controller would be.

**Comment by ds-sloth** [comment]
Is this good enough to remove from the 1.3.6.1 milestone?

![Scr_2023-08-19_16-15-59](https://github.com/Wohlstand/TheXTech/assets/72112344/91658ac2-ae42-4b9c-b600-f87dd00dbcbe)

**Comment by Wohlstand** [comment]
> Is this good enough to remove from the 1.3.6.1 milestone?

Sounds like yeah, not critical

**Comment by 0lhi** [comment]
Looks great!

![Scr_2023-08-20_20-22-38](https://github.com/Wohlstand/TheXTech/assets/74732674/f3c9dd26-6164-4e6d-acf7-73340dcc4ed7)
