### ISSUE TITLE
Game fails to work if fonts for new font engine are missing

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#600]
**Describe the issue**

Attempt to play the game with old assets without `fonts` directory leads the assert at the FontManager code.

**Example Case**

![Screenshot_20230828-165244_TheXTech](https://github.com/Wohlstand/TheXTech/assets/6751442/227673bf-69e9-4f91-988b-c6c629e4675a)

```
00:45.591 [Fatal]: <Assertion condition has failed>:
---------------------------------------------------------
File: /home/runner/work/TheXTech/TheXTech/src/fontman/font_manager.cpp(536)
Function: textSize
Condition: g_fontManagerIsInit
---------------------------------------------------------
====Stack trace====
  # 0: 0x7943cbbe34  
  # 1: 0x7943cbc360  
  # 2: 0x7944074160  SDL_ReportAssertion
  # 3: 0x7943bd0f00  _ZN11FontManager8textSizeEPKcmijbj
  # 4: 0x794396ab3c  _Z15SuperTextPixLeniPKci
  # 5: 0x794386e250  _ZN11PauseScreen4InitEib
  # 6: 0x79438416d8  _Z9PauseGame9PauseCodei
  # 7: 0x79437b6e64  _Z8GameMainRK14CmdLineSetup_t
  # 8: 0x79439c84ac  SDL_main
  # 9: 0x794410f9d0  Java_org_libsdl_app_SDLActivity_nativeRunMain
```

**Additional context**

To resolve this issue, the new font manager should fall back to the legacy SMBX's font engine even calling FontManager's API directly. Otherwise, because of this bug, assets that lacks the `fonts` directory will don't work which is absolutely not intented to be: old assets should work as well as new according to goal of the TheXTech, updates of engine shouldn't require user to upgrade their assets to get the game work, but it should disable features that are depends on new-added resources.

**Comment by ds-sloth** [comment]
In addition, I believe that the multi-line split algorithms of the font manager don't work if the fonts aren't initialized. Maybe there is some way to generate hardcoded raster fonts based on the SMBX64 fonts?

**Comment by Wohlstand** [comment]
I could implement a fallback class that uses legacy fonts to print, I got an idea how I could do that.
