### ISSUE TITLE
[Bug] Crash on New SMGX 1.1

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#601]
**Describe the issue**

It crashes in lobby when going to the right (see video), it leaves the game in a state that i need to kill him.

**Example Case**

It happens on this episode, ill leave the savx to skip the intro.

https://smbxarchive.wohlsoft.ru/SMBX%201.3/New%20Super%20Mario%20Galaxy%20X%201.1.zip

[New SMGX.wld-save1.savx.zip](https://github.com/Wohlstand/TheXTech/files/12458659/New.SMGX.wld-save1.savx.zip)

**Recording**

https://github.com/Wohlstand/TheXTech/assets/60852359/d4517099-4461-43f2-ba69-75bf8f2ad7dc

**Additional context**

Im using the latest nightly build.

Included the log file.

[log.txt](https://github.com/Wohlstand/TheXTech/files/12458609/log.txt)

**Comment by Wohlstand** [comment]
I see, here is a bug in the mergeWithMask call, @ds-sloth seems know something on this :eyes:

**Comment by ds-sloth** [comment]
The issue is that `npc-42m.gif` failed to load. I have added code so that the load failure won't crash the entire engine, but hopefully we'll be able to fix the cause of the load failure as well.

**Comment by Wohlstand** [comment]
Okay, just now I made the fix for loading of that GIF file, now it should get loaded properly.

**Comment by M0REKZ** [comment]
Its working now

![Scr_2023-08-29_18-18-07](https://github.com/Wohlstand/TheXTech/assets/60852359/c827374c-b73a-4dba-81ce-960f7c9600c5)

**Comment by Wohlstand** [comment]
Súper :)
