### ISSUE TITLE
Allow using cheats by software keyboard on mobile devices

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#61]
Some levels (such as "Superb Demo 128" at "Prelude To The Stupid") do require users to type cheat code to be passed. Right now on mobile devices that is impossible without the USB-OTG plugged hardware keyboard. There is a possible solution to add the calling for the software keyboard where users will be able to type any cheats they want. That should allow them to easily pass levels that require the user to cheat, or simply allows the user to use chats while casual playthrough.

**Comment by M0REKZ** [comment]
The idea that the keyboard prevents me from seeing the game while it is running does not seem very nice to me ... you could make the game stop while the code is being typed...

Another idea would be to have a cheat menu in which you can select the cheat you want and run it quickly in the game, without having to obnoxiously write the code on the screen every second ("needapowerup" :-1:)

The cheat menu could also be implemented in the computer version :D

**Comment by DerpyBubblez** [comment]
You can pause the game then input the cheat already. It doesn't need to be forced on the player.

**Comment by M0REKZ** [comment]
You may be right, but the idea of ​​the cheat menu would destroy that hassle of typing the same code every second.

**Comment by ds-sloth** [comment]
For devices that use the onscreen keyboard (game pad, touchscreen), is it better to add the cheat entry screen as an option on the pause menu or to have a hot key to start it (or onscreen key, for mobile)? If a pause option, players would need to enable it in the settings of course.

**Comment by suicvne** [comment]
In my humble opinion, for an OSK type interface, I feel a pause menu option may be better. I'm not sure if the plan is to pause the game while cheats are being input via OSK/game pad methods, but if not, accidentally triggering the hot key could have disastrous consequences in the middle of a run.

**Comment by ds-sloth** [comment]
So, in all cases, when the software keyboard is up the game will be paused. However, the question is whether the software keyboard should exclusively be brought up by a hot key, or whether it could also be brought up by a pause menu option.

**Comment by suicvne** [comment]
I'm still in favour of a pause menu option for that. It's infrequent enough, imho.

**Comment by Wohlstand** [comment]
At #243, for Android, I made the way to call the cheat typing dialog using the Start+ControlShowHide combination.
