### ISSUE TITLE
BUG of Tr-ID Mode Translation with same strings

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#614]
![Scr_2023-09-12_08-56-07](https://github.com/Wohlstand/TheXTech/assets/37089530/49083e29-3d0b-40bc-a3e3-ba6309582963)
[Same TR-ID Strings Test.zip](https://github.com/Wohlstand/TheXTech/files/12581353/Same.TR-ID.Strings.Test.zip)

When using same strings with Tr-Id Mode (even with different String Key; in both "event" and "NPC dialogue"), the other one got screwed up!!!

_Tested with: Nostalgic Paradise_

**Comment by Wohlstand** [comment]
Going to check this out...

**Comment by Wohlstand** [comment]
I fixed this bug just now: the reason was a messing with a storage that tracks for the uniqueness of strings and trired to share the same string index if there are duplicates. So, I made it update the index when updating the string.

**Comment by LoveBodhi** [comment]
![Scr_2023-09-12_11-30-07](https://github.com/Wohlstand/TheXTech/assets/37089530/dae2fe7d-b0b0-4c3f-a1ea-42c597227f1f)

No more problem.
