### ISSUE TITLE
Ceiling crush bugfix too permissive

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#620]
My bugfix for a ceiling crush bug (#394) was too permissive. As a result, the player can unexpectedly survive crushes that should kill them when ducking. This can even cause softlocks by getting the player stuck in the ground.

Current behavior (bugfix enabled):
<img width="400" height="300" src="https://github.com/Wohlstand/TheXTech/assets/72112344/3067107c-fab2-40c6-aa83-17d03b812560">

Correct behavior (bugfix disabled):
<img width="400" height="300" src="https://github.com/Wohlstand/TheXTech/assets/72112344/da627b0f-11cc-4bbf-b72d-66c655fc563d">

This should be resolved before releasing Version 1.3.6.1.

**Comment by ds-sloth** [comment]
This case should be fixed now, I added a timer to use the stricter collision logic after a cancelled crush death (which was the cause of the issue here).

@Wohlstand, please provide a quick test when possible.

**Comment by ds-sloth** [comment]
On further testing, the bug still occurs when a ducked Boot is lost due to the ceiling spikes.

I'm not sure how to fix this in a fair way, since the new crush death condition doesn't apply for any frames here. (StandUp is set when a ducked Boot is lost, and this prevents the Top3 pinch spot from being set.) It would be possible to always use the strict condition after touching spikes, but this would result in an unfair death if there were a spiked floor and a sloped ceiling.

**Comment by ds-sloth** [comment]
I've refined the new crush detection condition so that player gets crushed if:
(i) player is touching walls on left and right, at least one of them is moving
(ii) player is touching floor and ceiling, at least one of them is moving
(iii) player is touching moving floor OR moving ceiling, and also walls on left and right

This produces good results on all the levels and test cases I've checked (including the Dungeon of Pain in TI2). Please verify that everything seems good on your side.

**Comment by LoveBodhi** [comment]
![Scr_2023-10-13_07-43-13](https://github.com/Wohlstand/TheXTech/assets/37089530/103111a2-e15d-45cb-99a0-4e19b3d06d59)

Is it does like this?

**Comment by ds-sloth** [comment]
Very nice test case! Visually, everything looks how I would expect it to look. Does it behave the same way in Modern and in Compat mode?

**Comment by LoveBodhi** [comment]
![Scr_2023-10-13_07-46-48](https://github.com/Wohlstand/TheXTech/assets/37089530/4810a5fe-597a-433a-a9f1-dae3fce14792)
If compat mode: Player will die when standing on moving layer with a ground

**Comment by LoveBodhi** [comment]
Everything Else should be same.

**Comment by ds-sloth** [comment]
Excellent, thanks very much for the test! I'll leave the issue open in case @Wohlstand has any comments, but this should be complete.

**Comment by Wohlstand** [comment]
I have nothing, I'll just close.
