### ISSUE TITLE
[gameinfo.ini] Certain Cheat Renames/Aliases Don't Work

### ISSUE THREAD

**Issue by DanielMKruse** [Wohlstand/TheXTech#656]
v1.3.6.2 Windows

I use cheat aliases to make inputting cheats much easier, as typing in the entire cheat without messing up sequentially is cumbersome. However, I have noticed that some aliases do not work for me no matter what I tried, such as "sonicstooslow". I would go and test every cheat, but there are I think 66 in total, which is a drag.

Here are examples of what I have in my text file:

[cheats-level-aliases]
donthurtme = 2g                      <--- Works
ahippinandahoppin = 2j              <--- Works
flamethrower = 2f              <--- Works
shadowstar = 2w              <--- Works
needahammersuit = 2h              <--- Works
needatanookisuit = 2t              <--- Works
sonicstooslow = 2s              <--- Doesn't Work

**Comment by Wohlstand** [comment]
I guess, I should document all these cheats to let people don't make such mistakes in next time.

**Comment by DanielMKruse** [comment]
Thanks for the clear up

**Comment by Wohlstand** [comment]
Closing as solved.

**Comment by Wohlstand** [comment]
I made this list of cheats to help you (and other people) to figure what actual cheat key should be used in the gameinfo-ini: https://github.com/Wohlstand/TheXTech/wiki/Cheat-codes
