### ISSUE TITLE
[Latest Dev Build BUG] Font1_9 (Status Bar Font) didn't show without "fonts" folder

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#674]
![Scr_2023-12-20_16-41-04_1](https://github.com/Wohlstand/TheXTech/assets/37089530/33c86c7e-793b-4015-8558-d67643d820cd)

**Comment by ds-sloth** [comment]
Thanks very much for the report! Can you please check whether this has been fixed?

**Comment by LoveBodhi** [comment]
![Scr_2023-12-21_07-50-28](https://github.com/Wohlstand/TheXTech/assets/37089530/13cba227-3426-45d4-ab6a-207016ec933c)
Fixed.
