### ISSUE TITLE
Bug: World Map Music Doesn't Change Unless Player Stops On Trigger

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#68]
While playing Super Talking Time Bros 2 I noticed that the world map music didn't correctly change in a lot of places. At first I thought maybe the triggers were missing or something, but upon inspecting it in PGE Editor I noticed the triggers were there.

Then, I realized that if I continued holding the direction and passed over the tile with the trigger it's never... uh... triggered, but if I stop on it, it is.

Tested using
**Commit:** 2f80725
**CPU Architecture:** x86_64
**OS:** Linux Mint 20.1
**Episode:** Super Talking Time Bros. 2

**Comment by Wohlstand** [comment]
Fixed just now!
I had to make the 16 pixels margin at all QuadTree queries as you won't be able to find the thing by the approximated search using absolute values.

**Comment by ChristianSilvermoon** [comment]
> Fixed just now!
> I had to make the 16 pixels margin at all QuadTree queries as you won't be able to find the thing by the approximated search using absolute values.

Tested and that definitely seems to have fixed it, you're awesome ^^
