### ISSUE TITLE
[BUG] Flips Y when taking screenshot by using OpenGL 1.1 Renderer

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/TheXTech#683]
![Scr_2024-01-06_07-11-56](https://github.com/Wohlstand/TheXTech/assets/37089530/3c2a6cea-1510-4684-934c-98d01876bdbd)

**Comment by ds-sloth** [comment]
Thanks very much for the report. Please let me know whether the issue has been fixed.

**Comment by LoveBodhi** [comment]
![Scr_2024-01-06_08-44-51](https://github.com/Wohlstand/TheXTech/assets/37089530/e9e9bc36-2c47-43f8-ba07-c29154300e6d)
Fixed now
