### ISSUE TITLE
Vanilla / TheXTech bug: slope cancels other ground block

### ISSUE THREAD

**Issue by ds-sloth** [Wohlstand/TheXTech#689]
While testing Yoshi's Archipelago, and standing on a downward moving slope, I found myself clipping into the ground and dying unexpectedly. This isn't the kind of polish I expect from YA and I was worried that we had introduced a bug.

Indeed, the exact case from YA does not cause clipping or death in SMBX 1.3, but a very similar case where the slope is AFTER the block in the Blocks array does cause clipping and deaths.

**My test level**: [subcon area house.lvl.zip](https://github.com/Wohlstand/TheXTech/files/13944393/subcon.area.house.lvl.zip)

**Our bug (YA case)**:
<img src="https://github.com/Wohlstand/TheXTech/assets/72112344/3fa415e8-b8a0-4ef2-bf31-f43bf1adb888" width="400" height="300"> <img src="https://github.com/Wohlstand/TheXTech/assets/72112344/2ae34b74-a4a0-434e-9389-6a2c8af3d50a" width="400" height="300">

**Vanilla bug**:
<img src="https://github.com/Wohlstand/TheXTech/assets/72112344/a0a5e52d-f8db-4040-8f8e-0ab6e4ac7799" width="400" height="300"> <img src="https://github.com/Wohlstand/TheXTech/assets/72112344/92a49297-603b-478a-8506-d904521172bb" width="400" height="300">

I've added a fix for this to the main branch, guarded by `fix-player-downward-clip`. I'll also put this fix in the stable branch after our 1.3.6.4 release. Important note: this is the same flag used to guard other `fix-player-downward-clip` cases, and the bugfix is enabled in Mode 2.

**New behavior**:
<img src="https://github.com/Wohlstand/TheXTech/assets/72112344/a10dfffd-4dee-4394-aa95-b28559834d61" width="400" height="300"> <img src="https://github.com/Wohlstand/TheXTech/assets/72112344/70ffce80-0f66-48df-88fc-61ae23705dc6" width="400" height="300">

It would be great if some people could test slope-ground collisions, especially when they are moving, in order to make sure that this fix doesn't introduce any regressions.

**Comment by 0lhi** [comment]
Mode 2 [clipping](https://clips.twitch.tv/GenerousFilthyVanillaRalpherZ-p2cwboBPfyo-ue8P) is fixed 👍

![Scr_2024-01-19_12-58-46](https://github.com/Wohlstand/TheXTech/assets/74732674/de3ad6dc-188d-4a71-8620-39bf6ccda2c5)

**Comment by ds-sloth** [comment]
0lhi and I have both tested this and it was included in Release 1.3.6.3.
