### ISSUE TITLE
Untie id and class

### ISSUE THREAD

**Issue by Shadowblitz16** [Wohlstand/TheXTech#692]
What if entity behavior was tied to a dynamic enum type instead of their id?

Then we could say take npc-x and change it's type to be npc-y and then npc-x then acts exactly like npc-y

**Comment by Wohlstand** [comment]
Here is a plan for the future to turn entire spahgetti code into array of function pointers, and that will allow assigning of different algorithms to any ID.

**Comment by ds-sloth** [comment]
This is a good suggestion, also see #282 for more notes on the idea.

**Comment by ds-sloth** [comment]
Closing as an approximate duplicate of #282, and as a portion of #472.
