### ISSUE TITLE
Feature Request: Automatic World Map Path Movement

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#70]
Traditionally in a Mario game, path traversal is automatic until a fork or level is reached. It should be possible to determine whether or not the player is at a fork or level and stop automatic movement.

Additionally if the player presses the opposite direction, they should be able to change directions mid-move.

This would be a nice bit of polish, and especially helpful for Episodes which have long and winding paths. I can't think of anything that'd be broken in any Episodes by such a change.

The player also traditionally moves from the current level to the next and takes a world map warp if possible, but implementing this could be undesirable as it may lead to being permanently locked out of areas in some episodes and would add complexity when it came to forks.

So, just for traversing from one level or fork to another, would be ideal.

**Comment by Wohlstand** [comment]
In most that is an easy check by keeping the count of available directions for every cell

**Comment by ds-sloth** [comment]
Not too hard to do. :)

I have implemented this and will add a config option for it soon, then push to my branch.

![Scr_2021-06-03_12-13-02](https://user-images.githubusercontent.com/72112344/120678336-fd93e080-c465-11eb-9760-6db12cb39dfa.gif)

**Comment by ds-sloth** [comment]
Fully implemented; will merge into the primary branch when the related quadtree code is fully verified.

**Comment by 0lhi** [comment]
Are there any updates on this?

**Comment by ds-sloth** [comment]
Now that `multires` is merged, it's available in the primary branch via `settings.ini` option `world-map-fast-move`. Thanks for checking!

**Comment by ds-sloth** [comment]
Wohlstand is planning a large-scale improvement of the settings UI that will make this configurable via GUI also

**Comment by 0lhi** [comment]
> Now that multires is merged, it's available in the primary branch via settings.ini option world-map-fast-move. Thanks for checking!

Nice! Confirm that it's working =)

However, needs to be disabled for Speedrun Mode 2 and 3.

Also, would it be possible to have a Compat.ini setting to enable it for certain Episodes even when the setting is set to disabled?

**Comment by ds-sloth** [comment]
@0lhi good suggestions, I suppose that this should not be considered complete until we have it implemented with speedrun and compat.

Plan:

* `compat.ini` has an option `fast-world-map-movement` with values `force`, `allow`, and `forbid`.
* Speedrun modes 2 and 3 set this to `forbid`.
* In pseudocode, enable the feature if `(compat.fastMove == force || compat.fastMove == allow && config.fastMove == on)`.

How does that plan sound to you?

**Comment by 0lhi** [comment]
The decision of the episode creator should take priority over the decision of the player. So, it should be like this:

1. Speedrun Mode 2 and 3 will disable it no matter what.

2. Episode Creators can dedicate what's the case for their episodes through Compat.ini.

3. Settings allow the Player to choose for episodes where it's not specified.

**Comment by ds-sloth** [comment]
I believe those words are equivalent to the pseudocode I posted in my last message. However, I do not remember how manually specified `compat.ini` values interact with speedrun-set `compat` values. It sounds like you are saying you want the speedrun to override the episode-specific values.

**Comment by ds-sloth** [comment]
Added parentheses to the pseudocode. Thank you for the clarification!

**Comment by 0lhi** [comment]
Yup. I misinterpreted the code. My bad.

> It sounds like you are saying you want the speedrun to override the episode-specific values.

Yes. Mode 2 and 3 have to strictly enforce the old game's behavior.

**Comment by ChristianSilvermoon** [comment]
I believe this was implemented as of 8c123ed, which is currently available in devel

Would this be closable now?

**Comment by Wohlstand** [comment]
Oh, looks like this is a feature that we forgot to add into backporting list....

**Comment by ds-sloth** [comment]
This one should be really easy to backport now. We shouldn't even need to make a branch, it's just a procedure or two and a new config option.

**Comment by ds-sloth** [comment]
Has been available in the main branch for a few months now.
