### ISSUE TITLE
[Arch Linux] Display Problem

### ISSUE THREAD

**Issue by SkullGamer205** [Wohlstand/TheXTech#700]
**OS:** `Arch Linux`
**Kernel:** `6.7.0-arch3-1`
**TheXTech Version:** `TheXTech 1.3.7-dev` (branch `main`, commit f61b14d4)

**Problem:** The game displays one color instead of pictures/display
`Error while SDL Initialization: Failed loading udev_device_get_action: /home/skullgamer205/.git_dir/TheXTech/build/output/lib/libSDL2-2.0.so.0: undefined symbol: _udev_device_get_action`
**Logs:** [here](https://github.com/Wohlstand/TheXTech/files/14006120/TheXTech_log_2024_01_22_16_36_13.txt)
**Video:** [here](https://wohlnet.ru/sentfile/oneday/2024-01-22_16-42-53.mp4)
**Change Render doesn't resolve problem.**

```
$ ldd -r /home/skullgamer205/applications/Mario/smbx/TheXTech/smbx
	linux-vdso.so.1 (0x00007ffe8fda9000)
	libSDL2_mixer_ext.so.2 => /home/skullgamer205/.git_dir/TheXTech/build/output/lib/libSDL2_mixer_ext.so.2 (0x000070046f800000)
	libSDL2-2.0.so.0 => /home/skullgamer205/.git_dir/TheXTech/build/output/lib/libSDL2-2.0.so.0 (0x000070046fd40000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x000070046f720000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x000070046f400000)
	libm.so.6 => /usr/lib/libm.so.6 (0x000070046f313000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x000070046f6fb000)
	libc.so.6 => /usr/lib/libc.so.6 (0x000070046f131000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x000070046f079000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x000070046f6c9000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x000070046fed9000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x000070046ef36000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x000070046f69e000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x000070046fd37000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x000070046fd2f000)
```

**Comment by Wohlstand** [comment]
The undefined `_udev_device_get_action` error happens everywhere, and it doesn't means anything.

**Comment by SkullGamer205** [comment]
> The undefined `_udev_device_get_action` error happens everywhere, and it doesn't means anything.

Interesting.

**Comment by SkullGamer205** [comment]
In addition: Versions up to main (1.3.6.2 git) worked flawlessly.
1.3.6.3-stable works great.

**Comment by ds-sloth** [comment]
I'll take a look at your logs. It may be helpful to set your logging level to debug temporarily.

**Comment by ds-sloth** [comment]
Your OpenGL logs are showing a minor error where one of the frame buffers was not correctly initialized. I'll try to reproduce that on my side soon.

It's possible that error was linked with this issue. Can you please test the game in SDL mode? (`-r sdl`?)

**Comment by SkullGamer205** [comment]
> It's possible that error was linked with this issue. Can you please test the game in SDL mode? (`-r sdl`?)
[Logs](https://github.com/Wohlstand/TheXTech/files/14021546/TheXTech_log_2024_01_23_19_30_37.txt)
Problem not resolved.

**Comment by ds-sloth** [comment]
> Problem not resolved

Very strange. Would you be willing to find a commit in the main branch that works and use git bisect to find where the issue was introduced? Two possible places would be the multires merge into main this week and the render depth update in December.

**Comment by SkullGamer205** [comment]
a267ac2 and higher have problems...

**Comment by SkullGamer205** [comment]
Guys
Issue closed.

I Found problem

After update and first open new version TheXTech add in my config two lines (in `[video]`)
```
internal-height = 1
internal-width = 1
```

**Comment by SkullGamer205** [comment]
I rename old configuration and retry to open and game works good.

IDK why i don't do this before...
