### ISSUE TITLE
Allow binding press and movement input in editor

### ISSUE THREAD

**Issue by Shadowblitz16** [Wohlstand/TheXTech#701]
Please allow us to binding whatever right trigger is and the left joy is in the editor

**Comment by ds-sloth** [comment]
Are you saying that you want to be able to bind them *inside* the editor, or that you want to be able to bind them at all? To do it at all, you need to go to your controller profile's settings, and adjust the "Cursor Controls" to set the left click, and the "Editor Controls" to set the scrolling.

**Comment by Shadowblitz16** [comment]
oh why is it under cursor controls instead of editor controls?

**Comment by ds-sloth** [comment]
The cursor controls also apply on the main menu, the Drop/Add screen, and a few other areas.

**Comment by Shadowblitz16** [comment]
Oh I meant more of just for the editor only

**Comment by ds-sloth** [comment]
You are free to set an alternative Click control (you can bind two buttons to it), and only actually use that button in the editor. It won't mess up gameplay, even if the button is also bound to a player control during normal gameplay.

I'm hesitant to separate the Click action in the editor from the Click action in the rest of the engine, but if more people demand it we can consider doing that.
