### ISSUE TITLE
Editor may benefit from removing tileset groups in favor of large scrollable tilesheet

### ISSUE THREAD

**Issue by Shadowblitz16** [Wohlstand/TheXTech#703]
The editor may benefit from removing tileset groups in favor of large scrollable tilesheet
Of course this would only be useful if the cursor was both saved when closing the dialog and snapped to the nearest tile.

**Comment by Shadowblitz16** [comment]
https://github.com/Wohlstand/TheXTech/issues/704

**Comment by ds-sloth** [comment]
Tileset groups will be kept for sure; they organize the editor and help users understand how Magic Block will behave. The idea of the cursor snapping to buttons is interesting. Let's discuss that more in #704.

**Comment by Shadowblitz16** [comment]
@ds-sloth I don't even know what magic blocks are care to explain?

**Comment by ds-sloth** [comment]
Magic Block is TheXTech's auto-tiling system. There should be an icon to enable it in the upper-right side of the block select pane.
