### ISSUE TITLE
SMB3 Levels

### ISSUE THREAD

**Issue by Shadowblitz16** [Wohlstand/TheXTech#725]
Can we have a flag the forces paths to show even if the level is not beaten?

Of course the level would still be impassable until beaten

**Comment by ds-sloth** [comment]
Please check [this note](https://github.com/Wohlstand/TheXTech/wiki/Considerations-for-Contributors#an-important-note-on-the-scope-of-thextech) on the scope of TheXTech.

> a flag that forces paths to show, but still be impassable

Place both a scenery and a path in the same location, using the same sprite.
