### ISSUE TITLE
Feature Request: Play sound-58 when Selecting "Save and Continue" instead of sound-30

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#73]
Traditionally this sound is used in SMW to indicate saving the game, but no special sound is currently used, giving no audio cue as to whether or not the game was actually saved or if the game was just unpaused.

**Comment by Wohlstand** [comment]
Done quickly :fox_face: :+1:

**Comment by ChristianSilvermoon** [comment]
Darn that *was* quick XD
I didn't even realize until just now x3

Tested (x86_64 Linux Mint), can confirm it works :P
