### ISSUE TITLE
nsmbx  vegetals dont hurt npcs

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#8]
on nsmbx 1.0, the smb2 vegetals (and eggs) dont hurt npc

**Comment by mlloewen** [comment]
I believe this was fixed in commit "Fixed invincible npc bug"  by @textmonster404

textmonster404 committed 3 days ago commit 6e6e714fc2483f0e195d950eb500e6bf2c0a5e6d

The smb2 levels are working fine in the git build.
