### ISSUE TITLE
Link's upward sword rising through a column of blue grab blocks (npc-45)

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#82]
If you make a column of grab blocks, and Link stabs upwards through it, he is boosted through the column until he reaches the top. This needs compatibility because I remember an episode that uses the glitch as a joke.

**Comment by Wohlstand** [comment]
Yeah, I probably saw somewhere it got used :grin:

**Comment by P-Star7** [comment]
Has improved report
