### ISSUE TITLE
(Bug) Dragon Coins turn into SMB3 brick with P-Switch

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#87]
The first issue being that, if we hide the dragon coin behind a p-switch, the player can break it by accident. The second issue is that SMW dragon coin turning into SMB3 block! In SMW the correct behavior is to not change the dragon coin at all.

**Comment by 0lhi** [comment]
Works 👍

![Scr_2021-06-04_21-43-10](https://user-images.githubusercontent.com/74732674/120855294-91f16680-c57e-11eb-96b7-19bf87663e5e.gif)

![Scr_2021-06-04_21-46-08](https://user-images.githubusercontent.com/74732674/120855307-961d8400-c57e-11eb-9979-f10358268b12.gif)

[Coin.zip](https://github.com/Wohlstand/TheXTech/files/6600945/Coin.zip)

**Comment by Wohlstand** [comment]
Thanks for the confirmation! :fox_face: :+1:
