### ISSUE TITLE
(Cosmetic) Mario, Luigi, Peach, Toad stationary for a moment before upwards movement in death

### ISSUE THREAD

**Issue by P-Star7** [Wohlstand/TheXTech#97]
I will check how many frames Mario is still for before his death movement in SMB3, but I am putting this here already so I do not forget.

**Comment by ds-sloth** [comment]
In order to not alter gameplay, if we add this, then we should make the respawn delay lower by the same number of frames after the player leaves the screen.

**Comment by P-Star7** [comment]
The timing for Mario and Luigi in SMB3: A halt of 48 frames before they start moving upwards.

**Comment by ds-sloth** [comment]
Also out of scope for current aims.
